/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.classgroupingscheme;

import com.lztech.site.viewmodel.classgroupingscheme.*;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-06-23T05:58:18.497Z")

@Validated
@Api(value = "classgroupingscheme", description = "the classgroupingscheme API")
@RequestMapping(value = "/v1")
public interface ClassGroupingSchemeApi {

    @ApiOperation(value = "获取班级分组方案信息接口", nickname = "getClassGroupingSchemeList"
            , notes = "调用方：1、云课堂老师web端-班级小组方案查询", response = ClassGroupingSchemeVo.class
            , responseContainer = "List", tags = {"ClassGroupingScheme",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ClassGroupingSchemeVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/classgroupingscheme",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<ClassGroupingSchemeVo>> getClassGroupingSchemeList(
            @NotNull @ApiParam(value = "班级id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @NotNull @ApiParam(value = "验证码：groupId={XXX}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "小组方案类型 0:普通小组；1：实验小组")
            @Valid @RequestParam(value = "schemaType", required = false) Integer schemaType);


    @ApiOperation(value = "删除班级分组方案信息接口", nickname = "deleteClassGroupingScheme"
            , notes = "调用方：1、云课堂老师web端-班级小组方案删除", tags = {"ClassGroupingScheme",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/classgroupingscheme/delete",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteClassGroupingScheme(
            @NotNull @ApiParam(value = "班级分组方案id", required = true)
            @Valid @RequestParam(value = "classGroupingSchemeId", required = true) String classGroupingSchemeId,
            @NotNull @ApiParam(value = "验证码：classGroupingSchemeId={xxx}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "新增班级分组方案接口",
            nickname = "insertClassGroupingScheme", notes = "云课堂老师端-新增班级分案调用",
            tags = {"ClassGroupingScheme",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/classgroupingscheme",
            method = RequestMethod.POST)
    ResponseEntity<Void> insertClassGroupingScheme(@NotNull
                                                   @ApiParam(value = "验证码（groupId={}&signKey=123123）", required = true)
                                                   @Valid @RequestParam(value = "validCode", required = true)
                                                           String validCode,
                                                   @NotNull @ApiParam(value = "班级id", required = true)
                                                   @Valid @RequestParam(value = "groupId", required = true)
                                                           String groupId,
                                                   @ApiParam(value = "", required = true) @Valid
                                                   @RequestBody ClassGroupingSchemeInsertResource schemeResource);

    @ApiOperation(value = "获取班级分组方案详情", nickname = "getClassGroupingSchemeDetail",
            notes = "1、云课堂老师端-获取班级分组方案详情接口", tags = {"ClassGroupingScheme",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到此班级方案", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/classgroupingscheme/{id}",
            method = RequestMethod.GET)
    ResponseEntity<ClassGroupingSchemeResource> getClassGroupingSchemeDetail(@NotNull @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
                                                                             @Valid @RequestParam(value = "validCode", required = true)
                                                                                     String validCode,
                                                                             @ApiParam(value = "班级分组方案id", required = true)
                                                                             @PathVariable("id") String id);

    @ApiOperation(value = "校验添加实验小组方案", nickname = "checkCanAddExperimentalGroupingScheme",
            notes = "云课堂老师端-校验能否添加实验小组方案", tags = {"ClassGroupingScheme",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = GroupingSchemeAddCheckedResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "无法添加实验小组方案"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/classgroupingscheme/checkaddexperimental",
            method = RequestMethod.POST)
    ResponseEntity<GroupingSchemeAddCheckedResource> checkCanAddExperimentalGroupingScheme(@NotNull @ApiParam(value = "验证码（groupId={}&signKey" +
            "=123123）", required = true)
                                                                                           @Valid @RequestParam(value = "validCode", required = true)
                                                                                                   String validCode,
                                                                                           @NotNull @ApiParam(value = "班级id", required = true)
                                                                                           @Valid @RequestParam(value = "groupId", required = true)
                                                                                                   String groupId);

    @ApiOperation(value = "获取课程下所有小组的负责老师", nickname = "getResponsibleTeacher", notes = "云课堂老师端-实验互评获取负责老师",
            response = GroupingSchemeTeacher.class, responseContainer = "List", tags={ "ClassGroupingScheme", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = GroupingSchemeTeacher.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/classgroupingscheme/responsibleteacher",
            method = RequestMethod.GET)
    ResponseEntity<List<GroupingSchemeTeacher>> getResponsibleTeacher(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "班级id(多个班级用“，”隔开)", required = true)
            @Valid @RequestParam(value = "groupIds", required = true) String groupIds,
            @NotNull @ApiParam(value = "老师名称", required = true)
            @Valid @RequestParam(value = "teacherName", required = true) String teacherName);


    @ApiOperation(value = "获取老师负责下的所有小组", nickname = "getResponsibleClassGroup", notes = "云课堂老师端-实验互评获取负责小组", response = ClassGroupingVO.class,
            responseContainer = "List", tags={ "ClassGroupingScheme", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = ClassGroupingVO.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/classgroupingscheme/responsibleclass",
            method = RequestMethod.GET)
    ResponseEntity<List<ClassGroupingVO>> getResponsibleClassGroup(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "老师Id") @Valid @RequestParam(value = "teacherId", required = false) String teacherId,
            @ApiParam(value = "小组名称") @Valid @RequestParam(value = "className", required = false) String className);

    @ApiOperation(value = "根据班级，负责老师，负责小组，获取课程下所有学生信息", nickname = "getResponsibleStudent",
            notes = "teachingApi:云课堂老师端-老师端获取同伴互评项目评价统计-接口调用", response = GroupingSchemeStudent.class,
            responseContainer = "List", tags={ "ClassGroupingScheme", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = GroupingSchemeStudent.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/classgroupingscheme/responsiblestudent",
            method = RequestMethod.GET)
    ResponseEntity<List<GroupingSchemeStudent>> getResponsibleStudent(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "班级id(多个班级用“，”隔开)", required = true)
            @Valid @RequestParam(value = "groupIds", required = true) String groupIds,
            @ApiParam(value = "负责老师ID") @Valid @RequestParam(value = "responsibleTeacherId", required = false) String responsibleTeacherId,
            @ApiParam(value = "小组ID") @Valid @RequestParam(value = "classGroupId", required = false) String classGroupId);

}
