/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.dibblingvideo;

import com.lztech.site.viewmodel.coursetable.CourseTableVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-28T06:15:56.376Z")

@Api(value = "dibblingvideo", description = "the dibblingvideo API")
@RequestMapping(value = "/v1")
public interface DibblingvideoApi {

    @ApiOperation(value = "获取课程视频详情信息", nickname = "dibblingvideoCoursetablePost", notes = "云课堂-管理端",
            response = CourseTableVo.class, tags = {"DibblingVideo",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableVo.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/dibblingvideo/coursetable",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CourseTableVo> dibblingvideoCoursetableGet(
            @NotNull @ApiParam(value = "课表Id", required = true)
            @Valid @RequestParam(value = "id", required = true) String id,
            @NotNull @ApiParam(value = "&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
