/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.groupmembers;

import com.lztech.site.resource.group.ImportGroupMemberResource;
import com.lztech.site.viewmodel.StudentInfo;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.group.*;
import com.lztech.site.viewmodel.groupmember.GroupMemberBranch;
import com.lztech.site.viewmodel.userinfo.UsersInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-19T08:59:41.236Z")

@Api(value = "groupmembers", description = "the groupmembers API")
@RequestMapping(value = "/v1")
public interface GroupmembersApi {

    @ApiOperation(value = "获取班级成员信息", nickname = "groupmembersGroupIdGet", notes = "云课堂前端使用",
            response = UsersInfo.class, responseContainer = "List", tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = UsersInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupmembers/{groupId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<UsersInfo>> groupmembersGroupIdGet(@ApiParam(value = "组Id", required = true)
                                                           @PathVariable("groupId") String groupId,
                                                           @NotNull @ApiParam(value = "验证码：groupId=?&signKey=123123(md5加密)",
                                                                   required = true)
                                                           @Valid @RequestParam(value = "validCode", required = true)
                                                           String validCode,
                                                           @ApiParam(value = "学号/工号或者姓名")
                                                           @Valid @RequestParam(value = "userNoOrName", required = false)
                                                           String userNoOrName);


    @ApiOperation(value = "获取当前课程上课老师信息", nickname = "groupteachersGet", notes = "云课堂前端使用",
            response = UsersInfo.class, responseContainer = "List", tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = UsersInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupteachers",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<UsersInfo>> groupteachersGet(@NotNull @ApiParam(value = "组Id", required = true)
                                                     @Valid @RequestParam(value = "groupId", required = true)
                                                     String groupId,
                                                     @NotNull @ApiParam(value = "课程Id", required = true)
                                                     @Valid @RequestParam(value = "courseId", required = true)
                                                     String courseId,
                                                     @NotNull
                                                     @ApiParam(value = "验证码：groupId=?&signKey=123123(md5加密)",
                                                             required = true)
                                                     @Valid @RequestParam(value = "validCode", required = true)
                                                     String validCode);

    @ApiOperation(value = "根据组名称和学号/工号查询组成员信息", nickname = "groupmembersGet", notes = "云课堂前端使用",
            response = GroupMembersResource.class, responseContainer = "List", tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = GroupMembersResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupmembers",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<GroupMembersResource>> groupmembersGet(@NotNull @ApiParam(value = "组名称", required = true)
                                                               @Valid @RequestParam(value = "groupName", required = true)
                                                               String groupName,
                                                               @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)",
                                                                       required = true)
                                                               @Valid @RequestParam(value = "validCode", required = true)
                                                               String validCode, @ApiParam(value = "学号/工号")
                                                               @Valid @RequestParam(value = "userNo", required = false)
                                                               String userNo);


    @ApiOperation(value = "Excel导入班级成员", nickname = "groupImportgroupmembersPost", notes = "云课堂前端使用",
            response = ImportGroupMemberResource.class, tags = {"ImportGroupMember",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ImportGroupMemberResource.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到导入的Excel信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/importgroupmembers",
            produces = {"application/json"},
            consumes = {"multipart/form-data"},
            method = RequestMethod.POST)
    ResponseEntity<ImportGroupMemberResource> groupImportgroupmembersPost(
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "课程Id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "组Id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @ApiParam(value = "成员信息")
            @Valid @RequestPart(value = "groupMember", required = true) MultipartFile groupMember,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "删除班级成员", nickname = "groupDeletegroupmembersDelete", notes = "云课堂前端使用", tags = {"DeleteGroupMember",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到学生信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/deletegroupmembers",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> groupDeletegroupmembersDelete(
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "老师姓名", required = true)
            @Valid @RequestParam(value = "teacherName", required = true) String teacherName,
            @NotNull @ApiParam(value = "组Id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "学生id")
            @Valid @RequestParam(value = "studentId", required = false) String studentId);


    @ApiOperation(value = "批量删除班级成员", nickname = "groupBatchdeletegroupmembersPost", notes = "小程序端使用", tags = {"BatchDeleteGroupMembers",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到学生信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/batchdeletegroupmembers",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> batchDeleteGroupMembers(
            @NotNull @ApiParam(value = "组Id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "学生Id 使用,分割的字符串", required = true)
            @Valid @RequestParam(value = "studentIds", required = true) String studentIds,
            @NotNull @ApiParam(value = "教师姓名", required = true)
            @Valid @RequestParam(value = "teacherName", required = true) String teacherName,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );


    @ApiOperation(value = "根据学生Id或微信openId查询成员信息", nickname = "groupmembersUserIdOrOpenIdGet",
            notes = "teachingApi使用", response = UsersInfo.class, tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = UsersInfo.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证失败"),
            @ApiResponse(code = 404, message = "未找到用户信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupmembers/userIdOrOpenId",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<UsersInfo> groupmembersUserIdOrOpenIdGet(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "用户Id") @Valid @RequestParam(value = "userId", required = false) String userId,
            @ApiParam(value = "微信openId") @Valid @RequestParam(value = "openId", required = false) String openId,
            @ApiParam(value = "分组Id") @Valid @RequestParam(value = "groupId", required = false) String groupId,
            @ApiParam(value = "排除删除状态") @Valid @RequestParam(value = "excludeDelete", required = false) Integer excludeDelete
    );

    @ApiOperation(value = "获取组成员信息", nickname = "groupGroupIdMembersGet",
            notes = "小程序使用", response = GroupMembersResource.class, responseContainer = "List",
            tags = {"GroupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = GroupMembersResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/{groupId}/members",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<StudentInfo>> groupGroupIdMembersGet(@ApiParam(value = "组Id", required = true)
                                                             @PathVariable("groupId") String groupId,
                                                             @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true) @Valid
                                                             @RequestParam(value = "validCode", required = true) String validCode);

    //
    @ApiOperation(value = "根据学生姓名或学号模糊获取班级学生信息接口",
            nickname = "getGroupMemberByStudentNoOrNameIsLike",
            notes = "调用方：1、云课堂老师web端-云课堂课程公告", response = StudentVo.class,
            responseContainer = "List", tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = StudentVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/groupmember",
            method = RequestMethod.POST)
    ResponseEntity<List<StudentVo>> getGroupMemberByStudentNoOrNameIsLike(@NotNull @ApiParam(value = "验证码&signKey=123123(md5加密)", required = true)
                                                                          @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                                          @ApiParam(value = "", required = true)
                                                                          @Valid @RequestBody GroupMemberByStudentNoOrNameVo userNoOrUserIdVoList);


    @ApiOperation(value = "根据多个班级获取班级上课老师信息", nickname = "getGroupteachers",
            notes = "课程整体数据：teachingApi使用", response = UsersInfo.class, responseContainer = "List",
            tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = UsersInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groups/teachers",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<List<UsersInfo>> getGroupteachers(
            @ApiParam(value = "", required = true) @Valid @RequestBody GroupsTeachersVo groupId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据学年学期和老师id获取当前学期下老师所有班级助教列表信息", nickname = "groupIdAssistantsGet", notes = "云课堂前端使用",
            response = AssistantResource.class, responseContainer = "List", tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = AssistantResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到学生信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/{id}/assistants",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<AssistantResource>> groupIdAssistantsGet(
            @ApiParam(value = "老师id", required = true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "验证码：id=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据学生id和组id更改学生身份", nickname = "groupmembersStudentidentityPost",
            notes = "云课堂前端使用", tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupmembers/studentidentity",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> groupmembersStudentidentityPost(
            @NotNull @ApiParam(value = "学生id", required = true)
            @Valid @RequestParam(value = "studentId", required = true) String studentId,
            @NotNull @ApiParam(value = "教学班id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @NotNull @ApiParam(value = "学生身份编码(0:学生；1：助教)", required = true)
            @Valid @RequestParam(value = "studentIdentityCode", required = true) Integer studentIdentityCode,
            @NotNull @ApiParam(value = "验证码：studentId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "学生信息批量导入", nickname = "importStudents",
            notes = "调用方：1、云课堂管理端web端-基础数据管理教学班学生信息管理调用",
            response = ImportStudentsVo.class, tags = {"GroupMembers",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ImportStudentsVo.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务异常", response = ImportClassVo.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/groups/importstudents",
            method = RequestMethod.POST)
    ResponseEntity<ImportStudentsVo> importStudents(
            @NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "导入的excel文件") @Valid @RequestPart(value = "importFile", required = true) MultipartFile importFile,
            @NotNull @ApiParam(value = "操作人id", required = true)
            @Valid @RequestParam(value = "operatorid", required = true) String operatorid,
            @NotNull @ApiParam(value = "操作人姓名", required = true)
            @Valid @RequestParam(value = "operatorname", required = true) String operatorName);

    @ApiOperation(value = "获取班级成员上课方式人员分布", nickname = "getGroupMemberBranch",
            notes = "云课堂课表巡课、视频点播、督导听课使用", response = GroupMemberBranch.class, responseContainer = "List",
            tags = {"groupMembersResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = GroupMemberBranch.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupmemberbranch/{groupId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<GroupMemberBranch>> getGroupMemberBranch(
            @ApiParam(value = "组Id", required = true)
            @PathVariable("groupId") String groupId,
            @NotNull @ApiParam(value = "验证码：groupId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据分组成员信息获取组信息", nickname = "getGroupByGroupMember", notes = "根据分组成员信息获取组信息",
            response = GroupResourceVo.class, responseContainer = "List", tags = {"Group",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = GroupResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupmember/group",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<GroupResourceVo>> getGroupByGroupMember(
            @NotNull @ApiParam(value = "学生ID", required = true) @Valid
            @RequestParam(value = "studentId", required = true) String studentId,
            @ApiParam(value = "MD5加密验证字符串 &signKey=123123") @Valid
            @RequestParam(value = "validCode", required = false) String validCode,
            @ApiParam(value = "学年") @Valid @RequestParam(value = "schoolYear", required = false) String schoolYear,
            @ApiParam(value = "学期") @Valid @RequestParam(value = "term", required = false) Integer term);


}
