/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.nowdatetime;

import com.lztech.site.viewmodel.datetime.Times;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-01T06:12:00.909Z")

@Api(value = "nowDateTimes", description = "the nowDateTimes API")
public interface NowTimesApi {

    @ApiOperation(value = "获取当前时间", nickname = "getNowDateTime", notes = "当前时间", response = Times.class, tags = {"NowDateTime",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = Times.class),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "当前未查询到数据"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/nowTimes",
            method = RequestMethod.GET)
    ResponseEntity<Times> getNowTime(
            @NotNull @ApiParam(value = "MD5加密验证字符串", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
