/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teachingresearchsection;

import com.lztech.site.viewmodel.teachingresearchsection.TeachingResearchSectionPage;
import com.lztech.site.viewmodel.teachingresearchsection.TeachingResearchSectionVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-12-24T06:53:58.920Z")

@Api(value = "teachingresearchsection", description = "the teachingresearchsection API")
@RequestMapping(value = "/v1")
public interface TeachingresearchsectionApi {

    @ApiOperation(value = "新增/修改教研室", nickname = "teachingresearchsectionPost", notes = "1、云课堂管理端教研室管理调用", tags = {"teachingResearchSection",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "错误的请求"),
            @ApiResponse(code = 403, message = "验证信息错误"),
            @ApiResponse(code = 409, message = "自定义返回信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingresearchsection",
            method = RequestMethod.POST)
    ResponseEntity<Void> teachingresearchsectionPost(
            @ApiParam(value = "新增/修改的教研室信息", required = true) @Valid @RequestBody TeachingResearchSectionVo teachingResearchSectionVo,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取教研室列表", nickname = "teachingresearchsectionGet", notes = "1、云课堂管理端教研室管理调用",
            response = TeachingResearchSectionPage.class, tags = {"teachingResearchSection",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingResearchSectionPage.class),
            @ApiResponse(code = 400, message = "错误的请求"),
            @ApiResponse(code = 403, message = "验证信息错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingresearchsection",
            method = RequestMethod.GET)
    ResponseEntity<TeachingResearchSectionPage> teachingresearchsectionGet(
            @NotNull @ApiParam(value = "当前页", required = true) @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true) @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-删除教研室", nickname = "teachingresearchsectionDelete", notes = "1.云课堂管理端教研室管理调用", tags = {"teachingResearchSection",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到该教研室信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingresearchsection/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> teachingresearchsectionDelete(
            @NotNull @ApiParam(value = "教研室id", required = true) @Valid @RequestParam(value = "id", required = true) String id,
            @NotNull @ApiParam(value = "id=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


}
