/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.experimentschedulecoursetabledetail;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.experimentschedulecoursetabledetail.*;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2024-09-12T16:34:51.679Z")

@Api(value = "experimentScheduleCourseTableDetails", description = "the experimentScheduleCourseTableDetails API")
@RequestMapping(value = "/v1")
public interface ExperimentScheduleCourseTableDetailsApi {

    @ApiOperation(value = "根据条件获取可以进行实验课排课的数据对接课表列表", nickname = "getDataDockingCourseTableDetailPageResource",
            notes = "1、云课堂管理端", response = DataDockingCourseTableDetailPageResource.class,
            tags = {"ExperimentScheduleCourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = DataDockingCourseTableDetailPageResource.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/experimentschedulecoursetabledetails/datadockingcoursetabledetails",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<DataDockingCourseTableDetailPageResource> getDataDockingCourseTableDetailPageResource(
            @ApiParam(value = "查询参数", required = true)
            @Valid @RequestBody ExperimentScheduleObtainDataParam experimentScheduleObtainDataParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "根据条件导入可以进行实验课排课的数据对接课表", nickname = "importExperimentScheduleCourseTableDetails",
            notes = "1、云课堂管理端", tags = {"ExperimentScheduleCourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/experimentschedulecoursetabledetails/import", produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> importExperimentScheduleCourseTableDetails(
            @ApiParam(value = "查询参数", required = true)
            @Valid @RequestBody ExperimentScheduleObtainDataParam experimentScheduleObtainDataParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "根据条件发布该实验课排课", nickname = "pushExperimentScheduleCourseTableDetail",
            notes = "1、云课堂管理端", response = ExperimentScheduleCourseTableDetailRelevantResource.class,
            tags={ "ExperimentScheduleCourseTableDetails", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentScheduleCourseTableDetailRelevantResource.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/push",
            method = RequestMethod.POST)
    ResponseEntity<ExperimentScheduleCourseTableDetailRelevantResource> pushExperimentScheduleCourseTableDetail(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "发布实验课排课参数" ,required=true )  @Valid @RequestBody
            ExperimentScheduleCourseTableDetailPushParam experimentScheduleCourseTableDetailPushParam
    );

    @ApiOperation(value = "修改实验排课门禁下发状态", nickname = "updateEntranceGuardGeneratedStatus",
            notes = "1、云课堂管理端", response = DataDockingCourseTableDetailPageResource.class,
            tags={ "ExperimentScheduleCourseTableDetails", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = DataDockingCourseTableDetailPageResource.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/{id}/updateentranceguardgeneratedstatus",
            method = RequestMethod.POST)
    ResponseEntity<Void> updateEntranceGuardGeneratedStatus(
            @ApiParam(value = "实验课表id", required = true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "MD5加密验证字符串(id=?&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "门禁生成状态(0:没有生成;1:生成失败;2:生成成功;3:生成失败，没有门禁设备)", required = true)
            @Valid @RequestParam(value = "entranceGuardGeneratedStatus", required = true) Integer entranceGuardGeneratedStatus
            );


    @ApiOperation(value = "根据id获取实验排课信息", nickname = "getExperimentScheduleCourseTableDetailById",
            notes = "1、云课堂管理端", response = ExperimentScheduleCourseTableDetailInfoVo.class,
            tags={ "ExperimentScheduleCourseTableDetails", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentScheduleCourseTableDetailInfoVo.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/{id}",
            method = RequestMethod.GET)
    ResponseEntity<ExperimentScheduleCourseTableDetailInfoVo> getExperimentScheduleCourseTableDetailById(
            @ApiParam(value = "实验课表id",required=true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "操作人id", required = true)
            @Valid @RequestParam(value = "operatorId", required = true) String operatorId,
            @NotNull @ApiParam(value = "操作人名称", required = true)
            @Valid @RequestParam(value = "operatorName", required = true) String operatorName,
            @NotNull @ApiParam(value = "MD5加密验证字符串(id=?&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "根据id取消该实验课排课", nickname = "cancelExperimentScheduleCourseTableDetailById",
            response = ExperimentScheduleCourseTableDetailInfoVo.class,
            notes = "1、内部调用", tags={ "ExperimentScheduleCourseTableDetails", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/{id}/cancel",
            method = RequestMethod.POST)
    ResponseEntity<CancelExperimentScheduleCourseTableDetailModel> cancelExperimentScheduleCourseTableDetailById(
            @ApiParam(value = "排课id",required=true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "操作人id", required = true)
            @Valid @RequestParam(value = "operatorId", required = true) String operatorId,
            @NotNull @ApiParam(value = "操作人名称", required = true)
            @Valid @RequestParam(value = "operatorName", required = true) String operatorName,
            @ApiParam(value = "操作类型（0：仅取消、1：修改前取消）")
            @Valid @RequestParam(value = "operatorType", required = false) Integer operatorType,
            @NotNull @ApiParam(value = "MD5加密验证字符串(id=?&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "根据id和相关条件校验教室是否已被排课", nickname = "checkExperimentScheduleCourseTableDetailById",
            response = CheckExperimentScheduleCourseTableDetailModel.class,
            notes = "1、内部调用", tags={ "ExperimentScheduleCourseTableDetails", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CheckExperimentScheduleCourseTableDetailModel.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/{id}/check",
            method = RequestMethod.POST)
    ResponseEntity<CheckExperimentScheduleCourseTableDetailModel> checkExperimentScheduleCourseTableDetailById(
            @ApiParam(value = "排课id",required=true) @PathVariable("id") String id,
            @ApiParam(value = "校验实验课排课参数" ,required=true )  @Valid @RequestBody
            CheckExperimentScheduleCourseTableDetailParam checkExperimentScheduleCourseTableDetailParam,
            @NotNull @ApiParam(value = "MD5加密验证字符串(id=?&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "获取实验排课操作日志时间线", nickname = "getExperimentScheduleCourseLog",
            notes = "使用方：1、云课堂管理端-实验教学-实验排课；2、云课堂教师端-实验排课",
            response = ExperimentScheduleCourseLogVo.class, responseContainer = "List", tags = {"ExperimentSchedule",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentScheduleCourseLogVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/experimentschedulecoursetabledetails/log",
            method = RequestMethod.GET)
    ResponseEntity<List<ExperimentScheduleCourseLogVo>> getExperimentScheduleCourseLog(
            @NotNull @ApiParam(value = "验证码&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "实验排课待排课表id", required = true)
            @Valid @RequestParam(value = "experimentScheduleId", required = true) String experimentScheduleId);

}
