swagger: "2.0"
info:
  title: 学习资源智能推荐相关接口接口文档
  version: "1.0"
host: 192.168.1.34:8080
basePath: /v1
schemes:
  - https
  - http
paths:

  /courseknowledgegraph/courseresource/canassociation:
    get:
      tags:
        - "CourseKnowledgeGraphCourseResource"
      summary: "获取允许被关联的所有课程资源"
      description: "1.云课堂老师端-课程建设使用"
      operationId: getCourseKnowledgeGraphCanAssociationCourseResource
      parameters:
        - name: "courseId"
          in: "query"
          description: "课程id"
          type: "string"
          required: true
        - name: "versionId"
          in: "query"
          description: "课程id"
          type: "string"
          required: false
        - name: "validCode"
          in: "query"
          description: "验证码&signKey=123123(md5加密)"
          type: "string"
          required: true
        - name: "needUserId"
          in: "query"
          type: "string"
          description: "需要的用户ID，即用户ID创建的资源展示"
          required: false
        - name: "coursewareStatus"
          in: "query"
          type: "integer"
          description: "课件查询状态（null或0：没有限制，1：只查询课件）"
          required: false
      responses:
        200:
          description: "成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CourseStructureVo"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        404:
          description: "未找到资源信息"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

definitions:
  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"
  CourseStructureVo:
    type: "object"
    properties:
      structureId:
        type: "string"
        description: "课程结构id"
      parentId:
        type: "string"
        description: "父id"
      structureName:
        type: "string"
        description: "课程结构名称"
      showOrder:
        type: "integer"
        description: "排序字段"
      childStructureList:
        type: "array"
        items:
          $ref: "#/definitions/CourseStructureVo"
        description: "子课程结构"
      courseResourceList:
        type: "array"
        items:
          $ref: "#/definitions/CourseResourceVo"
        description: "资源集合"

  CourseResourceVo:
    type: "object"
    properties:
      resourceId:
        type: "string"
        description: "资源id"
      resourceName:
        type: "string"
        description: "资源名称"
      resourceType:
        type: "integer"
        description: "资源类型(0-课件 1-视频 2-测验)"
      resourceSize:
        type: "string"
        description: "资源大小"
      modifyTime:
        type: "string"
        description: "更新时间"
      modifierName:
        type: "string"
        description: "更新人名称"
      modifierId:
        type: "string"
        description: "更新人id"
      innerIp:
        type: "string"
        description: "内网ip"
      outerIp:
        type: "string"
        description: "外网ip"
      filePath:
        type: "string"
        description: "文件路径"
      fileType:
        type: "string"
        description: "文件类型"
      isPublic:
        type: "integer"
        description: "是否公开 0 不公开 1公开"
      questionNum:
        type: "integer"
        description: "题目数量"
      resourceDetailId:
        type: "string"
        description: "资源详情id"
      fileSavedName:
        type: "string"
        description: "资源名称(上传名称)"
      fileSize:
        type: "string"
        description: "资源大小(上传)"
      resourceReferences:
        type: "integer"
        description: "资源引用次数(个人引用次数)"
      resourceOtherReferences:
        type: "integer"
        description: "资源引用次数(他人引用次数)"
      resourceNum:
        type: "integer"
        description: "资源内容数量"
      courseId:
        type: "string"
        description: "课程id"
      creatorId:
        type: "string"
        description: "创建人id"
      sourceType:
        type: "integer"
        description: "资源来源类型"
      transcodeStatus:
        type: "string"
        description: "转码状态：0:不转码;1:转码中;2:转码成功;3:转码失败"
      knowledgePointList:
        type: array
        items:
          $ref: "#/definitions/KnowledgePointResource"
        description: "知识点集合"
      aiIdentifyStatus:
        type: "integer"
        description: "AI识别状态（0:未识别,1:识别中,2:识别成功,3:识别失败)"
  KnowledgePointResource:
    type: object
    properties:
      pointId:
        type: string
        description: "知识点id"
      pointName:
        type: string
        description: "知识点名称"
