swagger: "2.0"
info:
  title: 课程版本信息相关接口接口文档
  version: "1.0"
host: 192.168.1.34:8080
basePath: /v1
schemes:
  - https
  - http
paths:
  /coursechaptergoal/type:
    get:
      tags:
        - "CourseChapterGoal"
      summary: "获取章节目标分类"
      description: "1.云课堂教师端-课程建设使用"
      parameters:
        - name: validCode
          type: string
          description: "验证码（&signKey=123123）"
          in: query
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/CourseChapterGoalTypeResource"
        400:
          description: "参数不正确"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证码错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        404:
          description: "未找到资源信息"
          schema:
            $ref: "#/definitions/ErrorResult"
        409:
          description: "业务校验数据错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

  /coursechaptergoal:
    get:
      tags:
        - "CourseChapterGoal"
      summary: "获取章节目标"
      description: "1.云课堂教师端-课程建设使用"
      operationId: getCourseChapterGoal
      parameters:
        - name: validCode
          type: string
          description: "验证码（&signKey=123123）"
          in: query
          required: true
        - name: structureId
          type: string
          description: "章节id"
          in: query
          required: false
        - name: courseId
          type: string
          description: "课程id"
          in: query
          required: false
        - name: versionId
          type: string
          description: "版本id"
          in: query
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/CourseStructureBaseResource"
        400:
          description: "参数不正确"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证码错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        404:
          description: "未找到资源信息"
          schema:
            $ref: "#/definitions/ErrorResult"
        409:
          description: "业务校验数据错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

    post:
      tags:
        - "CourseChapterGoal"
      summary: "新增课程章节目标"
      description: "1.云课堂教师端-课程建设使用"
      operationId: addCourseChapterGoal
      parameters:
        - name: validCode
          type: string
          description: "验证码（&signKey=123123）"
          in: query
          required: true
        - name: "courseChapterGoalVo"
          description: "课程章节目标信息"
          in: body
          required: true
          schema:
            $ref: "#/definitions/CourseChapterGoalVo"
      responses:
        '200':
          description: OK
        400:
          description: "参数不正确"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证码错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        404:
          description: "未找到资源信息"
          schema:
            $ref: "#/definitions/ErrorResult"
        409:
          description: "业务校验数据错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

definitions:

  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"

  CourseChapterGoalTypeResource:
    type: object
    properties:
      typeName:
        type: string
        description: "类型名称"
      typeValue:
        type: integer
        description: "类型值"
      parentName:
        type: string
        description: "父级类型名称"
      isShow:
        type: boolean
        description: "是否展示"
      showOrder:
        type: integer
        description: "排序字段"

  CourseStructureBaseResource:
    type: object
    properties:
      structureId:
        type: string
        description: "章节id"
      structureName:
        type: string
        description: "章节名称"
      structureShowOrder:
        type: integer
        description: "章节排序信息"
      goalList:
        type: array
        description: "章节目标列表"
        items:
          $ref: "#/definitions/CourseChapterGoalResource"

  CourseChapterGoalResource:
    type: object
    properties:
      typeName:
        type: string
        description: "类型名称"
      typeValue:
        type: integer
        description: "类型值"
      parentName:
        type: string
        description: "父级类型名称"
      isShow:
        type: boolean
        description: "是否展示"
      showOrder:
        type: integer
        description: "排序字段"
      content:
        type: string
        description: "目标内容"

  CourseChapterGoalVo:
    type: object
    properties:
      courseId:
        type: string
        description: "课程id"
      versionId:
        type: string
        description: "版本id"
      structureId:
        type: string
        description: "章节id"
      userId:
        type: string
        description: "用户id"
      userName:
        type: string
        description: "用户姓名"
      goalList:
        type: array
        description: "目标列表"
        items:
          $ref: "#/definitions/CourseChapterGoalResource"