/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseinfo;


import com.lztech.site.resource.course.CourseInfo;
import com.lztech.site.viewmodel.course.CourseCoverVo;
import com.lztech.site.viewmodel.course.CourseData;
import com.lztech.site.viewmodel.course.CourseImageInfoQueryParam;
import com.lztech.site.viewmodel.course.CourseImageInfoVo;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-07T09:16:12.156Z")

@Api(value = "courses", description = "the courses API")
@RequestMapping(value = "/v1")
public interface CoursesApi {

    @ApiOperation(value = "保存课程", nickname = "coursesPost", notes = "数据对接使用", tags = {"CourseResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courses",
            method = RequestMethod.POST)
    ResponseEntity<Void> coursesPost(@NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
                                     @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                     @ApiParam(value = "课程列表", required = true) @Valid @RequestBody List<CourseInfo> courses);


    @ApiOperation(value = "删除课程接口", nickname = "deleteCourse",
            notes = "1.云课堂老师端-课程管理删除课程；2.云课堂管理端-删除课程", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/course/{id}/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourse(@NotNull @ApiParam(value = "验证码：id=?&signKey=123123(md5加密)", required = true)
                                      @Valid @RequestParam(value = "validCode", required = true)
                                              String validCode,
                                      @ApiParam(value = "课程id", required = true) @PathVariable("id")
                                              String id);


    @ApiOperation(value = "修改课程名称接口", nickname = "updateCourseName",
            notes = "1.云课堂老师端-课程建设修改课程名称", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/course/{id}/coursename",
            method = RequestMethod.POST)
    ResponseEntity<Void> updateCourseName(@NotNull @ApiParam(value = "验证码：id=?&signKey=123123(md5加密)", required = true)
                                          @Valid @RequestParam(value = "validCode", required = true)
                                                  String validCode,
                                          @ApiParam(value = "课程id", required = true) @PathVariable("id")
                                                  String id,
                                          @NotNull @ApiParam(value = "新课程名称", required = true)
                                          @Valid @RequestParam(value = "newCourseName", required = true)
                                                  String newCourseName);

    @ApiOperation(value = "获取所有课程信息", nickname = "getAllCourseList", notes = "期末评教获取所有课程信息", response = CourseData.class,
            responseContainer = "List", tags = {"courses",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseData.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/course/allcourse",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseData>> getAllCourseList(@NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                                      @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "上传课程封面", nickname = "addOrUpdateCourseCover", notes = "云课堂老师端调用", tags={ "Course", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课程信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/coursecover/upload",
            produces = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<Void> addOrUpdateCourseCover(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "封面信息"  )  @Valid @RequestBody CourseCoverVo courseCoverVo);

    @ApiOperation(value = "根据课程id(多个,拼接)获取课程图片信息列表", nickname = "getCourseImageInfos", notes = "1、云课堂听查课",
            response = CourseImageInfoVo.class, responseContainer = "List",tags={ "courses", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功",response = CourseImageInfoVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课程信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/course/courseimageinfos",
            produces = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<List<CourseImageInfoVo>> getCourseImageInfos(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询参数"  )  @Valid @RequestBody CourseImageInfoQueryParam courseImageInfoQueryParam);
}
