/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.buildings;

import com.lztech.site.viewmodel.buildings.Buildings;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-08T07:23:58.366Z")

@Api(value = "builds", description = "the builds API")
@RequestMapping(value = "/v1")
public interface BuildsApi {

    @ApiOperation(value = "获取楼栋信息", nickname = "buildsGet", notes = "获取楼栋信息,云课堂管理端获取节次信息时使用",
            response = Buildings.class, responseContainer = "List", tags={ "buildings", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "操作成功", response = Buildings.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "参数不正确"),
        @ApiResponse(code = 403, message = "验证码错误"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/builds",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Buildings>> buildsGet(@ApiParam(value = "验证码&signKey=123123(md5加密)")
                                              @Valid @RequestParam(value = "validCode", required = false)
                                                      String validCode);

}
