/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.39).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.expertinformation;

import com.lztech.site.viewmodel.coursetabledetail.LiveCourseParam;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.expertinformation.ExpertListenCurriculumPageVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2024-04-15T08:04:04.064Z")

@Validated
@Api(value = "v1", description = "the v1 API")
@RequestMapping(value = "/v1")
public interface ExpertInformationApi {

    @ApiOperation(value = "获取专家听课课表授权列表", nickname = "getExpertListenCurriculumPage",
            notes = "1.云课堂听查课端-专家听课-获取专家听课课表授权列表使用", response = ExpertListenCurriculumPageVo.class, tags = {"ExpertInformation",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExpertListenCurriculumPageVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/expertlisten/curriculum/page",
            method = RequestMethod.POST)
    ResponseEntity<ExpertListenCurriculumPageVo> getExpertListenCurriculumPage(@NotNull
                                                                               @ApiParam(value = "验证码：&signKey=123123(md5加密)", required =
                                                                                       true)
                                                                               @Valid @RequestParam(value = "validCode", required = true)
                                                                               String validCode,
                                                                               @ApiParam(value = "获取正在直播课程信息入参", required = true)
                                                                               @Valid @RequestBody
                                                                               LiveCourseParam liveCourseParam);

}
