/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.30).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teacherpreparelessons;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.teacherpreparelessons.CopiedCourseResourceVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2023-03-02T06:18:18.885Z")

@Validated
@Api(value = "teacherPrepareLessons", description = "the teacherPrepareLessons API")
@RequestMapping(value = "/v1")
public interface TeacherPrepareLessonsApi {

    @ApiOperation(value = "教师备课教学资源引用", nickname = "copyTeacherCourseResource", notes = "1.云课堂教师端-教师备课使用",
            tags = {"TeacherPrepareLessons",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验错误信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teacherPrepareLessons/courseResource/copied",
            method = RequestMethod.POST)
    ResponseEntity<Void> copyTeacherCourseResource(@NotNull @ApiParam(value = "验证码&signKey=123123(md5加密)", required = true)
                                                   @Valid @RequestParam(value = "validCode", required = true)
                                                           String validCode,
                                                   @ApiParam(value = "复制的教学资源信息", required = true) @Valid
                                                   @RequestBody CopiedCourseResourceVo copiedCourseResourceVo);

}
