/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.collegeresources;

import com.lztech.site.resource.collegeresources.CollegeResources;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-08T09:26:24.794Z")

@Api(value = "CollegeResources", description = "the CollegeResources API")
@RequestMapping(value = "/v1")
public interface CollegeResourcesApi {

    @ApiOperation(value = "学院列表信息", nickname = "collegeResourcesGet", notes = "", response = CollegeResources.class,
            responseContainer = "List", tags={ "collegeResources", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeResources.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密错误"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/collegeResources",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<CollegeResources>> collegeResourcesGet(
            @ApiParam(value = "学院名称")
            @RequestParam(value = "collegeName",required = false) String collegeName,
            @ApiParam(value = "是否是开课学院")
            @RequestParam(value = "courseInfoCollege",required = false) Integer courseInfoCollege,


            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);



}
