/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.preparation;

import com.lztech.site.viewmodel.preparation.PreparationResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-25T03:07:00.312Z")

@Api(value = "preparation", description = "the preparation API")
@RequestMapping(value = "/v1")
public interface PreparationApi {

    @ApiOperation(value = "老师我的课程信息", nickname = "preparationTeacherIdGet", notes = "云课堂调用",
            response = PreparationResource.class, responseContainer = "List", tags = {"Preparation",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = PreparationResource.class,
                    responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密错误"),
            @ApiResponse(code = 404, message = "未找到老师我的课程信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/preparation",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<PreparationResource>> preparationGet(
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
