/*
 * 课程管理接口文档API
 * 课程管理接口文档
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lztech.site.viewmodel.coursemanagement;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AiIntelligentCourseVo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-05-22T02:14:01.259Z")
public class AiIntelligentCourseVo {
    @JsonProperty("courseId")
    private String courseId = null;

    @JsonProperty("courseCode")
    private String courseCode = null;

    @JsonProperty("courseName")
    private String courseName = null;

    @JsonProperty("courseSource")
    private Integer courseSource = null;

    @JsonProperty("courseCollegeId")
    private String courseCollegeId = null;

    @JsonProperty("courseCollegeCode")
    private String courseCollegeCode = null;

    @JsonProperty("courseCollege")
    private String courseCollege = null;

    @JsonProperty("courseTeachingTeamId")
    private String courseTeachingTeamId = null;

    @JsonProperty("teacherType")
    private Integer teacherType = null;

    @JsonProperty("completeRate")
    private String completeRate = null;

    @JsonProperty("existCourseClass")
    private Boolean existCourseClass = null;

    @JsonProperty("coverInnerIp")
    private String coverInnerIp = null;

    @JsonProperty("coverOuterIp")
    private String coverOuterIp = null;

    @JsonProperty("coverFilepath")
    private String coverFilepath = null;

    @JsonProperty("studentType")
    private Integer studentType = null;

    @JsonProperty("courseCategoryId")
    private String courseCategoryId = null;

    @JsonProperty("courseCategory")
    private String courseCategory = null;

    @JsonProperty("teacherId")
    private String teacherId = null;

    @JsonProperty("teacherName")
    private String teacherName = null;

    @JsonProperty("schoolYear")
    private String schoolYear = null;

    @JsonProperty("term")
    private Integer term = null;

    @JsonProperty("teachingClassCount")
    private Integer teachingClassCount = null;

    @JsonProperty("teachingClassStudentCount")
    private Integer teachingClassStudentCount = null;

    @JsonProperty("totalClassHour")
    private Integer totalClassHour = null;

    @JsonProperty("completeClassHour")
    private Integer completeClassHour = null;

    @JsonProperty("openClassNum")
    private Integer openClassNum = null;

    @JsonProperty("runTermNum")
    private Integer runTermNum = null;

    @JsonProperty("serviceStudentNum")
    private Integer serviceStudentNum = null;

    @JsonProperty("isCurrentTerm")
    private Boolean isCurrentTerm = null;

    public AiIntelligentCourseVo courseId(String courseId) {
        this.courseId = courseId;
        return this;
    }

    /**
     * 课程id
     *
     * @return courseId
     **/
    @ApiModelProperty(value = "课程id")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    public AiIntelligentCourseVo courseCode(String courseCode) {
        this.courseCode = courseCode;
        return this;
    }

    /**
     * 课程编号
     *
     * @return courseCode
     **/
    @ApiModelProperty(value = "课程编号")
    public String getCourseCode() {
        return courseCode;
    }

    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }

    public AiIntelligentCourseVo courseName(String courseName) {
        this.courseName = courseName;
        return this;
    }

    /**
     * 课程名称
     *
     * @return courseName
     **/
    @ApiModelProperty(value = "课程名称")
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public AiIntelligentCourseVo courseSource(Integer courseSource) {
        this.courseSource = courseSource;
        return this;
    }

    /**
     * 课程来源 0：对接；1：新增
     *
     * @return courseSource
     **/
    @ApiModelProperty(value = "课程来源 0：对接；1：新增")
    public Integer getCourseSource() {
        return courseSource;
    }

    public void setCourseSource(Integer courseSource) {
        this.courseSource = courseSource;
    }

    public AiIntelligentCourseVo courseCollegeId(String courseCollegeId) {
        this.courseCollegeId = courseCollegeId;
        return this;
    }

    /**
     * 课程学院id
     *
     * @return courseCollegeId
     **/
    @ApiModelProperty(value = "课程学院id")
    public String getCourseCollegeId() {
        return courseCollegeId;
    }

    public void setCourseCollegeId(String courseCollegeId) {
        this.courseCollegeId = courseCollegeId;
    }

    public AiIntelligentCourseVo courseCollegeCode(String courseCollegeCode) {
        this.courseCollegeCode = courseCollegeCode;
        return this;
    }

    /**
     * 课程学院编号
     *
     * @return courseCollegeCode
     **/
    @ApiModelProperty(value = "课程学院编号")
    public String getCourseCollegeCode() {
        return courseCollegeCode;
    }

    public void setCourseCollegeCode(String courseCollegeCode) {
        this.courseCollegeCode = courseCollegeCode;
    }

    public AiIntelligentCourseVo courseCollege(String courseCollege) {
        this.courseCollege = courseCollege;
        return this;
    }

    /**
     * 课程学院名称
     *
     * @return courseCollege
     **/
    @ApiModelProperty(value = "课程学院名称")
    public String getCourseCollege() {
        return courseCollege;
    }

    public void setCourseCollege(String courseCollege) {
        this.courseCollege = courseCollege;
    }

    public AiIntelligentCourseVo courseTeachingTeamId(String courseTeachingTeamId) {
        this.courseTeachingTeamId = courseTeachingTeamId;
        return this;
    }

    /**
     * 课程教学团队Id
     *
     * @return courseTeachingTeamId
     **/
    @ApiModelProperty(value = "课程教学团队Id")
    public String getCourseTeachingTeamId() {
        return courseTeachingTeamId;
    }

    public void setCourseTeachingTeamId(String courseTeachingTeamId) {
        this.courseTeachingTeamId = courseTeachingTeamId;
    }

    public AiIntelligentCourseVo teacherType(Integer teacherType) {
        this.teacherType = teacherType;
        return this;
    }

    /**
     * 老师类型：0 团队老师；1 课程负责人
     *
     * @return teacherType
     **/
    @ApiModelProperty(value = "老师类型：0 团队老师；1 课程负责人")
    public Integer getTeacherType() {
        return teacherType;
    }

    public void setTeacherType(Integer teacherType) {
        this.teacherType = teacherType;
    }

    public AiIntelligentCourseVo completeRate(String completeRate) {
        this.completeRate = completeRate;
        return this;
    }

    /**
     * 资料完成度
     *
     * @return completeRate
     **/
    @ApiModelProperty(value = "资料完成度")
    public String getCompleteRate() {
        return completeRate;
    }

    public void setCompleteRate(String completeRate) {
        this.completeRate = completeRate;
    }

    public AiIntelligentCourseVo existCourseClass(Boolean existCourseClass) {
        this.existCourseClass = existCourseClass;
        return this;
    }

    /**
     * 是否存在课程班级（true：存在；false：不存在）
     *
     * @return existCourseClass
     **/
    @ApiModelProperty(value = "是否存在课程班级（true：存在；false：不存在）")
    public Boolean isExistCourseClass() {
        return existCourseClass;
    }

    public void setExistCourseClass(Boolean existCourseClass) {
        this.existCourseClass = existCourseClass;
    }

    public AiIntelligentCourseVo coverInnerIp(String coverInnerIp) {
        this.coverInnerIp = coverInnerIp;
        return this;
    }

    /**
     * 封面内网IP
     *
     * @return coverInnerIp
     **/
    @ApiModelProperty(value = "封面内网IP")
    public String getCoverInnerIp() {
        return coverInnerIp;
    }

    public void setCoverInnerIp(String coverInnerIp) {
        this.coverInnerIp = coverInnerIp;
    }

    public AiIntelligentCourseVo coverOuterIp(String coverOuterIp) {
        this.coverOuterIp = coverOuterIp;
        return this;
    }

    /**
     * 封面外网IP
     *
     * @return coverOuterIp
     **/
    @ApiModelProperty(value = "封面外网IP")
    public String getCoverOuterIp() {
        return coverOuterIp;
    }

    public void setCoverOuterIp(String coverOuterIp) {
        this.coverOuterIp = coverOuterIp;
    }

    public AiIntelligentCourseVo coverFilepath(String coverFilepath) {
        this.coverFilepath = coverFilepath;
        return this;
    }

    /**
     * 封面文件路径
     *
     * @return coverFilepath
     **/
    @ApiModelProperty(value = "封面文件路径")
    public String getCoverFilepath() {
        return coverFilepath;
    }

    public void setCoverFilepath(String coverFilepath) {
        this.coverFilepath = coverFilepath;
    }


    public AiIntelligentCourseVo runTermNum(Integer runTermNum) {
        this.runTermNum = runTermNum;
        return this;
    }

    /**
     * 开课学期总数
     *
     * @return runTermNum
     **/
    @ApiModelProperty(value = "开课学期总数")
    public Integer getRunTermNum() {
        return runTermNum;
    }

    public void setRunTermNum(Integer runTermNum) {
        this.runTermNum = runTermNum;
    }

    public AiIntelligentCourseVo openClassNum(Integer openClassNum) {
        this.openClassNum = openClassNum;
        return this;
    }

    /**
     * 开设班级总数
     *
     * @return openClassNum
     **/
    @ApiModelProperty(value = "开设班级总数")
    public Integer getOpenClassNum() {
        return openClassNum;
    }

    public void setOpenClassNum(Integer openClassNum) {
        this.openClassNum = openClassNum;
    }

    public AiIntelligentCourseVo serviceStudentNum(Integer serviceStudentNum) {
        this.serviceStudentNum = serviceStudentNum;
        return this;
    }

    /**
     * 服务学生总数
     *
     * @return serviceStudentNum
     **/
    @ApiModelProperty(value = "服务学生总数")
    public Integer getServiceStudentNum() {
        return serviceStudentNum;
    }

    public void setServiceStudentNum(Integer serviceStudentNum) {
        this.serviceStudentNum = serviceStudentNum;
    }

    public AiIntelligentCourseVo studentType(Integer studentType) {
        this.studentType = studentType;
        return this;
    }

    /**
     * 开课类型
     *
     * @return studentType
     **/
    @ApiModelProperty(value = "开课类型")
    public Integer getStudentType() {
        return studentType;
    }

    public void setStudentType(Integer studentType) {
        this.studentType = studentType;
    }

    public AiIntelligentCourseVo courseCategoryId(String courseCategoryId) {
        this.courseCategoryId = courseCategoryId;
        return this;
    }

    /**
     * 课程类别Id
     *
     * @return courseCategoryId
     **/
    @ApiModelProperty(value = "课程类别Id")
    public String getCourseCategoryId() {
        return courseCategoryId;
    }

    public void setCourseCategoryId(String courseCategoryId) {
        this.courseCategoryId = courseCategoryId;
    }

    public AiIntelligentCourseVo courseCategory(String courseCategory) {
        this.courseCategory = courseCategory;
        return this;
    }

    /**
     * 课程类别名称
     *
     * @return courseCategory
     **/
    @ApiModelProperty(value = "课程类别名称")
    public String getCourseCategory() {
        return courseCategory;
    }

    public void setCourseCategory(String courseCategory) {
        this.courseCategory = courseCategory;
    }

    public AiIntelligentCourseVo teacherId(String teacherId) {
        this.teacherId = teacherId;
        return this;
    }

    /**
     * 上课老师id,多个老师使用“,” 隔开
     *
     * @return teacherId
     **/
    @ApiModelProperty(value = "上课老师id,多个老师使用“,” 隔开")
    public String getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    public AiIntelligentCourseVo teacherName(String teacherName) {
        this.teacherName = teacherName;
        return this;
    }

    /**
     * 上课老师名称,多个老师使用“,” 隔开
     *
     * @return teacherName
     **/
    @ApiModelProperty(value = "上课老师名称,多个老师使用“,” 隔开")
    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public AiIntelligentCourseVo schoolYear(String schoolYear) {
        this.schoolYear = schoolYear;
        return this;
    }

    /**
     * 学年
     *
     * @return schoolYear
     **/
    @ApiModelProperty(value = "学年")
    public String getSchoolYear() {
        return schoolYear;
    }

    public void setSchoolYear(String schoolYear) {
        this.schoolYear = schoolYear;
    }

    public AiIntelligentCourseVo term(Integer term) {
        this.term = term;
        return this;
    }

    /**
     * 学期
     *
     * @return term
     **/
    @ApiModelProperty(value = "学期")
    public Integer getTerm() {
        return term;
    }

    public void setTerm(Integer term) {
        this.term = term;
    }

    public AiIntelligentCourseVo teachingClassCount(Integer teachingClassCount) {
        this.teachingClassCount = teachingClassCount;
        return this;
    }

    /**
     * 教学班个数
     *
     * @return teachingClassCount
     **/
    @ApiModelProperty(value = "教学班个数")
    public Integer getTeachingClassCount() {
        return teachingClassCount;
    }

    public void setTeachingClassCount(Integer teachingClassCount) {
        this.teachingClassCount = teachingClassCount;
    }

    public AiIntelligentCourseVo teachingClassStudentCount(Integer teachingClassStudentCount) {
        this.teachingClassStudentCount = teachingClassStudentCount;
        return this;
    }

    /**
     * 教学班学生个数
     *
     * @return teachingClassStudentCount
     **/
    @ApiModelProperty(value = "教学班学生个数")
    public Integer getTeachingClassStudentCount() {
        return teachingClassStudentCount;
    }

    public void setTeachingClassStudentCount(Integer teachingClassStudentCount) {
        this.teachingClassStudentCount = teachingClassStudentCount;
    }

    public AiIntelligentCourseVo totalClassHour(Integer totalClassHour) {
        this.totalClassHour = totalClassHour;
        return this;
    }

    /**
     * 总课时
     *
     * @return totalClassHour
     **/
    @ApiModelProperty(value = "总课时")
    public Integer getTotalClassHour() {
        return totalClassHour;
    }

    public void setTotalClassHour(Integer totalClassHour) {
        this.totalClassHour = totalClassHour;
    }

    public AiIntelligentCourseVo completeClassHour(Integer completeClassHour) {
        this.completeClassHour = completeClassHour;
        return this;
    }

    /**
     * 完成课时
     *
     * @return completeClassHour
     **/
    @ApiModelProperty(value = "完成课时")
    public Integer getCompleteClassHour() {
        return completeClassHour;
    }

    public void setCompleteClassHour(Integer completeClassHour) {
        this.completeClassHour = completeClassHour;
    }


    public AiIntelligentCourseVo isCurrentTerm(Boolean isCurrentTerm) {
        this.isCurrentTerm = isCurrentTerm;
        return this;
    }

    /**
     * 是否为当前学期
     *
     * @return isCurrentTerm
     **/
    @ApiModelProperty(value = "是否为当前学期")
    public Boolean getCurrentTerm() {
        return isCurrentTerm;
    }

    public void setCurrentTerm(Boolean currentTerm) {
        isCurrentTerm = currentTerm;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AiIntelligentCourseVo aiIntelligentCourseVo = (AiIntelligentCourseVo) o;
        return Objects.equals(this.courseId, aiIntelligentCourseVo.courseId) &&
                Objects.equals(this.courseCode, aiIntelligentCourseVo.courseCode) &&
                Objects.equals(this.courseName, aiIntelligentCourseVo.courseName) &&
                Objects.equals(this.courseSource, aiIntelligentCourseVo.courseSource) &&
                Objects.equals(this.courseCollegeId, aiIntelligentCourseVo.courseCollegeId) &&
                Objects.equals(this.courseCollegeCode, aiIntelligentCourseVo.courseCollegeCode) &&
                Objects.equals(this.courseCollege, aiIntelligentCourseVo.courseCollege) &&
                Objects.equals(this.courseTeachingTeamId, aiIntelligentCourseVo.courseTeachingTeamId) &&
                Objects.equals(this.teacherType, aiIntelligentCourseVo.teacherType) &&
                Objects.equals(this.completeRate, aiIntelligentCourseVo.completeRate) &&
                Objects.equals(this.existCourseClass, aiIntelligentCourseVo.existCourseClass) &&
                Objects.equals(this.coverInnerIp, aiIntelligentCourseVo.coverInnerIp) &&
                Objects.equals(this.coverOuterIp, aiIntelligentCourseVo.coverOuterIp) &&
                Objects.equals(this.coverFilepath, aiIntelligentCourseVo.coverFilepath) &&
                Objects.equals(this.studentType, aiIntelligentCourseVo.studentType) &&
                Objects.equals(this.courseCategoryId, aiIntelligentCourseVo.courseCategoryId) &&
                Objects.equals(this.courseCategory, aiIntelligentCourseVo.courseCategory) &&
                Objects.equals(this.teacherId, aiIntelligentCourseVo.teacherId) &&
                Objects.equals(this.teacherName, aiIntelligentCourseVo.teacherName) &&
                Objects.equals(this.schoolYear, aiIntelligentCourseVo.schoolYear) &&
                Objects.equals(this.term, aiIntelligentCourseVo.term) &&
                Objects.equals(this.teachingClassCount, aiIntelligentCourseVo.teachingClassCount) &&
                Objects.equals(this.teachingClassStudentCount, aiIntelligentCourseVo.teachingClassStudentCount) &&
                Objects.equals(this.totalClassHour, aiIntelligentCourseVo.totalClassHour) &&
                Objects.equals(this.completeClassHour, aiIntelligentCourseVo.completeClassHour) &&
                Objects.equals(this.openClassNum, aiIntelligentCourseVo.openClassNum) &&
                Objects.equals(this.runTermNum, aiIntelligentCourseVo.runTermNum) &&
                Objects.equals(this.serviceStudentNum, aiIntelligentCourseVo.serviceStudentNum) &&
                Objects.equals(this.isCurrentTerm, aiIntelligentCourseVo.isCurrentTerm);
    }

    @Override
    public int hashCode() {
        return Objects.hash(courseId, courseCode, courseName, courseSource, courseCollegeId, courseCollegeCode,
                courseCollege, courseTeachingTeamId, teacherType, completeRate, existCourseClass, coverInnerIp,
                coverOuterIp, coverFilepath, runTermNum,openClassNum, serviceStudentNum,studentType, courseCategoryId,
                courseCategory, teacherId, teacherName,
                schoolYear, term, teachingClassCount, teachingClassStudentCount, totalClassHour, completeClassHour,
                isCurrentTerm);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AiIntelligentCourseVo {\n");

        sb.append("    courseId: ").append(toIndentedString(courseId)).append("\n");
        sb.append("    courseCode: ").append(toIndentedString(courseCode)).append("\n");
        sb.append("    courseName: ").append(toIndentedString(courseName)).append("\n");
        sb.append("    courseSource: ").append(toIndentedString(courseSource)).append("\n");
        sb.append("    courseCollegeId: ").append(toIndentedString(courseCollegeId)).append("\n");
        sb.append("    courseCollegeCode: ").append(toIndentedString(courseCollegeCode)).append("\n");
        sb.append("    courseCollege: ").append(toIndentedString(courseCollege)).append("\n");
        sb.append("    courseTeachingTeamId: ").append(toIndentedString(courseTeachingTeamId)).append("\n");
        sb.append("    teacherType: ").append(toIndentedString(teacherType)).append("\n");
        sb.append("    completeRate: ").append(toIndentedString(completeRate)).append("\n");
        sb.append("    existCourseClass: ").append(toIndentedString(existCourseClass)).append("\n");
        sb.append("    coverInnerIp: ").append(toIndentedString(coverInnerIp)).append("\n");
        sb.append("    coverOuterIp: ").append(toIndentedString(coverOuterIp)).append("\n");
        sb.append("    coverFilepath: ").append(toIndentedString(coverFilepath)).append("\n");
        sb.append("    runTermNum: ").append(toIndentedString(runTermNum)).append("\n");
        sb.append("    openClassNum: ").append(toIndentedString(openClassNum)).append("\n");
        sb.append("    serveStudentNum: ").append(toIndentedString(serviceStudentNum)).append("\n");
        sb.append("    studentType: ").append(toIndentedString(studentType)).append("\n");
        sb.append("    courseCategoryId: ").append(toIndentedString(courseCategoryId)).append("\n");
        sb.append("    courseCategory: ").append(toIndentedString(courseCategory)).append("\n");
        sb.append("    teacherId: ").append(toIndentedString(teacherId)).append("\n");
        sb.append("    teacherName: ").append(toIndentedString(teacherName)).append("\n");
        sb.append("    schoolYear: ").append(toIndentedString(schoolYear)).append("\n");
        sb.append("    term: ").append(toIndentedString(term)).append("\n");
        sb.append("    teachingClassCount: ").append(toIndentedString(teachingClassCount)).append("\n");
        sb.append("    teachingClassStudentCount: ").append(toIndentedString(teachingClassStudentCount)).append("\n");
        sb.append("    totalClassHour: ").append(toIndentedString(totalClassHour)).append("\n");
        sb.append("    completeClassHour: ").append(toIndentedString(completeClassHour)).append("\n");
        sb.append("    isCurrentTerm: ").append(toIndentedString(isCurrentTerm)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

