/*
 * 课程管理接口文档API
 * 课程管理接口文档
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lztech.site.viewmodel.coursemanagement;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AiIntelligentCourseSummaryResource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-05-22T02:14:01.259Z")
public class AiIntelligentCourseSummaryResource {
  @JsonProperty("currentTermAIIntelligentCourseVoList")
  private List<AiIntelligentCourseVo> currentTermAIIntelligentCourseVoList = new ArrayList<>();

  @JsonProperty("historyTermAIIntelligentCourseVoList")
  private List<AiIntelligentCourseVo> historyTermAIIntelligentCourseVoList = new ArrayList<>();

  public AiIntelligentCourseSummaryResource currentTermAIIntelligentCourseVoList(
          List<AiIntelligentCourseVo> currentTermAIIntelligentCourseVoList) {
    this.currentTermAIIntelligentCourseVoList = currentTermAIIntelligentCourseVoList;
    return this;
  }

  public AiIntelligentCourseSummaryResource addCurrentTermAIIntelligentCourseVoListItem(
          AiIntelligentCourseVo currentTermAIIntelligentCourseVoListItem) {
    if (this.currentTermAIIntelligentCourseVoList == null) {
      this.currentTermAIIntelligentCourseVoList = new ArrayList<AiIntelligentCourseVo>();
    }
    this.currentTermAIIntelligentCourseVoList.add(currentTermAIIntelligentCourseVoListItem);
    return this;
  }

   /**
   * 当前学期AI智能课程列表
   * @return currentTermAIIntelligentCourseVoList
  **/
  @ApiModelProperty(value = "当前学期AI智能课程列表")
  public List<AiIntelligentCourseVo> getCurrentTermAIIntelligentCourseVoList() {
    return currentTermAIIntelligentCourseVoList;
  }

  public void setCurrentTermAIIntelligentCourseVoList(List<AiIntelligentCourseVo> currentTermAIIntelligentCourseVoList) {
    this.currentTermAIIntelligentCourseVoList = currentTermAIIntelligentCourseVoList;
  }

  public AiIntelligentCourseSummaryResource historyTermAIIntelligentCourseVoList(
          List<AiIntelligentCourseVo> historyTermAIIntelligentCourseVoList) {
    this.historyTermAIIntelligentCourseVoList = historyTermAIIntelligentCourseVoList;
    return this;
  }

  public AiIntelligentCourseSummaryResource addHistoryTermAIIntelligentCourseVoListItem(
          AiIntelligentCourseVo historyTermAIIntelligentCourseVoListItem) {
    if (this.historyTermAIIntelligentCourseVoList == null) {
      this.historyTermAIIntelligentCourseVoList = new ArrayList<AiIntelligentCourseVo>();
    }
    this.historyTermAIIntelligentCourseVoList.add(historyTermAIIntelligentCourseVoListItem);
    return this;
  }

   /**
   * 往期AI智能课程列表
   * @return historyTermAIIntelligentCourseVoList
  **/
  @ApiModelProperty(value = "往期AI智能课程列表")
  public List<AiIntelligentCourseVo> getHistoryTermAIIntelligentCourseVoList() {
    return historyTermAIIntelligentCourseVoList;
  }

  public void setHistoryTermAIIntelligentCourseVoList(
          List<AiIntelligentCourseVo> historyTermAIIntelligentCourseVoList) {
    this.historyTermAIIntelligentCourseVoList = historyTermAIIntelligentCourseVoList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiIntelligentCourseSummaryResource aiIntelligentCourseSummaryResource = (AiIntelligentCourseSummaryResource) o;
    return Objects.equals(this.currentTermAIIntelligentCourseVoList, aiIntelligentCourseSummaryResource.currentTermAIIntelligentCourseVoList) &&
        Objects.equals(this.historyTermAIIntelligentCourseVoList, aiIntelligentCourseSummaryResource.historyTermAIIntelligentCourseVoList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentTermAIIntelligentCourseVoList, historyTermAIIntelligentCourseVoList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiIntelligentCourseSummaryResource {\n");
    
    sb.append("    currentTermAIIntelligentCourseVoList: ").append(toIndentedString(currentTermAIIntelligentCourseVoList)).append("\n");
    sb.append("    historyTermAIIntelligentCourseVoList: ").append(toIndentedString(historyTermAIIntelligentCourseVoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

