/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.projectsuite;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.projectsuite.*;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-21T05:33:12.625Z")

@Api(value = "projectSuite", description = "the projectSuite API")
@RequestMapping(value = "/v1")
public interface ProjectSuiteApi {

    @ApiOperation(value = "添加或修改项目套件及其相关物品", nickname = "projectSuiteUpdatePost", notes = "云课堂管理端项目卡管理使用", tags = {"projectSuite",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = ErrorResult.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/projectSuite",
            method = RequestMethod.POST)
    ResponseEntity<Void>
    projectSuitePost(@NotNull @ApiParam(value = "MD5加密验证字符串", required = true)
                                    @Valid @RequestParam(value = "validCode", required = true) String validCode,
                     @ApiParam(value = "项目卡套件", required = true)
                                    @Valid @RequestBody ProjectSuiteVo projectSuiteVo);

    @ApiOperation(value = "根据套件类型、套件名称获取套件列表", nickname = "projectSuiteProjectSuitesGet",
            notes = "云课堂管理端项目卡管理使用", response = ProjectSuitePageVo.class, tags={ "projectSuite", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = ProjectSuitePageVo.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/projectSuite",
            method = RequestMethod.GET)
    ResponseEntity<ProjectSuitePageVo> projectSuiteGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "当前页", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true)
            @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize,
            @ApiParam(value = "套件名称") @Valid @RequestParam(value = "projectSuiteName", required = false) String projectSuiteName,
            @ApiParam(value = "套件名称:0 设备仪器、1 低值易耗 ")
            @Valid @RequestParam(value = "projectSuiteType", required = false) String projectSuiteType);

    @ApiOperation(value = "根据套件id获取套件及相关物品信息", nickname = "projectSuiteProjectSuiteIdGet",
            notes = "云课堂管理端项目卡管理使用", response = ProjectSuiteInfo.class, tags = {"projectSuite",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = ProjectSuiteInfo.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到套件信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/projectSuite/{projectSuiteId}",
            method = RequestMethod.GET)
    ResponseEntity<ProjectSuiteInfo> projectSuiteProjectSuiteIdGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串projectSuiteId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "套件id", required = true) @PathVariable("projectSuiteId") String projectSuiteId);

    @ApiOperation(value = "根据套件id删除对应的项目卡套件（假删）", nickname = "projectSuiteDelete",
            notes = "云课堂管理端项目卡管理使用", tags={ "projectSuite", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到套件信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/projectSuite/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> projectSuiteDelete(
            @NotNull @ApiParam(value = "MD5加密验证字符串projectSuiteIds=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "套件id(逗号分割)", required = true)
            @Valid @RequestParam(value = "projectSuiteIds", required = true) String projectSuiteIds);

    @ApiOperation(value = "根据套件id和数量列表获取套件中易耗品信息", nickname = "projectSuiteLowValueArticlesPost",
            notes = "云课堂管理端项目卡管理使用", response = ArticlesModel.class, responseContainer = "List", tags={ "projectSuite", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = ArticlesModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到套件信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/projectSuite/lowValueArticles",
            method = RequestMethod.POST)
    ResponseEntity<List<ArticlesModel>> projectSuiteLowValueArticlesPost(
            @NotNull @ApiParam(value = "MD5加密验证字符串&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "" ,required=true ) @Valid @RequestBody List<ProjectSuiteResourceVo> projectSuiteResourceVos);


}
