/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.39).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseknowledgegraph;


import com.lztech.site.viewmodel.courseknowledgegraph.*;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.questionknowledgepointvo.QuestionKnowledgePointVo;
import com.lztech.site.viewmodel.questionlibrary.QuestionLibraryResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2024-01-24T07:25:45.794Z")

@Validated
@Api(value = "courseknowledgegraph", description = "the courseknowledgegraph API")
@RequestMapping(value = "/v1")
public interface CourseKnowledgeGraphApi {
    @ApiOperation(value = "接口-根据课程id获取该课程对应知识节点树形结构", nickname = "getCourseKnowledgeGraphTree", notes = "调用方：1、老师端",
            response = CourseKnowledgeGraphNodeTreeModel.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeTreeModel.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}",
            method = RequestMethod.GET)
    ResponseEntity<CourseKnowledgeGraphNodeTreeModel> getCourseKnowledgeGraphTree(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "验证码：courseId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-新增知识图谱知识节点", nickname = "createCourseKnowledgeGraphNode", notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph",
            method = RequestMethod.POST)
    ResponseEntity<Void> createCourseKnowledgeGraphNode(
            @ApiParam(value = "新增知识图谱节点参数", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeData courseKnowledgeGraphNodeData,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id和课程知识图谱知识节点id删除对应知识节点、子节点以及对应关系",
            nickname = "deleteCourseKnowledgeGraphNode", notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/{courseKnowledgeGraphNodeId}",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourseKnowledgeGraphNode(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @ApiParam(value = "课程知识图谱知识点id", required = true)
            @PathVariable("courseKnowledgeGraphNodeId") String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id和节点id获取知识节点详情信息", nickname = "getCourseKnowledgeGraphNodeInfo",
            notes = "调用方：1、老师端", response = CourseKnowledgeGraphNodeModel.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeModel.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodeinfo",
            method = RequestMethod.GET)
    ResponseEntity<CourseKnowledgeGraphNodeModel> getCourseKnowledgeGraphNodeInfo(
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "课程知识图谱知识点id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphNodeId", required = true) String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id和节点id修改知识节点对应基本信息", nickname = "updateCourseKnowledgeGraphNode",
            notes = "调用方：1、老师端", response = CourseKnowledgeGraphNodeModel.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeModel.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/node",
            method = RequestMethod.POST)
    ResponseEntity<CourseKnowledgeGraphNodeModel> updateCourseKnowledgeGraphNode(
            @ApiParam(value = "新增知识图谱节点参数", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeParam courseKnowledgeGraphNodeParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id和节点id获取知识节点相关关系列表", nickname = "getCourseKnowledgeGraphNodeRelationshipList",
            notes = "调用方：1、老师端", response = CourseKnowledgeGraphNodeRelationshipResource.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeRelationshipResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/noderelationships",
            method = RequestMethod.GET)
    ResponseEntity<CourseKnowledgeGraphNodeRelationshipResource> getCourseKnowledgeGraphNodeRelationshipList(
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "课程知识图谱知识点id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphNodeId", required = true) String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据关系id删除对应关系", nickname = "deleteCourseKnowledgeGraphNodeRelationship",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/noderelationship/{courseKnowledgeGraphNodeId}/{relationshipId}",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourseKnowledgeGraphNodeRelationship(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @ApiParam(value = "课程知识点id", required = true) @PathVariable("courseKnowledgeGraphNodeId") String courseKnowledgeGraphNodeId,
            @ApiParam(value = "关系id", required = true) @PathVariable("relationshipId") String relationshipId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "验证码：relationshipId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据相关信息创建对应节点关系", nickname = "createCourseKnowledgeGraphNodeRelationship",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/noderelationship",
            method = RequestMethod.POST)
    ResponseEntity<Void> createCourseKnowledgeGraphNodeRelationship(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @ApiParam(value = "新增知识图谱节点关系参数", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeRelationshipParam courseKnowledgeGraphNodeRelationshipParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id和节点id获取学习材料列表", nickname = "getCourseKnowledgeGraphNodeFileList",
            notes = "调用方：1、老师端", response = CourseKnowledgeGraphNodeFileModel.class, responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeFileModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodefiles",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseKnowledgeGraphNodeFileModel>> getCourseKnowledgeGraphNodeFileList(
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "课程知识图谱知识点id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphNodeId", required = true) String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id和节点id保存学习材料", nickname = "createCourseKnowledgeGraphNodeFileList",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodefiles",
            method = RequestMethod.POST)
    ResponseEntity<Void> createCourseKnowledgeGraphNodeFileList(
            @ApiParam(value = "新增知识图谱节点学习材料参数", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeFileParam courseKnowledgeGraphNodeFileParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据节点学习材料id删除对应学习材料", nickname = "deleteCourseKnowledgeGraphNodeFile",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodefile/{nodeFileId}",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourseKnowledgeGraphNodeFile(
            @ApiParam(value = "节点学习材料id", required = true) @PathVariable("nodeFileId") String nodeFileId,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "验证码：nodeFileId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据节点id拖动学习材料排序", nickname = "reorderCourseKnowledgeGraphNodeFile",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodefile/reorder",
            method = RequestMethod.POST)
    ResponseEntity<Void> reorderCourseKnowledgeGraphNodeResource(
            @ApiParam(value = "节点文件重新排序参数", required = true)
            @Valid @RequestBody NodeFileReorderParam nodeFileReorderParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "接口-根据课程id获取对应节点和关系列表", nickname = "getCourseKnowledgeGraphClassifyResource",
            notes = "调用方：1、老师端", response = CourseKnowledgeGraphClassifyResource.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphClassifyResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/list",
            method = RequestMethod.GET)
    ResponseEntity<CourseKnowledgeGraphClassifyResource> getCourseKnowledgeGraphClassifyResource(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-历史课程知识结构数据导入图谱", nickname = "importKnowledgeStructure",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/importolddata",
            method = RequestMethod.POST)
    ResponseEntity<Void> importKnowledgeStructure(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-知识图谱排序修改", nickname = "courseKnowledgeGraphSort",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/sort",
            method = RequestMethod.POST)
    ResponseEntity<Void> courseKnowledgeGraphSort(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @ApiParam(value = "课程知识图谱树形结构参数", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeTreeModel courseKnowledgeGraphNodeTreeModel);

    @ApiOperation(value = "接口-导入知识图谱知识节点", nickname = "importCourseKnowledgeGraphNode", notes = "调用方：1.云课堂老师理端-导入知识图谱知识节点使用",
            response = ImportCourseKnowledgeGraphNodeResource.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ImportCourseKnowledgeGraphNodeResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "自定义返回信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/import",
            produces = {"application/json"},
            consumes = {"multipart/form-data"},
            method = RequestMethod.POST)
    ResponseEntity<ImportCourseKnowledgeGraphNodeResource> importCourseKnowledgeGraphNode(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "用户ID", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "用户姓名", required = true)
            @Valid @RequestParam(value = "userName", required = true) String userName,
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @ApiParam(value = "谱知识节点信息")
            @Valid @RequestPart(value = "courseKnowledgeGraphNodeInfo", required = true) MultipartFile courseKnowledgeGraphNodeInfo);

    @ApiOperation(value = "新增/修改知识图谱公开班级", nickname = "addOrUpdateCourseKnowledgeGraphClass", notes = "1.云课堂老师端-我的课程知识图谱功能使用",
            tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraphclass",
            method = RequestMethod.POST)
    ResponseEntity<Void> addOrUpdateCourseKnowledgeGraphClass(
            @NotNull @ApiParam(value = "验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "退回信息", required = true)
            @Valid @RequestBody CourseKnowledgeGraphInfo courseKnowledgeGraphInfo);

    @ApiOperation(value = "查看知识图谱公开班级", nickname = "getCourseKnowledgeGraphClassList", notes = "1.云课堂老师端-我的课程知识图谱功能使用",
            response = ClassVo.class, responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ClassVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraphclass",
            method = RequestMethod.GET)
    ResponseEntity<List<ClassVo>> getCourseKnowledgeGraphClassList(
            @NotNull @ApiParam(value = "验证码courseId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "开课学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "开课学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term);

    @ApiOperation(value = "判断学生所在教学班是否公开知识图谱", nickname = "checkCourseKnowledgeGraphPublicStatus",
            notes = "1.云课堂学生端-我的课程知识图谱功能使用", response = Boolean.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Boolean.class),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/ispublic",
            method = RequestMethod.GET)
    ResponseEntity<Boolean> checkCourseKnowledgeGraphPublicStatus(
            @NotNull @ApiParam(value = "验证码courseId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "开课学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "开课学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "班级id，多个用“,”隔开", required = true)
            @Valid @RequestParam(value = "groupIds", required = true) String groupIds);

    @ApiOperation(value = "接口-根据课程id和节点id批量保存知识点和题目关系", nickname = "createCourseKnowledgeGraphNodeQuestionList",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodequestions",
            method = RequestMethod.POST)
    ResponseEntity<Void> createCourseKnowledgeGraphNodeQuestionList(
            @ApiParam(value = "新增知识图谱节点题目参数", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeQuestionParam courseKnowledgeGraphNodeQuestionParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "接口-根据课程id和节点id获取关联题目列表", nickname = "getCourseKnowledgeGraphNodeQuestionList",
            notes = "调用方：1、老师端", response = QuestionLibraryResource.class, responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = QuestionLibraryResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodequestions",
            method = RequestMethod.GET)
    ResponseEntity<List<QuestionLibraryResource>> getCourseKnowledgeGraphNodeQuestionList(
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "课程知识图谱知识点id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphNodeId", required = true) String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程id、知识点id和题目id删除对应知识点和题目关系", nickname = "deleteCourseKnowledgeGraphNodeQuestion",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/nodequestion/{courseKnowledgeGraphNodeId}/{questionId}",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourseKnowledgeGraphNodeQuestion(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @ApiParam(value = "课程知识点id", required = true)
            @PathVariable("courseKnowledgeGraphNodeId") String courseKnowledgeGraphNodeId,
            @ApiParam(value = "题目id", required = true) @PathVariable("questionId") String questionId,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @NotNull @ApiParam(value = "验证码：questionId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-知识点题目关系根据题目id获取知识节点基本信息列表", nickname = "getNodeBasicInfoListByQuestionId", notes = "调用方：1、老师端",
            response = CourseKnowledgeGraphNodeBasicInfo.class, responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeBasicInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodequestion/{questionId}/nodeinfos",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseKnowledgeGraphNodeBasicInfo>> getNodeBasicInfoListByQuestionId(
            @ApiParam(value = "题目id", required = true) @PathVariable("questionId") String questionId,
            @NotNull @ApiParam(value = "验证码：questionId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-知识点题目关系根据题目id列表删除对应知识点题目关系信息", nickname = "deleteNodeQuestionByQuestionIdList",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/deletenodequestions",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteNodeQuestionByQuestionIdList(
            @ApiParam(value = "题目id列表", required = true)
            @Valid @RequestBody List<String> questionIdList,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-知识点历史数据推送kafka", nickname = "historyDataPushKafka",
            notes = "调用方：1、老师端", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/historydatapushkafka",
            method = RequestMethod.POST)
    ResponseEntity<Void> historyDataPushKafka(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据条件查询知识图谱相关节点信息", nickname = "getCourseKnowledgeGraphCorrelationNodeInfoList",
            notes = "调用方：1、老师端", response = CourseKnowledgeGraphCorrelationNodeInfo.class, responseContainer = "List",
            tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphCorrelationNodeInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodeinfos",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseKnowledgeGraphCorrelationNodeInfo>> getCourseKnowledgeGraphCorrelationNodeInfoList(
            @ApiParam(value = "知识图谱节点查询条件", required = true)
            @Valid @RequestBody CourseKnowledgeGraphNodeQueryInfoParam courseKnowledgeGraphNodeQueryInfoParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "批量题库新题目复制原题目与知识点关系保存接口", nickname = "batchCopyQuestionKnowledgeGraphNodeToNewQuestion",
            notes = "调用方：1、云课堂老师端-共享题库-引用至我的题库（内部使用）", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/batchcopyquestionsnodestonewquestions",
            method = RequestMethod.POST)
    ResponseEntity<Void> batchCopyQuestionKnowledgeGraphNodeToNewQuestion(
            @ApiParam(value = "保存参数", required = true)
            @Valid @RequestBody CourseQuestionToNewQuestionKnowledgeGraphParam saveParam,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据相关信息获取智能资源列表", nickname = "getCourseKnowledgeGraphNodeVideoInfoTextList",
            notes = "调用方：1、学生端", response = CourseKnowledgeGraphNodeVideoInfoTextModel.class,
            responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeVideoInfoTextModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/nodevideoinfotexts",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseKnowledgeGraphNodeVideoInfoTextModel>> getCourseKnowledgeGraphNodeVideoInfoTextList(
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "班级id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @NotNull @ApiParam(value = "课程知识图谱知识点id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphNodeId", required = true) String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphId", required = true) String courseKnowledgeGraphId,
            @ApiParam(value = "相似性分数")
            @Valid @RequestParam(value = "similarityScore", required = false) Double similarityScore,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "接口-根据视频id和知识点id获取智能资源列表", nickname = "getFilterCourseKnowledgeGraphNodeVideoInfoTextList",
            notes = "调用方：1、学生端", response = CourseKnowledgeGraphNodeVideoInfoTextModel.class,
            responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeVideoInfoTextModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseKnowledgeGraphNodeId}/videoinfotexts",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseKnowledgeGraphNodeVideoInfoTextModel>> getFilterCourseKnowledgeGraphNodeVideoInfoTextList(
            @ApiParam(value = "课程知识图谱知识点id", required = true)
            @PathVariable("courseKnowledgeGraphNodeId") String courseKnowledgeGraphNodeId,
            @NotNull @ApiParam(value = "视频信息id", required = true)
            @Valid @RequestParam(value = "videoInfoId", required = true) String videoInfoId,
            @ApiParam(value = "相似性分数")
            @Valid @RequestParam(value = "similarityScore", required = false) Double similarityScore,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "接口-根据课程id获取该课程历史版本列表", nickname = "getCourseKnowledgeGraphTree", notes = "调用方：1、老师端",
            response = CourseKnowledgeGraphVersionModel.class, responseContainer = "List", tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphVersionModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/{courseId}/historyversions",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseKnowledgeGraphVersionModel>> getHistoryVersionCourseKnowledgeGraphList(
            @ApiParam(value = "课程id", required = true) @PathVariable("courseId") String courseId,
            @NotNull @ApiParam(value = "验证码：courseId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-根据课程知识图谱id获取历史知识图谱信息",
            nickname = "getHistoryCourseKnowledgeGraphNodeTreeModel", notes = "调用方：1、老师端",
            response = CourseKnowledgeGraphNodeTreeModel.class, tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseKnowledgeGraphNodeTreeModel.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/history",
            method = RequestMethod.GET)
    ResponseEntity<CourseKnowledgeGraphNodeTreeModel> getHistoryCourseKnowledgeGraphNodeTreeModel(
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphDomainId", required = true) String courseKnowledgeGraphDomainId,
            @NotNull @ApiParam(value = "验证码：courseKnowledgeGraphDomainId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );


    @ApiOperation(value = "接口-根据courseKnowledgeGraphDomainId恢复版本",
            nickname = "replyHistoryCourseKnowledgeGraphDomain", notes = "调用方：1、老师端" , tags = {"CourseKnowledgeGraph",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseknowledgegraph/replyversion",
            method = RequestMethod.POST)
    ResponseEntity<Void> replyHistoryCourseKnowledgeGraphDomain(
            @NotNull @ApiParam(value = "课程知识图谱id", required = true)
            @Valid @RequestParam(value = "courseKnowledgeGraphDomainId", required = true) String courseKnowledgeGraphDomainId,
            @NotNull @ApiParam(value = "访问用户id", required = true)
            @Valid @RequestParam(value = "accessUserId", required = true) String accessUserId,
            @NotNull @ApiParam(value = "访问用户名称", required = true)
            @Valid @RequestParam(value = "accessUserName", required = true) String accessUserName,
            @NotNull @ApiParam(value = "验证码：courseKnowledgeGraphDomainId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "接口-根据课程id和知识点id批量保存知识点和题目关系", nickname
            = "createCourseKnowledgeGraphNodeQuestionList", notes = "调用方：1、老师端", tags={ "CourseKnowledgeGraph", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/questionlibrary/courseknowledgegraph/contact",
            method = RequestMethod.POST)
    ResponseEntity<Void> createCourseKnowledgeGraphNodeQuestionList(
            @ApiParam(value = "新增知识点和题目参数" ,required=true )  @Valid @RequestBody
            QuestionKnowledgePointVo questionKnowledgePointVo,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


}
