/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.major;

import com.lztech.site.viewmodel.major.MajorVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-20T07:09:56.790Z")

@Api(value = "major", description = "the major API")
@RequestMapping(value = "/v1")
public interface MajorApi {

    @ApiOperation(value = "查询专业信息", nickname = "majorGet", notes = "小程序使用",
            response = MajorVo.class, responseContainer = "List", tags={ "MajorResource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = MajorVo.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "参数不正确"),
        @ApiResponse(code = 401, message = "解密验证失败"),
        @ApiResponse(code = 404, message = "未找到课表信息"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/major",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<MajorVo> majorGet(@NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
                                           @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                           @NotNull @ApiParam(value = "当前页", required = true)
                                           @Valid @RequestParam(value = "page", required = true) Integer page,
                                           @NotNull @ApiParam(value = "每页个数", required = true)
                                           @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize, @ApiParam(value = "专业名称")
                                           @Valid @RequestParam(value = "majorName", required = false) String majorName, @ApiParam(value = "学院名称")
                                           @Valid @RequestParam(value = "collageName", required = false) String collageName);

}
