/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.major;

import com.lztech.site.resource.major.MajorInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-20T08:30:00.298Z")

@Api(value = "majors", description = "the majors API")
@RequestMapping(value = "/v1")
public interface MajorsApi {

    @ApiOperation(value = "保存专业信息", nickname = "majorsPost", notes = "数据对接使用", tags={ "MajorResource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功"),
        @ApiResponse(code = 400, message = "参数不正确"),
        @ApiResponse(code = 401, message = "解密验证失败"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/majors",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> majorsPost(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                    @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                    @ApiParam(value = "专业列表" ,required=true )  @Valid @RequestBody List<MajorInfo> majors);

}
