/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.coursetabledetail;

import com.lztech.site.resource.coursetabledetail.CourseTableDetailResource;
import com.lztech.site.resource.coursetabledetail.*;
import com.lztech.site.viewmodel.CourseTableSimpleVo;
import com.lztech.site.viewmodel.coursetable.*;
import com.lztech.site.viewmodel.coursetabledetail.*;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.teachingcalendarcoursetabledetail.LabResource;
import com.lztech.site.viewmodel.teachingcalendarcoursetabledetail.TeachingCalendarCourseTableDetail;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-15T08:34:51.679Z")

@Api(value = "courseTableDetails", description = "the courseTableDetails API")
@RequestMapping(value = "/v1")
public interface CourseTableDetailsApi {

    @ApiOperation(value = "更新课表明细的课次状态", nickname = "coursetabledetailsIdCoursestatusPost",
            notes = "互动课堂使用", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表明细的课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/{id}/coursestatus",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> coursetabledetailsIdCoursestatusPost(@ApiParam(value = "课表明细id", required = true)
                                                              @PathVariable("id") String id,
                                                              @NotNull @ApiParam(value = "验证码：id=?&signKey=123123(md5加密)", required = true)
                                                              @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                              @ApiParam(value = "更新课表的课次状态信息", required = true)
                                                              @Valid @RequestBody UpdateCourseStatusInfo updateCourseStatusInfo);


    @ApiOperation(value = "通过课表明细id获取课表信息", nickname = "courseTableDetailsIdGet",
            notes = "1、互动课堂内部使用；2、督导听课提交内部使用; 3、电子班牌学生签到内部使用",
            response = CourseTableInfo.class, tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableInfo.class),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表明细的课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/{id}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CourseTableInfo> courseTableDetailsIdGet(@ApiParam(value = "课表明细id", required = true)
                                                            @PathVariable("id") String id,
                                                            @NotNull @ApiParam(value = "验证码：id=?&signKey=123123(md5加密)", required = true)
                                                            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据课表id列表获取课表时间(开始时间和结束时间)", nickname = "getCourseTableDetailTimeVoList",
            notes = "1、内部使用",
            response = CourseTableDetailTimeVo.class, responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDetailTimeVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表明细的课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/times",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDetailTimeVo>> getCourseTableDetailTimeVoList(
            @ApiParam(value = "课表列表", required = true)
            @Valid @RequestBody List<String> courseTableDetailIdList,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "保存课表明细", nickname = "coursetabledetailsPost",
            notes = "数据对接使用", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> coursetabledetailsPost(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                                @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                @ApiParam(value = "课表列表", required = true)
                                                @Valid @RequestBody List<CourseTableDetailResource> courseTableDetails);


    @ApiOperation(value = "保存教学日历课表明细", nickname = "coursetabledetailsTeachingcalendarPost",
            notes = "1.云课堂二次排课使用", response = CourseTableSimpleVo.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableSimpleVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到此自定义任务", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "校验未通过", response = ErrorResult.class, responseContainer = "List"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/teachingcalendar",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<CourseTableSimpleVo> coursetabledetailsTeachingcalendarPost(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                                                               @Valid @RequestParam(value = "validCode", required = true)
                                                                               String validCode,
                                                                               @ApiParam(value = "课表详情", required = true) @Valid
                                                                               @RequestBody TeachingCalendarCourseTableDetail courseTableDetails);

    @ApiOperation(value = "获取所有课表信息", nickname = "courseTableDetailsFindcoursetablePost", notes = "web云课堂调用",
            response = CourseTableDetailVo.class, tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDetailVo.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseTableDetails/findcoursetable",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<CourseTableDetailVo> courseTableDetailsFindcoursetablePost(
            @ApiParam(value = "课表查询条件", required = true)
            @Valid @RequestBody CourseTableDetailData courseTableDetailData,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "1.更新二次排课物品准备老师信息", nickname = "coursetabledetailsCourseTableDetailIdRoomIdItemteacherPost",
            notes = "1.二次排课分配其他时更新物品准备老师", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到此课表详情", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "校验未通过", response = ErrorResult.class, responseContainer = "List"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/{courseTableDetailId}/room/{id}/itemteacher",
            method = RequestMethod.POST)
    ResponseEntity<Void> coursetabledetailsCourseTableDetailIdRoomIdItemteacherPost(@NotNull
                                                                                    @ApiParam(value = "id={}&signKey=123123", required = true)
                                                                                    @Valid @RequestParam(value = "validCode", required = true)
                                                                                    String validCode,
                                                                                    @ApiParam(value = "课表详情id", required = true)
                                                                                    @PathVariable("courseTableDetailId")
                                                                                    String courseTableDetailId,
                                                                                    @ApiParam(value = "教室id", required = true) @PathVariable("id")
                                                                                    String id,
                                                                                    @ApiParam(value = "", required = true) @Valid @RequestBody
                                                                                    LabResource labResource);

    @ApiOperation(value = "根据房间id获取大于当前时间课表详情信息",
            nickname = "getRoomScheduleInformationList", notes = "teachingApi预约获取实验室时间段接口调用",
            response = RoomScheduleInformation.class, responseContainer = "List", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = RoomScheduleInformation.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 401, message = "解密验证失败", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/roomscheduleinformation",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<RoomScheduleInformation>> getRoomScheduleInformationList(
            @NotNull @ApiParam(value = "房间Ids（多个用“,”隔开）", required = true)
            @Valid @RequestParam(value = "roomIds", required = true) String roomIds,
            @NotNull @ApiParam(value = "加密验证码roomId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取时间范围课表详情信息", nickname = "getTimeFrameCourseTableDetailList"
            , notes = "调用方：1、teachingApi-教室预约获取占用教室信息接口调用", response = Object.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/timeframecoursetabledetails",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Object> getTimeFrameCourseTableDetailList(
            @NotNull @ApiParam(value = "开始时间（格式：yyyy-MM-dd HH:mm）", required = true)
            @Valid @RequestParam(value = "startTime", required = true) String startTime,
            @NotNull @ApiParam(value = "结束时间（格式：yyyy-MM-dd HH:mm）", required = true)
            @Valid @RequestParam(value = "endTime", required = true) String endTime,
            @NotNull @ApiParam(value = "验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据组id和老师id获取课表及相关节次信息", nickname = "getCourseTableDetailSegments",
            notes = "web云课堂调用", response = CourseTableDetailSegmentModel.class,
            responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailSegmentModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/courseTableDetails/coursetabledetailsegments",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableDetailSegmentModel>> getCourseTableDetailSegments(
            @NotNull @ApiParam(value = "组id", required = true)
            @Valid @RequestParam(value = "groupId", required = true) String groupId,
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据roomId和日期获取教室节次使用情况 ", nickname = "getCourseTableDetailRoomSegmentUsages",
            notes = "1、微信小程序", response = RoomSegmentUsageModel.class, responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = RoomSegmentUsageModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/roomsegmentusages",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<RoomSegmentUsageModel>> getCourseTableDetailRoomSegmentUsages(
            @NotNull @ApiParam(value = "教室id", required = true)
            @Valid @RequestParam(value = "roomId", required = true) String roomId,
            @NotNull @ApiParam(value = "上课日期", required = true)
            @Valid @RequestParam(value = "courseDate", required = true) String courseDate,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "根据年月获取本学期这年月教学日历列表", nickname = "getTeachingCalendarResourceList",
            notes = "1、web云课堂老师端", response = TeachingCalendarResource.class, responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingCalendarResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/coursetabledetails/monthteachingcalendarlist",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingCalendarResource>> getTeachingCalendarResourceList(
            @NotNull @ApiParam(value = "年月(yyyy-MM)", required = true)
            @Valid @RequestParam(value = "yearMonth", required = true) String yearMonth,
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据年月获取学生本学期这年月教学日历列表", nickname = "getStudentTeachingCalendarResourceList",
            notes = "1、web云课堂学生端", response = TeachingCalendarResource.class, responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingCalendarResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/coursetabledetails/studentmonthteachingcalendarlist",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingCalendarResource>> getStudentTeachingCalendarResourceList(
            @NotNull @ApiParam(value = "年月(yyyy-MM)", required = true)
            @Valid @RequestParam(value = "yearMonth", required = true) String yearMonth,
            @NotNull @ApiParam(value = "学生id", required = true)
            @Valid @RequestParam(value = "studentId", required = true) String studentId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据日期获取本学期该日期所在周课表详情", nickname = "getCourseTableWeekDetailInfo",
            notes = "1、web云课堂老师端", response = WeekCourseTableDetailPage.class, tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = WeekCourseTableDetailPage.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/coursetabledetails/weekdetailinfo",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<WeekCourseTableDetailPage> getCourseTableWeekDetailInfo(
            @NotNull @ApiParam(value = "课程日期", required = true)
            @Valid @RequestParam(value = "courseDate", required = true) String courseDate,
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取有门禁教室下指定日期课表信息", nickname = "getCourseTableDetailResourceVoList", notes = "1.根据课表生成门禁记录服务使用",
            response = CourseTableDetailResourceVo.class, responseContainer = "List", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/roomids/coursetabledetailinfo",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDetailResourceVo>> getCourseTableDetailResourceVoList(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "", required = true)
            @Valid @RequestBody ParamResource paramResource);

    @ApiOperation(value = "根据当前时间获取节次信息及课表数,如果当前时间不在上课时间,获取今天当前时间之前课表数",
            nickname = "getCurrentTimeStatistics", notes = "内部调用", response = CurrentTimeStatisticsModel.class, tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CurrentTimeStatisticsModel.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/currenttimestatistics",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<CurrentTimeStatisticsModel> getCurrentTimeStatistics(
            @NotNull @ApiParam(value = "&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询条件", required = true)
            @Valid @RequestBody CurrentTimeStatisticsParam currentTimeStatisticsParam);

    @ApiOperation(value = "根据课程表详情ID获取课程状态", nickname = "getCourseTableDetailStatusById",
            notes = "1、teachingapi调用", response = CourseTableDetailStatusResource.class, tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDetailStatusResource.class),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseTableDetail/{id}/status",
            method = RequestMethod.GET)
    ResponseEntity<CourseTableDetailStatusResource> getCourseTableDetailStatusById(
            @ApiParam(value = "课程表详情ID", required = true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "验证码：id={}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "教室Id", required = false)
            @Valid @RequestParam(value = "roomId", required = false) String roomId);

    @ApiOperation(value = "根据相关信息获取待上课的课表列表",
            nickname = "getWaitAttendClassCourseTableDetails", notes = "1.内部调用",
            response = CourseTableDetailResourceModel.class, responseContainer = "List",
            tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailResourceModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/waitattendclasscoursetabledetails",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDetailResourceModel>> getWaitAttendClassCourseTableDetails(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询条件", required = true)
            @Valid @RequestBody WaitAttendClassCourseTableDetailParam waitAttendClassCourseTableDetailParam
    );

    @ApiOperation(value = "根据课程id和用户id查询开课学年学期列表", nickname = "getCourseTableTermList",
            notes = "1、云课堂老师端", response = CourseTableTerm.class, responseContainer = "List", tags={ "CourseTableDetails", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableTerm.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/courseTableDetail/terms",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableTerm>> getCourseTableTermList(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "用户id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId
    );

    @ApiOperation(value = "根据开课id获取课表信息集合",
            nickname = "getCourseTableDetailListByCourseTableId",
            notes = "1、内部使用", response = CoursetableResourceVo.class,
            responseContainer = "List", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CoursetableResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetails/bycoursetableid",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableDetailInfoVo>> getCourseTableDetailListByCourseTableId(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "开课id", required = true)
            @Valid @RequestParam(value = "courseTableId", required = true) String courseTableId);


}
