/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.experimentalgroup;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.experimentalgroup.ExperimentalGroupCreateResource;
import com.lztech.site.viewmodel.experimentalgroup.ExperimentalGroupMemberResource;
import com.lztech.site.viewmodel.experimentalgroup.ExperimentalGroupNum;
import com.lztech.site.viewmodel.experimentalgroup.ExperimentalGroupResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-01-19T10:09:54.312Z")

@Validated
@Api(value = "group", description = "the group API")
@RequestMapping(value = "/v1")
public interface ExperimentalGroupApi {

    @ApiOperation(value = "获取班级下的实验小组信息接口", nickname = "getGroupExperimentalGroupList", notes = "1.云课堂教师端：实验小组管理使用", response =
            ExperimentalGroupResource.class, responseContainer = "List", tags = {"ExperimentalGroup",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentalGroupResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/{id}/experimentalgroup",
            method = RequestMethod.GET)
    ResponseEntity<List<ExperimentalGroupResource>> getGroupExperimentalGroupList(@NotNull
                                                                                  @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
                                                                                  @Valid @RequestParam(value = "validCode", required = true)
                                                                                          String validCode,
                                                                                  @ApiParam(value = "班级id", required = true)
                                                                                  @PathVariable("id")
                                                                                          String id);

    @ApiOperation(value = "新增或更新实验小组", nickname = "insertOrUpdateExperimentalGroup",
            notes = "1.云课堂教师端-实现小组管理使用", tags = {"ExperimentalGroup",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/experimentalgroup",
            method = RequestMethod.POST)
    ResponseEntity<Void> insertOrUpdateExperimentalGroup(@NotNull
                                                         @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                                         @Valid @RequestParam(value = "validCode", required = true)
                                                                 String validCode,
                                                         @ApiParam(value = "", required = true)
                                                         @Valid @RequestBody ExperimentalGroupCreateResource experimentalGroupCreateVo);

    @ApiOperation(value = "获取班级未分配实验小组成员接口", nickname = "getGroupUnassignedExperimentalGroupList", notes = "1.云课堂教师端-实验小组管理使用", response =
            ExperimentalGroupMemberResource.class, responseContainer = "List", tags = {"ExperimentalGroup",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentalGroupMemberResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/{id}/unassignedexperimentalgroup/member",
            method = RequestMethod.GET)
    ResponseEntity<List<ExperimentalGroupMemberResource>> getGroupUnassignedExperimentalGroupList(@NotNull
                                                                                                  @ApiParam(value = "验证码（id={}&signKey=123123）",
                                                                                                          required = true)
                                                                                                  @Valid
                                                                                                  @RequestParam(value = "validCode", required = true)
                                                                                                          String validCode,
                                                                                                  @ApiParam(value = "组id", required = true)
                                                                                                  @PathVariable("id")
                                                                                                          String id);

    @ApiOperation(value = "删除实验小组接口", nickname = "deleteExperimentalGroup",
            notes = "1.云课堂教师端-实验小组管理使用", tags = {"ExperimentalGroup",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/experimentalgroup/{id}/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteExperimentalGroup(@NotNull @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
                                                 @Valid @RequestParam(value = "validCode", required = true)
                                                         String validCode,
                                                 @ApiParam(value = "实验小组组id", required = true) @PathVariable("id")
                                                         String id,
                                                 @NotNull @ApiParam(value = "操作人id", required = true)
                                                 @Valid @RequestParam(value = "modifierId", required = true)
                                                         String modifierId,
                                                 @NotNull @ApiParam(value = "操作人姓名", required = true)
                                                 @Valid @RequestParam(value = "modifierName", required = true)
                                                         String modifierName);


    @ApiOperation(value = "获取班级实验小组详情接口", nickname = "getExperimentalGroupDetail", notes = "1.云课堂教师端-实验小组管理使用",
            response = ExperimentalGroupResource.class, tags = {"ExperimentalGroup",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentalGroupResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/experimentalgroup/{id}/detail",
            method = RequestMethod.GET)
    ResponseEntity<ExperimentalGroupResource> getExperimentalGroupDetail(@NotNull @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
                                                                         @Valid @RequestParam(value = "validCode", required = true)
                                                                                 String validCode,
                                                                         @ApiParam(value = "实验小组组id", required = true)
                                                                         @PathVariable("id")
                                                                                 String id,
                                                                         @ApiParam(value = "是否获取组员详情 默认不获取", defaultValue = "fale")
                                                                         @Valid @RequestParam(value = "isGetMemberList",
                                                                                 required = false, defaultValue = "fale")
                                                                                 Boolean isGetMemberList);


    @ApiOperation(value = "1.获取班级实验小组数量", nickname = "getGroupExperimentalGroupNum",
            notes = "1.云课堂教师端-实验小组管理使用", response = Integer.class, tags = {"ExperimentalGroup",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/group/{id}/experimentalgroupnum",
            method = RequestMethod.GET)
    ResponseEntity<ExperimentalGroupNum> getGroupExperimentalGroupNum(@NotNull @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
                                                                      @Valid @RequestParam(value = "validCode", required = true)
                                                                              String validCode,
                                                                      @ApiParam(value = "组id", required = true)
                                                                      @PathVariable("id")
                                                                              String id);

}
