/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.43).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.experimentschedule;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.experimentschedule.ExperimentScheduleCourseTableDetailExportQueryVo;
import com.lztech.site.viewmodel.experimentschedule.ExperimentScheduleCourseTableDetailPageVo;
import com.lztech.site.viewmodel.experimentschedule.ExperimentScheduleCourseTableDetailQueryVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2024-09-12T10:03:02.836Z")

@Validated
@Api(value = "experimentschedulecoursetabledetails", description = "the experimentschedulecoursetabledetails API")
@RequestMapping(value = "/api/v1")
public interface ExperimentschedulecoursetabledetailsApi {

    @ApiOperation(value = "查询实验排课信息列表接口", nickname = "getExperimentScheduleCourseTableDetails",
            notes = "使用方：1、云课堂管理端-实验教学-实验排课；2、云课堂教师端-实验排课",
            response = ExperimentScheduleCourseTableDetailPageVo.class, tags={ "ExperimentSchedule", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = ExperimentScheduleCourseTableDetailPageVo.class),
        @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
        @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/experimentschedulecoursetabledetails",
        method = RequestMethod.POST)
    ResponseEntity<ExperimentScheduleCourseTableDetailPageVo> getExperimentScheduleCourseTableDetails(
            @NotNull @ApiParam(value = "验证码&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "" ,required=true )  @Valid @RequestBody ExperimentScheduleCourseTableDetailQueryVo queryParam);

    @ApiOperation(value = "通过排课课表id删除实验排课信息接口", nickname = "deleteExperimentScheduleCourseTableDetails",
            notes = "使用方：1、云课堂管理端-实验教学-实验排课", tags={ "ExperimentSchedule", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "只有待排课状态课表才能删除", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/{id}/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteExperimentScheduleCourseTableDetails(
            @ApiParam(value = "排课id",required=true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "验证码id={}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "导出实验排课信息列表excel接口", nickname = "exportExperimentScheduleCourseTableDetailsExcel",
            notes = "使用方：1、云课堂管理端-实验教学-实验排课", tags={ "ExperimentSchedule", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "数据为空，无法导出Excel！", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/experimentschedulecoursetabledetails/excel",
            method = RequestMethod.POST)
    ResponseEntity<Void> exportExperimentScheduleCourseTableDetailsExcel(
            @NotNull @ApiParam(value = "验证码&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "" ,required=true )  @Valid @RequestBody ExperimentScheduleCourseTableDetailExportQueryVo queryParam,
            HttpServletResponse response);

}
