/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teachingstatusstatistic;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-09-17T08:37:25.285Z")

@Validated
@Api(value = "teachingstatusstatistic", description = "the teachingstatusstatistic API")
@RequestMapping(value = "/v1")
public interface TeachingstatusstatisticApi {

    @ApiOperation(
            value = "获取开课学院数量",
            nickname = "getAllCollegeNum",
            notes = "调用方：矿大门户",
            response = Integer.class,
            tags = {"teachingstatusstatistic",}
    )
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingstatusstatistic/getallcollegenum",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getAllCollegeNum(@NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
                                             @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取开课数量",
            nickname = "getAllCourseNum",
            notes = "调用方：矿大门户",
            response = Integer.class,
            tags = {"teachingstatusstatistic",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingstatusstatistic/getallcoursenum",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getAllCourseNum(
            @NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);



    @ApiOperation(value = "获取当前正在上课的学生数量",
            nickname = "getCurrentInClassStudemtNum",
            notes = "调用方：矿大门户",

            response = Integer.class, tags = {"teachingstatusstatistic",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingstatusstatistic/getcurrentinclassstudentnum",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getCurrentInClassStudentNum(
            @NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取当前正在上课的教师数量",
            nickname = "getCurrentInClassTeacherNum",
            notes = "调用方：矿大门户",
            response = Integer.class,
            tags = {"teachingstatusstatistic",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingstatusstatistic/getcurrentinclassteachernum",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getCurrentInClassTeacherNum(
            @NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取当前正在上课的教室数量",
            nickname = "getCurrentUsingClassroom",
            notes = "调用方：矿大门户",
            response = Integer.class,
            tags = {"teachingstatusstatistic",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingstatusstatistic/getcurrentusingclassroomnum",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getCurrentUsingClassroom(
            @NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
