/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseexpansion;

import com.lztech.site.viewmodel.courseexpansion.CourseExpansionCreateResource;
import com.lztech.site.viewmodel.courseexpansion.CourseExpansionQuery;
import com.lztech.site.viewmodel.courseexpansion.CourseExpansionResource;
import com.lztech.site.viewmodel.courseexpansion.CourseExpansionResourcePage;
import com.lztech.site.viewmodel.courseexpansion.CourseListeningTypeResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-12-08T06:03:14.171Z")

@Validated
@Api(value = "courseexpansion", description = "the courseexpansion API")
@RequestMapping(value = "/v1")
public interface CourseExpansionApi {

    @ApiOperation(value = "根据扩展属性的key获取课程以及扩展信息", nickname = "getCourseExpansionResource", notes = "1.云课堂管理端-获取思政课使用；2.云课堂听查课端-获取思政课使用", response =
            CourseExpansionResource.class, responseContainer = "List", tags = {"CourseExpansion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseExpansionResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseexpansion",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseExpansionResource>> getCourseExpansionResource(@NotNull
                                                                             @ApiParam(value = "验证码：expansionKey={}&signKey=123123(md5加密)",
                                                                                     required = true)
                                                                             @Valid @RequestParam(value = "validCode", required = true)
                                                                             String validCode,
                                                                             @NotNull @ApiParam(value = "扩展属性key", required = true)
                                                                             @Valid @RequestParam(value = "expansionKey", required = true)
                                                                             String expansionKey,
                                                                             @NotNull @ApiParam(value = "排序字段", required = true)
                                                                             @Valid @RequestParam(value = "sortName", required = true)
                                                                             String sortName,
                                                                             @ApiParam(value = "课程id") @Valid
                                                                             @RequestParam(value = "courseId",
                                                                                     required = false)
                                                                             String courseId);


    @ApiOperation(value = "删除课程附加属性", nickname = "deleteCourseExpansionResource", notes = "1.云课堂管理端-删除思政课课程",
            tags = {"CourseExpansion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseexpansion/{id}/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourseExpansionResource(@NotNull @ApiParam(value = "验证码：id={}&signKey=123123(md5加密)", required = true)
                                                       @Valid @RequestParam(value = "validCode", required = true)
                                                       String validCode,
                                                       @ApiParam(value = "扩展属性id", required = true)
                                                       @PathVariable("id") String id);


    @ApiOperation(value = "新增课程属性信息", nickname = "courseexpansionPost", notes = "1.云课堂管理端-新增思政课使用", tags = {"CourseExpansion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验错误信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseexpansion",
            method = RequestMethod.POST)
    ResponseEntity<Void> createCourseexpansion(@NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
                                               @Valid @RequestParam(value = "validCode", required = true)
                                               String validCode,
                                               @ApiParam(value = "添加思政课程信息", required = true)
                                               @Valid @RequestBody CourseExpansionCreateResource expansionInfo);

    @ApiOperation(value = "分页获取课程附加属性", nickname = "getCourseExpansionPage",
            notes = "1.云课堂管理端-课程听课类型维护", response = CourseExpansionResourcePage.class, tags={ "CourseExpansion", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseExpansionResourcePage.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/courseexpansion/page",
            method = RequestMethod.POST)
    ResponseEntity<CourseExpansionResourcePage> getCourseExpansionPage(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true) @Valid
            @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "分页查询参数" ,required=true )  @Valid @RequestBody
            CourseExpansionQuery courseExpansionQuery);

    @ApiOperation(value = "根据课程获取课程类型(听课类型)", nickname = "getCourseListeningType", notes = "1.云课堂管理端-课程听课类型维护回显/查询", response = CourseListeningTypeResource.class,
            tags = {"CourseExpansion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseListeningTypeResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "课程不存在", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseexpansion/coursetype",
            method = RequestMethod.GET)
    ResponseEntity<CourseListeningTypeResource> getCourseListeningType(
            @NotNull @ApiParam(value = "验证码：courseId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId
    );

    @ApiOperation(value = "Excel导入课程听课类型", nickname = "importCourseExpansion", notes = "1.云课堂管理端-课程听课类型维护导入", tags = {"CourseExpansion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验错误信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseexpansion/import",
            produces = {"application/json"},
            consumes = {"multipart/form-data"},
            method = RequestMethod.POST)
    ResponseEntity<Void> importCourseExpansion(
            @NotNull @ApiParam(value = "创建人id", required = true)
            @Valid @RequestParam(value = "creatorId", required = true) String creatorId,
            @NotNull @ApiParam(value = "创建人姓名", required = true)
            @Valid @RequestParam(value = "creatorName", required = true) String creatorName,
            @NotNull @ApiParam(value = "听课类型模式(0:固定,1:灵活)", required = true)
            @Valid @RequestParam(value = "superviseModel", required = true) Integer superviseModel,
            @ApiParam(value = "听课类型接口参数usageRange", required = false)
            @Valid @RequestParam(value = "usageRange", required = false) Integer usageRange,
            @ApiParam(value = "听课类型接口参数courseStudentTypeIds", required = false)
            @Valid @RequestParam(value = "courseStudentTypeIds", required = false) String courseStudentTypeIds,
            @ApiParam(value = "听课类型接口参数isDistinguishCourseStudentType", required = false)
            @Valid @RequestParam(value = "isDistinguishCourseStudentType", required = false) Integer isDistinguishCourseStudentType,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "导入文件（xlsx）", required = true)
            @Valid @RequestPart(value = "importFile", required = true) MultipartFile importFile
    );

}
