swagger: "2.0"
info:
  title: 学生课表查询相关接口文档
  version: "1.0"
host: 192.168.1.34:8080
basePath: /v1
schemes:
  - https
  - http
paths:

  /student/{id}/nowtime/coursetable:
    get:
      tags:
        - 'CourseTableDetail'
      summary: "查询学生有无正在上课的课表以及课程下实验项目信息"
      description: "1.teachingApi获取学生预约以及上课项目信息接口内部调用"
      operationId: getStudentNowTimeCourseTable
      parameters:
        - name: validCode
          in: query
          description: 验证码（id={}&signKey=123123）
          type: string
          required: true
        - name: id
          description: "学生id"
          type: string
          required: true
          in: path
      responses:
        200:
          description: "成功"
          schema:
            type: array
            items:
              $ref: "#/definitions/StudentCourseTableResource"
        400:
          description: "参数不正确"
          schema:
            $ref: "#/definitions/ErrorResult"
        404:
          description: "未找到正在上课的课表信息"
        403:
          description: "验证码错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"


definitions:

  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      message:
        type: "string"
        description: "错误信息"

  StudentCourseTableResource:
    properties:
      courseTableDetailId:
        type: string
        description: "课表明细id"
      segmentStartTime:
        type: string
        description: "节次开始时间"
      segmentEndTime:
        type: string
        description: "节次结束时间"
      courseId:
        type: string
        description: "课程id"
      courseName:
        type: string
        description: "课程名称"
      projectList:
        type: array
        items:
          $ref: "#/definitions/StudentCourseTableProjectResource"
  StudentCourseTableProjectResource:
    properties:
      projectId:
        type: string
        description: "项目id"
      projectCode:
        type: string
        description: "项目编号"
      projectName:
        type: string
        description: "项目名称"
      isInclass:
        type: integer
        description: "是否为上课项目 0:否；1：是"


