swagger: "2.0"
info:
  title: "courseApi文档"
  version: "1.0.0"
  description: "学院接口文档"
host: "192.168.1.34:8080"
basePath: "/courseApi/v1"
schemes:
  - "https"
  - "http"
paths:
  # v1
  "/colleges":
    post:
      tags:
        - "CollegeResource"
      summary: "保存学院"
      description: "数据对接使用"
      produces:
        - "application/json"
      parameters:
        - name: "validCode"
          in: "query"
          description: "加密验证码（&signKey=123123）"
          type: "string"
          required: true
        - name: "colleges"
          in: "body"
          required: true
          description: "学院列表"
          schema:
            type: array
            items:
              $ref: "#/definitions/CollegeResource"
      responses:
        200:
          description: "成功"
        401:
          description: "解密验证失败"
        400:
          description: "参数不正确"
        500:
          description: "服务器异常"

    get:
      tags:
        - "CollegeResource"
      summary: "根据学院ids获取学院信息列表"
      description: "1、云课堂管理端督导听课使用"
      parameters:
        - in: "query"
          name: "collegeIds"
          required: true
          type: "string"
          description: "学院ids（学院id逗号分割）"
        - in: "query"
          name: "validCode"
          required: true
          type: "string"
          description: "验证码：&signKey=123123(md5加密)"
      responses:
        200:
          description: '成功'
          schema:
            type: "array"
            items:
              $ref: '#/definitions/CollegeResource'
        400:
          description: "错误的请求"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证信息错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

  "/datadock/college":
    post:
      tags:
        - "CollegeResource"
      summary: "保存单个学院"
      description: "数据对接使用"
      produces:
        - "application/json"
      parameters:
        - name: "validCode"
          in: "query"
          description: "加密验证码（&signKey=123123）"
          type: "string"
          required: true
        - name: "college"
          in: "body"
          required: true
          description: "学院信息"
          schema:
            $ref: "#/definitions/CollegeResource"
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/CollegeResource"
        401:
          description: "解密验证失败"
        400:
          description: "参数不正确"
        500:
          description: "服务器异常"

  "/colleges/all":
    get:
      tags:
        - "CollegeResource"
      summary: "获取所有学院"
      description: "数据对接使用"
      produces:
        - "application/json"
      parameters:
        - name: "validCode"
          in: "query"
          description: "加密验证码（&signKey=123123）"
          type: "string"
          required: true
      responses:
        200:
          description: "成功"
          schema:
            type: array
            items:
              $ref: '#/definitions/CollegeResource'
        401:
          description: "解密验证失败"
        400:
          description: "参数不正确"
        500:
          description: "服务器异常"

  "/college":
    get:
      tags:
        - "CollegeResource"
      summary: "获取开课学院信息"
      description: "小程序获取开课学院信息"
      parameters:
        - in: "query"
          name: "validCode"
          required: true
          type: string
          description: "MD5加密验证字符串(&signKey=123123)"
      responses:
        200:
          description: '成功'
          schema:
            type: array
            items:
              $ref: '#/definitions/CollegeVo'
        400:
          description: "参数异常"
        403:
          description: "验证码错误"
        404:
          description: "未找到开课学院信息"
        500:
          description: "服务器异常"
  "/college/courseid":
    post:
      tags:
        - "CollegeResource"
      summary: "根据课程ID获取学院信息"
      description: "1.teachingApi题库统计接口使用"
      operationId: "findCollegeInfoByCourseIds"
      parameters:
        - in: "query"
          name: "validCode"
          required: true
          type: string
          description: "MD5加密验证字符串(&signKey=123123)"
        - name: "courseIds"
          in: "body"
          required: true
          description: "课程Id列表"
          schema:
            type: array
            items:
              $ref: "String"
      responses:
        200:
          description: '成功'
          schema:
            type: array
            items:
              $ref: '#/definitions/CollegeCourseResource'
        400:
          description: "参数异常"
        403:
          description: "验证码错误"
        500:
          description: "服务器异常"

  "/college/findAllByCourseCode":
    post:
      tags:
        - "CollegeResource"
      summary: "根据课程CODE获取学院信息"
      description: "1.学业支持统计不及格数据接口使用"
      operationId: "findAllByCourseCode"
      parameters:
        - in: "query"
          name: "validCode"
          required: true
          type: string
          description: "MD5加密验证字符串(&signKey=123123)"
        - name: "courseCodes"
          in: "body"
          required: true
          description: "课程Id列表"
          schema:
            type: array
            items:
              $ref: "String"
      responses:
        200:
          description: '成功'
          schema:
            type: array
            items:
              $ref: '#/definitions/CollegeCourseResource'
        400:
          description: "参数异常"
        403:
          description: "验证码错误"
        500:
          description: "服务器异常"

  "/colleges/{id}/courseinfocollegestatus":
    post:
      tags:
        - "CollegeResource"
      summary: "根据学院id修改学院是否是开课学院接口"
      description: "1.云课堂管理端-基础数据-基础数据-学院信息"
      operationId: "updateCollegeCourseInfoCollege"
      parameters:
        - name: "id"
          in: "path"
          type: "string"
          required: true
          description: "学院id"
        - in: "query"
          name: "validCode"
          required: true
          type: string
          description: "MD5加密验证字符串(id={}&signKey=123123)"
        - name: "courseInfoCollegeStatus"
          in: "query"
          description: "是否开课学院"
          type: "boolean"
          required: true
      responses:
        200:
          description: '成功'
        400:
          description: "参数异常"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        404:
          description: "数据不存在"
          schema:
            $ref: '#/definitions/ErrorResult'
        409:
          description: "业务错误（1、已经是开课学院更新为开课学院，1、不是开课学院更新为不是开课学院）"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"
          schema:
            $ref: '#/definitions/ErrorResult'

  "/colleges/courseinfoorallcolleges":
    post:
      tags:
        - "CollegeResource"
      summary: "根据学院ids和是否开课学院获取学院信息列表"
      description: "1、云课堂听查课端 课表巡课和课程视频"
      operationId: "getCourseInfoOrAllCollegeByIds"
      parameters:
        - in: "query"
          name: "validCode"
          type: "string"
          description: "验证码：&signKey=123123(md5加密)"
        - name: "queryParam"
          in: 'body'
          required: true
          description: "查询参数"
          schema:
            $ref: '#/definitions/CollegeIdsParam'

      responses:
        200:
          description: '成功'
          schema:
            type: "array"
            items:
              $ref: '#/definitions/CollegeResource'
        400:
          description: "错误的请求"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证信息错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"


definitions:
  CollegeResource:
    type: "object"
    properties:
      id:
        type: "string"
        description: "学院id"
      collegeName:
        type: "string"
        description: "学院名称"
      collegeCode:
        type: "string"
        description: "学院编号"
      showOrder:
        type: "integer"
        description: "显示顺序"

  CollegeVo:
    type: object
    properties:
      id:
        type: string
        description: '开课学院ID'
      name:
        type: string
        description: '开课学院名称'
      checked:
        type: boolean
        description: "是否选择"

  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"

  CollegeCourseResource:
    type: "object"
    properties:
      id:
        type: "string"
        description: "学院id"
      collegeName:
        type: "string"
        description: "学院名称"
      courseId:
        type: "string"
        description: "课程Id"
      courseName:
        type: "string"
        description: "课程名称"
      courseCode:
        type: "string"
        description: "课程编号"
      teacherId:
        type: "string"
        description: "老师ID"
      teacherName:
        type: "string"
        description: "老师名称"

  CollegeIdsParam:
    type: "object"
    properties:
      courseInfoCollegeStatus:
        type: "boolean"
        description: "是否开课学院（true：开课学院，false：所有学院）"
      ids:
        type: "string"
        description: "学院ids(逗号拼接)"


