swagger: "2.0"
info:
  description: "实验排课相关接口文档"
  version: "1.0.0"
  title: "实验排课相关接口文档"
host: "192.168.1.34:8080"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  '/experimentschedulecoursetabledetails':
    post:
      tags:
        - "ExperimentSchedule"
      summary: "查询实验排课信息列表接口"
      description: "使用方：1、云课堂管理端-实验教学-实验排课；2、云课堂教师端-实验排课"
      operationId: "getExperimentScheduleCourseTableDetails"
      parameters:
        - name: "validCode"
          in: "query"
          type: "string"
          description: "验证码&signKey=123123(md5加密)"
          required: true
        - name: "queryParam"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/ExperimentScheduleCourseTableDetailQueryVo"
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/ExperimentScheduleCourseTableDetailPageVo"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"

  '/experimentschedulecoursetabledetails/{id}/delete':
    post:
      tags:
        - "ExperimentSchedule"
      summary: "通过排课课表id删除实验排课信息接口"
      description: "使用方：1、云课堂管理端-实验教学-实验排课"
      operationId: "deleteExperimentScheduleCourseTableDetails"
      parameters:
        - name: "id"
          in: "path"
          type: "string"
          description: "排课id"
          required: true
        - name: "validCode"
          in: "query"
          type: "string"
          description: "验证码id={}&signKey=123123(md5加密)"
          required: true
      responses:
        200:
          description: "成功"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        404:
          description: "数据不存在"
          schema:
            $ref: '#/definitions/ErrorResult'
        409:
          description: "只有待排课状态课表才能删除"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"

  '/experimentschedulecoursetabledetails/excel':
    get:
      tags:
        - "ExperimentSchedule"
      summary: "导出实验排课信息列表excel接口"
      description: "使用方：1、云课堂管理端-实验教学-实验排课"
      operationId: "exportExperimentScheduleCourseTableDetailsExcel"
      parameters:
        - name: "validCode"
          in: "query"
          type: "string"
          description: "验证码&signKey=123123(md5加密)"
          required: true
        - name: "queryParam"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/ExperimentScheduleCourseTableDetailExportQueryVo"
      responses:
        200:
          description: "成功"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        409:
          description: "数据为空，无法导出Excel！"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"


  '/experimentschedulecoursetabledetails/log':
    post:
      tags:
        - "ExperimentSchedule"
      summary: "获取实验排课操作日志时间线"
      description: "使用方：1、云课堂管理端-实验教学-实验排课；2、云课堂教师端-实验排课"
      operationId: "getExperimentScheduleCourseLog"
      parameters:
        - name: "validCode"
          in: "query"
          type: "string"
          description: "验证码&signKey=123123(md5加密)"
          required: true
        - name: "experimentScheduleId"
          in: "query"
          type: "string"
          description: "实验排课待排课表id"
          required: true
      responses:
        200:
          description: "成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExperimentScheduleCourseLogVo"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"

definitions:
  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"

  ExperimentScheduleCourseLogVo:
    type: "object"
    properties:
      experimentScheduleId:
        type: "string"
        description: "实验排课待排课表id"
      operationDescription:
        type: "string"
        description: "操作描述"
      creatorName:
        type: "string"
        description: "操作人姓名"
      createTime:
        type: "string"
        description: "操作时间（yyyy-MM-dd HH:mm:ss）"


  ExperimentScheduleCourseTableDetailQueryVo:
    type: "object"
    properties:
      page:
        type: 'integer'
        description: '页码'
      pageSize:
        type: 'integer'
        description: '每页记录数'
      startDate:
        type: 'string'
        description: '开始上课日期（yyyy-MM-dd）'
      endDate:
        type: 'string'
        description: '结束上课日期（yyyy-MM-dd）'
      scheduleStatus:
        type: 'string'
        description: '排课状态：""-全部，0-待排课,1-已取消,2-已过期,3-已排课,4-教务删除'
      courseName:
        type: 'string'
        description: '课程名称'
      className:
        type: 'string'
        description: '上课班级'
      roomName:
        type: 'string'
        description: '实验室'
      classId:
        type: 'string'
        description: '上课班级Id'
      teacherId:
        type: 'string'
        description: '老师Id'
      courseId:
        type: 'string'
        description: '课程Id'
      collegeId:
        type: 'string'
        description: '学院Id'

  ExperimentScheduleCourseTableDetailPageVo:
    type: "object"
    properties:
      page:
        type: 'integer'
        description: '页码'
        example: '10'
      pageSize:
        type: 'integer'
        description: '每页记录数'
        example: '10'
      total:
        type: 'integer'
        description: '总记录数'
        example: '10'
      totalPage:
        type: 'integer'
        description: '总页数'
        example: '10'
      courseTableDetails:
        type: array
        items:
          $ref: "#/definitions/ExperimentScheduleCourseTableDetailVo"

  ExperimentScheduleCourseTableDetailVo:
    type: "object"
    properties:
      id:
        type: 'string'
        description: 'id'
      week:
        type: 'string'
        description: '周次'
      dayOfWeek:
        type: 'string'
        description: '星期几'
      courseId:
        type: 'string'
        description: '课程id'
      courseCode:
        type: 'string'
        description: '课程编码'
      courseName:
        type: 'string'
        description: '课程名称'
      projectNames:
        type: 'string'
        description: '实验项目（逗号分隔）'
      projectIds:
        type: 'string'
        description: '实验项目ids（逗号分隔）'
      classId:
        type: 'string'
        description: '上课班级Id'
      className:
        type: 'string'
        description: '上课班级'
      classStudentNumber:
        type: 'integer'
        description: '班级人数'
      teacherIds:
        type: 'string'
        description: '教师ids（逗号分隔）'
      teacherNames:
        type: 'string'
        description: '教师姓名（逗号分隔）'
      courseDate:
        type: 'string'
        description: '上课日期'
      segment:
        type: 'string'
        description: '节次'
      roomIds:
        type: 'string'
        description: '实验室ids（逗号分隔）'
      roomNames:
        type: 'string'
        description: '实验室（逗号分隔）'
      scheduleSource:
        type: 'integer'
        description: '来源值'
      scheduleSourceName:
        type: 'string'
        description: '来源名称'
      scheduleStatus:
        type: 'integer'
        description: '排课状态值'
      scheduleStatusName:
        type: 'string'
        description: '排课状态名称'
      operatorName:
        type: 'string'
        description: '操作人姓名'
      expire:
        type: 'integer'
        description: '是否过期，0-未过期，1-过期'
      modifyTime:
        type: 'string'
        description: '更新时间（yyyy-MM-dd HH:mm:ss）'
      collegeName:
        type: 'string'
        description: '开课学院'

  ExperimentScheduleCourseTableDetailExportQueryVo:
    type: "object"
    properties:
      term:
        type: 'string'
        description: '学期信息（例如：2024-2025 第一学期）'
      startDate:
        type: 'string'
        description: '开始上课日期（yyyy-MM-dd）'
      endDate:
        type: 'string'
        description: '结束上课日期（yyyy-MM-dd）'
      scheduleStatus:
        type: 'string'
        description: '排课状态：""-全部，0-待排课,1-已取消,2-已过期,3-已排课,4-教务删除'
      courseName:
        type: 'string'
        description: '课程名称'
      className:
        type: 'string'
        description: '上课班级'
      roomName:
        type: 'string'
        description: '实验室'
      teacherId:
        type: 'string'
        description: '老师Id'
      collegeId:
        type: 'string'
        description: '学院Id'