swagger: "2.0"
info:
  version: "1.0.0"
  title: "易耗品使用量统计相关接口"
host: "192.168.1.34:8080"
basePath: "/v1"
# 协议类型
schemes:
  - "https"
  - "http"
# 资源访问地址描述
paths:
  # v1
  "/lowvaluearticles":
    get:
      tags:
        - "LowValueArticles"
      summary: "根据预约项目Id获取低值易耗物品信息"
      description: "courseApi接口调用"
      produces:
        - "application/json"
      parameters:
        - name: "appointmentProjectIds"
          type: "string"
          in: "query"
          description: "项目Id,多个使用‘,’分割"
          required: true
        - name: "validCode"
          type: "string"
          in: "query"
          description: "MD5加密验证字符串 &signKey=123123"
          required: true
      responses:
        200:
          description: "成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LowValueArticlesResource"
        400:
          description: "参数不正确"
        403:
          description: "解密验证失败"
        404:
          description: "未找到视频资源文件信息"
        500:
          description: "服务器异常"

definitions:

  LowValueArticlesResource:
    type: "object"
    properties:
      lowValueArticlesId:
        type: "string"
        description: "物品id"
      lowValueArticlesNo:
        type: "string"
        description: "物品编号"
      lowValueArticlesName:
        type: "string"
        description: "物品名称"
      lowValueArticlesTypeId:
        type: "string"
        description: "物品分类id"
      lowValueArticlesTypeName:
        type: "string"
        description: "物品分类名称"
      specification:
        type: "string"
        description: "规格"
      units:
        type: "string"
        description: "单位"
      employType:
        type: "string"
        description: "使用类型"
      usage:
        type: "integer"
        description: "使用量"
      employDate:
        type: "string"
        description: "使用时间"


