swagger: "2.0"
info:
  description: "根据楼栋列表获取楼栋节次列表"
  version: "1.0.0"
  title: "实验排课相关接口文档"
host: "192.168.1.34:8080"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  '/segments/buildssegments':
    post:
      tags:
        - "Segments"
      summary: "根据楼栋列表获取楼栋节次列表"
      description: "使用方：teachinglaboratoryapi"
      operationId: "getSegmentsByBuildIds"
      parameters:
        - name: "validCode"
          in: "query"
          type: "string"
          description: "验证码&signKey=123123(md5加密)"
          required: true
        - name: "buildIdList"
          in: "body"
          description: "楼栋列表"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/BuildIdVo"
      responses:
        200:
          description: "成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/BuildingVo"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"


definitions:
  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"
        
  BuildIdVo:
    type: "object"
    properties:
      buildId:
        type: "string"
        description: "楼栋Id"  

  BuildingVo:
    type: "object"
    properties:
      buildId:
        type: "string"
        description: "楼栋Id"
      segmentList:
        type: array
        items:
          $ref: "#/definitions/SegmentVo"

  SegmentVo:
    type: "object"
    properties:
      segmentName:
        type: "string"
        description: "节次"
      segmentStartTime:
        type: "string"
        description: "节次开始时间"
      segmentEndTime:
        type: "string"
        description: "节次结束时间"
     
        
        
