swagger: "2.0"
info:
  title: "CourseApi-Api文档"
  version: "1.0.0"
  description: "班级管理教师查看引导记录相关接口文档"
host: "192.168.1.34:8080"
basePath: "/v1"
schemes:
  - "http"
paths:
  "/guidancereminderrecord":
    post:
      tags:
        - "GuidanceReminderRecord"
      summary: "新增班级管理教师查看引导记录"
      description: "云课堂老师端使用"
      operationId: "addGuidanceReminderRecord"
      produces:
        - "application/json"
      parameters:
        - name: "guidanceReminderRecordResource"
          in: "body"
          description: "新增班级管理记录教师查看记录信息"
          schema:
            $ref: "#/definitions/GuidanceReminderRecordResource"
          required: true

      responses:
        200:
          description: "成功"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        500:
          description: "服务器异常"
    get:
      tags:
        - "GuidanceReminderRecord"
      summary: "获取班级管理教师查看引导记录"
      description: "云课堂老师端使用"
      operationId: "getGuidanceReminderRecord"
      produces:
        - "application/json"
      parameters:
        - name: "userId"
          type: "string"
          in: "query"
          description: "用户id"
          required: true
        - name: "functionCode"
          type: "string"
          in: "query"
          description: "功能编码"
          required: true
        - name: "validCode"
          in: "query"
          description: "加密验证码userId=?&signKey=123123"
          type: "string"
          required: true
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/GuidanceReminderRecordVo"
        400:
          description: "参数不正确"
          schema:
            $ref: '#/definitions/ErrorResult'
        403:
          description: "验证码错误"
          schema:
            $ref: '#/definitions/ErrorResult'
        404:
          description: "未找到教师查看引导记录"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"
definitions:
  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      message:
        type: "string"
        description: "错误信息"
  GuidanceReminderRecordResource:
    type: "object"
    properties:
      userId:
        type: "string"
        description: "用户id"
      userNo:
        type: "string"
        description: "用户工号"
      userName:
        type: "string"
        description: "用户姓名"
      functionCode:
        type: "string"
        description: "功能编码：功能简称首字母+三位数字，例如：BJGL001"
      functionDescription:
        type: "string"
        description: "功能描述"
      validCode:
        type: "string"
        description: "加密验证码userId=?&signKey=123123"

  GuidanceReminderRecordVo:
    type: "object"
    properties:
      userId:
        type: "string"
        description: "用户id"
      reminderConfirmation:
        type: "boolean"
        description: "提醒确认状态"


