swagger: "2.0"
info:
  description: "课程教材附件相关接口"
  version: "1.0.0"
  title: "courseApi文档"
host: "192.168.1.34:8080"
basePath: "/v1"
schemes:
  - "https"
  - "http"
paths:
  /teachingmaterialfile/detaillist:
    get:
      tags:
        - "TeachingMaterialFile"
      summary: "接口-根据courseId获取课程材料及材料内容列表数据"
      description: "调用方：1、老师端"
      operationId: "getTeachingMaterialFileList"
      parameters:
        - name: "courseId"
          in: "query"
          description: "课程id"
          type: "string"
          required: true
        - name: "validCode"
          in: "query"
          description: "验证码：courseId=?&signKey=123123(md5加密)"
          type: "string"
          required: true
      responses:
        200:
          description: "成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TeachingMaterialFileResource"
        400:
          description: "参数不正确"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证码错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        404:
          description: "数据不存在"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

definitions:

  TeachingMaterialFileResource:
    type: "object"
    properties:
      teachingMaterialFileId:
        type: 'string'
        description: '课程教材id'
      fileDisplayName:
        type: 'string'
        description: '文件显示名称'
      fileRealName:
        type: 'string'
        description: '文件存储名称'
      fileType:
        type: 'string'
        description: '文件类型（即文件后缀）'
      innerUrl:
        type: 'string'
        description: '内网地址'
      outerUrl:
        type: 'string'
        description: '外网地址'
      filePath:
        type: "string"
        description: "文件路径"
      teachingMaterialFileContentList:
        type: array
        items:
          $ref: "#/definitions/TeachingMaterialFileContentResource"

  TeachingMaterialFileContentResource:
    type: "object"
    properties:
      teachingMaterialFileContentId:
        type: 'string'
        description: '课程建设教材内容id'
      chapterName:
        type: 'string'
        description: '章节'
      chapterIndex:
        type: 'integer'
        description: '章序号'
      fileType:
        type: 'string'
        description: '文件类型（即文件后缀）'
      contentInnerUrl:
        type: 'string'
        description: '内网地址'
      contentOuterUrl:
        type: 'string'
        description: '外网地址'
      contentPath:
        type: "string"
        description: "文件路径"

  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"





