swagger: "2.0"
info:
  description: "获取题库资源信息接口文档"
  version: "1.0.0"
  title: "courseApi文档"
host: "192.168.1.34:8080"
basePath: "/v1"
schemes:
  - "https"
  - "http"
paths:
  "/courseresourcedetail":
    get:
      tags:
        - "CourseResourceDetail"
      summary: "获取题库测验试卷资源是否公开信息"
      description: "云课堂老师端调用"
      parameters:
        - name: "resourceIds"
          in: 'query'
          required: true
          description: "试卷Id（逗号分割）"
          type: "string"
        - name: "validCode"
          in: "query"
          description: "验证码：&signKey=123123(md5加密)"
          type: "string"
          required: true
      responses:
        200:
          description: "成功"
          schema:
            type: array
            items:
              $ref: "#/definitions/CourseResourceDetailVo"
        400:
          description: "参数不正确"
          schema:
            $ref: "#/definitions/ErrorResult"
        403:
          description: "验证码错误"
          schema:
            $ref: "#/definitions/ErrorResult"
        404:
          description: "未找到资源信息"
          schema:
            $ref: "#/definitions/ErrorResult"
        500:
          description: "服务器异常"

# 资源属性描述,接口返回,参数等公共引用
definitions:
  ErrorResult:
    type: "object"
    properties:
      code:
        type: "string"
        description: "错误码"
      error:
        type: "string"
        description: "错误信息"

  CourseResourceDetailVo:
    type: object
    properties:
      resourceId:
        type: string
        description: "资源id"
      resourceDetailId:
        type: string
        description: "资源详情id"
      isPublic:
        type: boolean
        description: "是否公开"


