/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.coursetabledetailteacher;

import com.lztech.site.viewmodel.coursetabledetailteacher.AutonomousClassTeacher;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-09-24T07:27:55.359Z")

@Api(value = "autonomousClassTeacher", description = "the autonomousClassTeacher API")
@RequestMapping(value = "/v1")
public interface AutonomousClassTeacherApi {

    @ApiOperation(value = "自主开班老师添加"
            , nickname = "autonomousClassTeacherAddteacherPost"
            , notes = "云课堂web", tags = {"AutonomousClassTeacher",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "自由班级信息不存在", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/autonomousClassTeacher/addteacher",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> autonomousclassteacherAddteacherPost(
            @ApiParam(value = "", required = true)
            @Valid @RequestBody List<AutonomousClassTeacher> addTeacherList,
            @NotNull @ApiParam(value = "主课表id", required = true)
            @Valid @RequestParam(value = "courseTableId", required = true) String courseTableId,
            @NotNull @ApiParam(value = "操作人Id", required = true)
            @Valid @RequestParam(value = "operatorId", required = true) String operatorId,
            @NotNull @ApiParam(value = "操作人名称", required = true)
            @Valid @RequestParam(value = "operatorName", required = true) String operatorName,
            @NotNull @ApiParam(value = "courseTableId=XX&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "自主开班老师删除"
            , nickname = "autonomousClassTeacherDeleteteacherDelete"
            , notes = "云课堂web", tags = {"AutonomousClassTeacher",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "客户端错误", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "自由班级信息/老师信息不存在", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/autonomousClassTeacher/deleteteacher",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> autonomousclassteacherDeleteteacherDelete(
            @ApiParam(value = "", required = true)
            @Valid @RequestBody List<AutonomousClassTeacher> deleteTeacherIdList,
            @NotNull @ApiParam(value = "主课表id", required = true)
            @Valid @RequestParam(value = "courseTableId", required = true) String courseTableId,
            @NotNull @ApiParam(value = "操作人Id", required = true)
            @Valid @RequestParam(value = "operatorId", required = true) String operatorId,
            @NotNull @ApiParam(value = "操作人名称", required = true)
            @Valid @RequestParam(value = "operatorName", required = true) String operatorName,
            @NotNull @ApiParam(value = "courseTableId=XX&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


}
