/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.student;

import com.lztech.site.resource.coursetabledetail.WeekCourseTableDetailPage;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.studentcoursetable.StudentCourseTableDetailBaseResource;
import com.lztech.site.viewmodel.studentcoursetable.StudentCourseTableDetailParam;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2025-04-29T14:36:17.223+08:00")

@Api(value = "student", description = "the student API")
@RequestMapping(value = "/api/v1")
public interface StudentCourseTableDetailApi {

    @ApiOperation(value = "获取学生课表详情", nickname = "getStudentCourseTableDetail", notes = "学生端使用", response =
            StudentCourseTableDetailBaseResource.class, responseContainer = "List", tags = {"StudentCourseTableDetail",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = StudentCourseTableDetailBaseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class)})
    @RequestMapping(value = "/student/{id}/courseTableDetail",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<List<StudentCourseTableDetailBaseResource>> getStudentCourseTableDetail(
            @ApiParam(value = "学生Id", required = true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "加密验证码id={}&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "请求参数", required = true) @Valid @RequestBody StudentCourseTableDetailParam param);

    @ApiOperation(value = "获取学生周课表详情", nickname = "getStudentCourseTableDetailWeekDetailInfo", notes = "学生端使用",
            response = WeekCourseTableDetailPage.class, tags={ "StudentCourseTableDetail", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = WeekCourseTableDetailPage.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/student/{id}/courseTableDetail/weekdetailinfo",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<WeekCourseTableDetailPage> getStudentCourseTableDetailWeekDetailInfo(
            @ApiParam(value = "学生Id",required=true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "加密验证码id={}&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "上课日期", required = true) @Valid @RequestParam(value = "courseDate", required = true)
            String courseDate,
            @NotNull @ApiParam(value = "学年", required = true) @Valid @RequestParam(value = "schoolYear", required = true)
            String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true) @Valid @RequestParam(value = "term", required = true)
            Integer term);

}
