/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.37).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teachingreport;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.teachingreport.*;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2023-11-29T09:45:52.037Z")

@Validated
@Api(value = "teachingreports", description = "the teachingreports API")
@RequestMapping(value = "/v1")
public interface TeachingreportsApi {

    @ApiOperation(value = "根据学院和学期获取学院开课基础信息接口编写", nickname = "getTeachingReportOfferingCourseInfo",
            notes = "使用方：1、云课堂听查课端 教学报告 教学数据总览", response = OfferCourseInfoVo.class, tags={ "TeachingReport", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = OfferCourseInfoVo.class),
        @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
        @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingreports/offeringcourseinfo",
        method = RequestMethod.POST)
    ResponseEntity<OfferCourseInfoVo> getTeachingReportOfferingCourseInfo(
            @ApiParam(value = "查询参数" ,required=true )
            @Valid @RequestBody OfferingCourseRequest queryParam,
            @ApiParam(value = "验证码：&signKey=123123(md5加密)")
            @Valid @RequestParam(value = "validCode", required = false) String validCode);

    @ApiOperation(value = "根据教学报告参数统计对应资源个数、上传老师列表、资源占用", nickname = "getCourseResourceStatistics",
            notes = "使用方：1、云课堂听查课端-教学报告-教学数据总览-教学资源统计",
            response = TeachingReportCourseResourceStatisticsVo.class, tags={ "TeachingReport", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingReportCourseResourceStatisticsVo.class),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingreports/courseresourcesstatistics",
            method = RequestMethod.POST)
    ResponseEntity<TeachingReportCourseResourceStatisticsVo> getCourseResourceStatistics(
            @ApiParam(value = "查询参数" ,required=true )
            @Valid @RequestBody OfferingCourseRequest queryParam,
            @ApiParam(value = "验证码：&signKey=123123(md5加密)")
            @Valid @RequestParam(value = "validCode", required = false) String validCode);

    @ApiOperation(value = "根据教学报告参数统计对应学院老师备课包资源数据", nickname =
            "getCourseResourceCollegeStatisticsList", notes = "使用方：1、内部调用",
            response = CourseResourceCollegeStatisticsModel.class, responseContainer = "List", tags={ "TeachingReport", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseResourceCollegeStatisticsModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingreports/courseresourcecollegestatistics",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseResourceCollegeStatisticsModel>> getCourseResourceCollegeStatisticsList(
            @ApiParam(value = "查询参数" ,required=true )
            @Valid @RequestBody CollegeTeacherResourceStatisticsRequest queryParam,
            @ApiParam(value = "验证码：&signKey=123123(md5加密)")
            @Valid @RequestParam(value = "validCode", required = false) String validCode);



}
