/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseobjective;

import com.lztech.site.viewmodel.courseobjective.*;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2025-11-06T15:46:11.737+08:00")

@Api(value = "courseObjectives", description = "the courseObjectives API")
@RequestMapping("/api/v1")
public interface CourseObjectivesApi {

    @ApiOperation(value = "新增课程目标", nickname = "createCourseObjective",
            notes = "1.云课堂教师端使用", tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "新增成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives",
            method = RequestMethod.POST)
    ResponseEntity<CourseObjectiveResponse> createCourseObjective(
            @ApiParam(value = "", required = true) @Valid @RequestBody
            CourseObjectiveCreateRequest param,
            @ApiParam(value = "验证码  &signKey=123123(md5加密)") @Valid
            @RequestParam(value = "validCode", required = false) String validCode);


    @ApiOperation(value = "删除课程目标", nickname = "deleteCourseObjective",
            notes = "1.云课堂教师端使用", tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "删除成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives/{id}/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> deleteCourseObjective(
            @ApiParam(value = "课程目标ID", required = true) @PathVariable("id") String id,
            @ApiParam(value = "", required = true) @Valid @RequestBody
            CourseObjectiveUpdateRequest body,
            @ApiParam(value = "验证码 id={}&signKey=123123(md5加密)")
            @Valid @RequestParam(value = "validCode", required = false) String validCode);


    @ApiOperation(value = "编辑课程目标", nickname = "modifyCourseObjective", notes = "1.云课堂教师端使用",
            tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "修改成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives/{id}/modify",
            method = RequestMethod.POST)
    ResponseEntity<Void> modifyCourseObjective(
            @ApiParam(value = "课程目标ID", required = true) @PathVariable("id") String id,
            @ApiParam(value = "", required = true) @Valid @RequestBody CourseObjectiveUpdateRequest body,
            @ApiParam(value = "验证码 id={}&signKey=123123(md5加密)")
            @Valid @RequestParam(value = "validCode", required = false) String validCode);


    @ApiOperation(value = "查询课程目标列表", nickname = "queryCourseObjective", notes = "1.云课堂教师端使用",
            response = CourseObjectiveMainInfo.class, tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "查询成功", response = CourseObjectiveMainInfo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives",
            method = RequestMethod.GET)
    ResponseEntity<CourseObjectiveMainInfo> queryCourseObjective(
            @NotNull @ApiParam(value = "课程ID", required = true) @Valid
            @RequestParam(value = "courseId", required = true) String courseId,
            @ApiParam(value = "验证码 courseId={}&signKey=123123(md5加密)") @Valid
            @RequestParam(value = "validCode", required = false) String validCode);


    @ApiOperation(value = "拖拽排序", nickname = "sortCourseObjective", notes = "1.云课堂教师端使用", tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "排序更新成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives/sort",
            method = RequestMethod.POST)
    ResponseEntity<Void> sortCourseObjective(
            @ApiParam(value = "", required = true) @Valid @RequestBody CourseObjectiveSortRequest param,
            @NotNull @ApiParam(value = "验证码 courseId={}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "课程目标关联图谱", nickname = "relatedCourseObjectiveKnowledgeGraphNode",
            notes = "1.云课堂教师端使用", tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "关联图谱成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives/{id}/related/knowledgeGraphNode",
            method = RequestMethod.POST)
    ResponseEntity<Void> relatedCourseObjectiveKnowledgeGraphNode(
            @ApiParam(value = "", required = true) @Valid @RequestBody
            CourseObjectiveRelatedKnowledgeGraphNodeRequest param,
            @NotNull @ApiParam(value = "验证码 id={}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程目标ID", required = true) @PathVariable("id") String id);


    @ApiOperation(value = "获取课程目标关联图谱", nickname = "getCourseObjectiveRelatedKnowledgeGraphNode",
            notes = "1.云课堂教师端使用", response = CourseObjectiveRelatedKnowledgeGraphNodeResult.class,
            tags = {"CourseObjective",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "查询成功", response = CourseObjectiveRelatedKnowledgeGraphNodeResult.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseObjectives/{id}/knowledgeGraphNode",
            method = RequestMethod.GET)
    ResponseEntity<CourseObjectiveRelatedKnowledgeGraphNodeResult> getCourseObjectiveRelatedKnowledgeGraphNode(
            @ApiParam(value = "课程目标ID", required = true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "验证码 id={}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


}
