/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.coursetabledetail.imports;

import com.lztech.site.viewmodel.coursetabledetail.GroupCourseTableInfo;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-02-22T05:44:45.129Z")

@Api(value = "coursetabledetail", description = "the coursetabledetail API")
@RequestMapping(value = "/v1")
public interface CoursetabledetailImportApi {

    @ApiOperation(value = "课表明细导入", nickname = "coursetabledetailImportPost", notes = "课表明细导入，云课堂管理端使用", tags = {"CourseTableDetail",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到此课表信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "校验未通过", response = ErrorResult.class, responseContainer = "List"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/import",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> coursetabledetailImportPost(@NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
                                                     @Valid @RequestParam(value = "validCode", required = true)
                                                             String validCode,
                                                     @ApiParam(value = "导入课表的明细", required = true)
                                                     @Valid @RequestBody GroupCourseTableInfo groupCourseTableDetail);

}
