/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.administrativeclass;

import com.lztech.site.resource.administrativeclass.AdministrativeVo;
import com.lztech.site.resource.administrativeclass.ClassCourseTablePage;
import com.lztech.site.resource.coursetable.CourseTypeCountResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-22T01:42:27.475Z")

@Api(value = "classes", description = "the classes API")
public interface ClassesApi {

    @ApiOperation(value = "班级课表查询", nickname = "classesCoursetablesPagePost", notes = "调用方 小程序 班级课表查询",
            response = ClassCourseTablePage.class, tags = {"AdministrativeClassAndTeachingClass",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = ClassCourseTablePage.class),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到班级课表"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/classes/coursetables/page",
            method = RequestMethod.POST)
    ResponseEntity<ClassCourseTablePage> classesCoursetablesPagePost(
            @ApiParam(value = "", required = true)
            @Valid @RequestBody AdministrativeVo administrative,
            @NotNull @ApiParam(value = "MD5加密验证字符串 (&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "班级课表查询统计接口", nickname = "classesCoursetablesStatisticsPost", notes = "小程序班级课表查询统计接口",
            response = CourseTypeCountResource.class, tags = {"AdministrativeClassAndTeachingClass",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTypeCountResource.class),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到班级课表"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/classes/coursetables/statistics",
            method = RequestMethod.POST)
    ResponseEntity<CourseTypeCountResource> classesCoursetablesStatisticsPost(
            @ApiParam(value = "", required = true)
            @Valid @RequestBody AdministrativeVo administrative,
            @NotNull @ApiParam(value = "MD5加密验证字符串 (&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
