/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.segment;

import com.lztech.site.resource.segment.SegmentTimeResource;
import com.lztech.site.resource.segment.WeekIndexResource;
import com.lztech.site.viewmodel.SegmentResource;
import com.lztech.site.viewmodel.segment.*;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-08T03:08:12.542Z")

@Api(value = "segment", description = "the segment API")
@RequestMapping(value = "/v1")
public interface SegmentApi {

    @ApiOperation(value = "根据楼栋查询节次信息", nickname = "segmentGet", notes = "云课堂前端使用",
            response = SegmentResource.class, responseContainer = "List", tags = {"SegmentResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = SegmentResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课次信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<SegmentResource>> segmentGet(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                                     @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                     @ApiParam(value = "楼栋Id") @Valid @RequestParam(value = "buildId", required = false)
                                                     String buildId);


    @ApiOperation(value = "根据周次，星期获取当前日期", nickname = "datebyweekPost", notes = "小程序调用", response = CourseDate.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseDate.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到日期信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/datebyweek",
            method = RequestMethod.GET)
    ResponseEntity<CourseDate> datebyweekPost(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "星期", required = true)
            @Valid @RequestParam(value = "weekDay", required = true) Integer weekDay,
            @NotNull @ApiParam(value = "周次", required = true)
            @Valid @RequestParam(value = "weekNum", required = true) Integer weekNum,
            @ApiParam(value = "节次id")
            @Valid @RequestParam(value = "buildingId", required = false) String buildingId);

    @ApiOperation(value = "获取节次时间", nickname = "segmenttimeGet", notes = "小程序调用", response = SegmentTimeResource.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = SegmentTimeResource.class),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segmenttime",
            method = RequestMethod.GET)
    ResponseEntity<SegmentTimeResource> segmenttimeGet(
            @NotNull @ApiParam(value = "节次", required = true)
            @Valid @RequestParam(value = "segment", required = true) Integer segment,
            @NotNull @ApiParam(value = "周次", required = true)
            @Valid @RequestParam(value = "weekNum", required = true) Integer weekNum,
            @NotNull @ApiParam(value = "星期", required = true)
            @Valid @RequestParam(value = "weekDay", required = true) Integer weekDay,
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "buildingId")
            @Valid @RequestParam(value = "buildingId", required = false) String buildingId);

    @ApiOperation(value = "获取当前周次、星期、节次信息", nickname = "segmentNowdateGet", notes = "小程序调用",
            response = WeekIndexResource.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = WeekIndexResource.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证失败"),
            @ApiResponse(code = 404, message = "未找到当前周次、星期、节次信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/nowdate",
            method = RequestMethod.GET)
    ResponseEntity<WeekIndexResource> segmentNowdateGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "buildingId")
            @Valid @RequestParam(value = "buildingId", required = false) String buildingId);


    @ApiOperation(value = "根据开始结束时间获取节次时间段", nickname = "timebysegmentPost", notes = "小程序调用", response = CourseDate.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseDate.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到日期信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/timebysegment",
            method = RequestMethod.GET)
    ResponseEntity<CourseDate> timebysegmentPost(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "开始节次", required = true)
            @Valid @RequestParam(value = "sSegment", required = true) Integer sSegment,
            @NotNull @ApiParam(value = "结束节次", required = true)
            @Valid @RequestParam(value = "eSegment", required = true) Integer eSegment,
            @ApiParam(value = "节次id")
            @Valid @RequestParam(value = "buildingId", required = false) String buildingId);

    @ApiOperation(value = "根据楼栋id获楼栋当前节次", nickname = "getNowSegmentInfo", notes = "InformationReleaseSystemInternalApi项目调用",
            response = NowSegment.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = NowSegment.class),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/getNowSegmentInfo",
            method = RequestMethod.GET)
    ResponseEntity<NowSegment> getNowSegmentInfo(@NotNull @ApiParam(value = "MD5加密验证字符串buildId=?&signKey=123123", required = true)
                                                 @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                 @NotNull @ApiParam(value = "楼栋Id", required = true)
                                                 @Valid @RequestParam(value = "buildId", required = true) String buildId);

    @ApiOperation(value = "根据楼栋ids查询节次信息", nickname = "segmentBuildingIdsGet", notes = "信息发布服务调用", response = BuildingVo.class,
            responseContainer = "List", tags = {"SegmentResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = BuildingVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/buildingIds",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<BuildingVo>> segmentBuildingIdsGet(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                                           @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                           @ApiParam(value = "楼栋Ids")
                                                           @Valid @RequestParam(value = "buildIds", required = false) String buildIds);

    @ApiOperation(value = "教室查询结果详情接口", nickname = "segmentClassroomSegmentCourseDetailsPost", notes = "1.自助终端使用",
            response = ClassroomSegmentCourseVo.class, responseContainer = "List", tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = ClassroomSegmentCourseVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/classroomSegmentCourseDetails",
            method = RequestMethod.POST)
    ResponseEntity<List<ClassroomSegmentCourseVo>> segmentClassroomSegmentCourseDetailsPost(
            @ApiParam(value = "", required = true) @Valid @RequestBody SegmentQueryParam segmentQueryParam);

    @ApiOperation(value = "课表查询结果详情接口", nickname = "segmentCourseScheduleDetailsPost", notes = "1.自助终端使用",
            response = ClassroomSegmentCoursePage.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = ClassroomSegmentCoursePage.class),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/courseScheduleDetails",
            method = RequestMethod.POST)
    ResponseEntity<ClassroomSegmentCoursePage> segmentCourseScheduleDetailsPost(
            @ApiParam(value = "", required = true) @Valid @RequestBody CourseQueryParam courseQueryParam);


    @ApiOperation(value = "查询节次课表", nickname = "coursetableSegmentGet", notes = "巡检监控系统调用",
            response = SegmentDataResource.class, responseContainer = "List", tags = {"RoomSegmentTask",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = SegmentDataResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密错误"),
            @ApiResponse(code = 404, message = "未找到节次课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/segment",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<SegmentDataResource>> coursetableSegmentGet(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取默认楼栋节次", nickname = "segmentDefaulbuildingsegmentGet", notes = "巡检监控系统调用",
            response = NowSegment.class, responseContainer = "List", tags = {"RoomSegmentTask",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = NowSegment.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密错误"),
            @ApiResponse(code = 404, message = "未找到节次课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/defaultbuildingsegment",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<NowSegment>> segmentDefaultbuildingsegmentGet(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取所有节次信息（去重）", nickname = "segmentAllGet", notes = "1.三画面下载使用",
            response = SegmentVo.class, responseContainer = "List", tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = SegmentVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/all",
            method = RequestMethod.GET)
    ResponseEntity<List<SegmentVo>> segmentAllGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据教室id获取今天对应节次课表课程信息", nickname = "segmentRoomIdGet",
            notes = "1.电子班牌", response = BuildingSegmentResource.class, tags = {"Segment",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = BuildingSegmentResource.class),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segment/{roomId}",
            method = RequestMethod.GET)
    ResponseEntity<BuildingSegmentResource> getBuildingSegmentResource(
            @ApiParam(value = "教室id", required = true)
            @PathVariable("roomId") String roomId,
            @NotNull @ApiParam(value = "验证码：roomId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据楼栋查询节次信息", nickname = "getBuildAndSegmentList", notes = "云课堂课表录制服务使用",
            response = SegmentResourceVo.class, responseContainer = "List", tags = {"SegmentResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = SegmentResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课次信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/segments",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<SegmentResourceVo>> getBuildAndSegmentList(
            @NotNull @ApiParam(value = "&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "楼栋Id") @Valid @RequestParam(value = "buildId", required = false) String buildId);

}


