/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.segment;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.segment.BuildIdVo;
import com.lztech.site.viewmodel.segment.BuildingVo;
import com.lztech.site.viewmodel.segment.CourseTableDetailSegment;
import com.lztech.site.viewmodel.segment.SegmentTaskResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-20T12:16:00.895Z")

@Api(value = "segments", description = "the segments API")
@RequestMapping(value = "/v1")
public interface SegmentsApi {

    @ApiOperation(value = "接口-获取所有楼栋的节次任务", nickname = "segmentsTasksGet",
            notes = "teachingvideoservice服务使用", response = SegmentTaskResource.class, responseContainer = "List", tags={ "Segments", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = SegmentTaskResource.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
        @ApiResponse(code = 401, message = "验证失败"),
        @ApiResponse(code = 404, message = "当前时间不存在课表"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/segments/tasks",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SegmentTaskResource>> segmentsTasksGet(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "指定查询日期（yyyy-MM-dd）,可以为空,如果为空则查询当天的")
            @Valid @RequestParam(value = "date", required = false) String date,
            @ApiParam(value = "开课类型")
            @Valid @RequestParam(value = "studentType", required = false) Integer studentType);
    @ApiOperation(value = "接口-获取所有的节次任务", nickname = "getSegmentTaskList", notes = "teachingvideoservice服务使用",
            response = CourseTableDetailSegment.class, responseContainer = "List", tags={ "Segments", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDetailSegment.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 401, message = "验证失败"),
            @ApiResponse(code = 404, message = "当前时间不存在课表"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/segmenttasks",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableDetailSegment>> getSegmentTaskList(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "指定查询日期（yyyy-MM-dd）,可以为空,如果为空则查询当天的")
            @Valid @RequestParam(value = "date", required = false) String date,
            @ApiParam(value = "开课类型")
            @Valid @RequestParam(value = "studentType", required = false) Integer studentType);



    @ApiOperation(value = "根据楼栋列表获取楼栋节次列表", nickname = "getSegmentsByBuildIds",
            notes = "使用方：teachinglaboratoryapi", response = BuildingVo.class, responseContainer = "List", tags={ "Segments", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = BuildingVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/segments/buildssegments",
            method = RequestMethod.POST)
    ResponseEntity<List<BuildingVo>> getSegmentsByBuildIds(
            @NotNull @ApiParam(value = "验证码&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "楼栋列表"  )  @Valid @RequestBody List<BuildIdVo> buildIdList);


}
