/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.groupcard;

import com.lztech.site.viewmodel.group.GroupCardData;
import com.lztech.site.viewmodel.group.GroupMemberVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-17T08:00:47.801Z")

@Api(value = "groupcard", description = "the groupcard API")
@RequestMapping(value = "/v1")
public interface GroupcardApi {

    @ApiOperation(value = "扫码加入班级", nickname = "groupcardPost", notes = "小程序调用", tags = {"GroupCard",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密错误"),
            @ApiResponse(code = 404, message = "未找到班级信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupcard",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> groupcardPost(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "学生信息") @Valid @RequestBody GroupCardData groupCardData);

    @ApiOperation(value = "获取班级人数", nickname = "groupcardGroupIdStudentcountGet",
            notes = "互动课堂、PTT插件使用",
            response = GroupMemberVo.class, tags = {"GroupCard",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = GroupMemberVo.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密错误"),
            @ApiResponse(code = 404, message = "未找到班级人员信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/groupcard/{groupId}/studentcount",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<GroupMemberVo> groupcardGroupIdStudentcountGet(
            @ApiParam(value = "班级Id", required = true)
            @PathVariable("groupId") String groupId,
            @NotNull @ApiParam(value = "验证码：groupId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);
}
