/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teachingcenter;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.teachingcenterstatistics.TeachingCenterJobTitleStatistics;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-06-15T06:15:36.817Z")

@Validated
@Api(value = "teachingcenter", description = "the teachingcenter API")
@RequestMapping(value = "/v1")
public interface TeachingcenterApi {

    @ApiOperation(value = "获取实验中心课表教学人时数量", nickname = "getTeachingCenterTeachingQuantity"
            , notes = "调用方：云课堂管理端", response = Integer.class, tags = {"TeachingCenterStatistics",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingcenter/teachingquantity",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getTeachingCenterTeachingQuantity(
            @NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "实验中心id(不传值则查询全部实验中心数据)")
            @Valid @RequestParam(value = "teachingCenterId", required = false) String teachingCenterId);

    @ApiOperation(value = "获取实验中心上课教师数量", nickname = "getTeacherInClassQuantity"
            , notes = "调用方：云课堂管理端", response = Integer.class, tags = {"TeachingCenterStatistics",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Integer.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingcenter/teacherinclassquantity",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Integer> getTeacherInClassQuantity(
            @NotNull @ApiParam(value = "加密验证码: &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "实验中心id(不传值则查询全部实验中心数据)")
            @Valid @RequestParam(value = "teachingCenterId", required = false) String teachingCenterId);

    @ApiOperation(value = "根据教学中心统计开课下各职称老师数量",
            nickname = "statisticsTeachingCenterInClassTeacher",
            notes = "1、云课堂管理端-实验中心统计使用", response = Object.class,
            tags = {"TeachingCenterStatistics",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Object.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/teachingcenter/jobtitle/statistics",
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingCenterJobTitleStatistics>> courseJobTitleTeacherStatistics(@NotNull
                                                                                           @ApiParam(value = "学年", required = true)
                                                                                           @Valid
                                                                                           @RequestParam(value = "schoolYear", required = true)
                                                                                                   String schoolYear,
                                                                                           @NotNull @ApiParam(value = "学期", required = true)
                                                                                           @Valid @RequestParam(value = "term", required = true)
                                                                                                   Integer term,
                                                                                           @NotNull @ApiParam(value = "验证码（&signKey=123123）",
                                                                                                   required = true)
                                                                                           @Valid @RequestParam(value = "validCode",
                                                                                                   required = true)
                                                                                                   String validCode,
                                                                                           @ApiParam(value = "实验中心id") @Valid
                                                                                           @RequestParam(value = "teachingCenterId",
                                                                                                   required = false)
                                                                                                   String teachingCenterId);

}
