/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseconstruction;

import com.lztech.site.viewmodel.coursemanagement.CourseCompletionDetailResource;
import com.lztech.site.viewmodel.coursemanagement.CourseCompletionResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-02-28T09:21:24.689Z")

@Validated
@Api(value = "coursecompletion", description = "the coursecompletion API")
@RequestMapping(value = "/v1")
public interface CourseCompletionApi {

    @ApiOperation(value = "获取课程完成度接口", nickname = "getCourseCompletion", notes = "1.云课堂教师端：课程建设使用", response = CourseCompletionResource.class,
            responseContainer = "List", tags = {"CourseCompletion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseCompletionResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursecompletion",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseCompletionResource>> getCourseCompletion(@NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                                                       @Valid @RequestParam(value = "validCode", required = true)
                                                                               String validCode,
                                                                       @NotNull @ApiParam(value = "课程ids", required = true)
                                                                       @Valid @RequestParam(value = "courseIds", required = true)
                                                                               String courseIds);


    @ApiOperation(value = "获取课程完成度详情", nickname = "getCourseCompletionDetail",
            notes = "1.云课堂教师端：课程建设使用", response = CourseCompletionDetailResource.class,
            responseContainer = "List", tags = {"CourseCompletion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseCompletionDetailResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursecompletion/detail",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseCompletionDetailResource>> getCourseCompletionDetail(@NotNull
                                                                                   @ApiParam(value = "验证码（courseId={}&signKey=123123）",
                                                                                           required = true)
                                                                                   @Valid @RequestParam(value = "validCode", required = true)
                                                                                           String validCode,
                                                                                   @NotNull @ApiParam(value = "课程id", required = true)
                                                                                   @Valid @RequestParam(value = "courseId", required = true)
                                                                                           String courseId);

}
