/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseconstruction;

import com.lztech.site.viewmodel.coursechaptergoal.CourseChapterGoalVo;
import com.lztech.site.viewmodel.coursechaptergoal.CourseStructureBaseResource;
import com.lztech.site.viewmodel.courseconstruction.CourseChapterGoalTypeResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-02-24T09:15:35.278Z")

@Validated
@Api(value = "coursechaptergoal", description = "the coursechaptergoal API")
@RequestMapping(value = "/v1")
public interface CoursechaptergoalApi {

    @ApiOperation(value = "获取章节目标分类", nickname = "coursechaptergoalTypeGet", notes = "1.云课堂教师端-课程建设使用", response =
            CourseChapterGoalTypeResource.class, responseContainer = "List", tags = {"CourseChapterGoal",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseChapterGoalTypeResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursechaptergoal/type",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseChapterGoalTypeResource>> coursechaptergoalTypeGet(@NotNull
                                                                                 @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                                                                 @Valid @RequestParam(value = "validCode", required = true)
                                                                                         String validCode);

    @ApiOperation(value = "获取章节目标", nickname = "getCourseChapterGoal",
            notes = "1.云课堂教师端-课程建设使用", response = CourseStructureBaseResource.class,
            responseContainer = "List", tags = {"CourseChapterGoal",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseStructureBaseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursechaptergoal",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseStructureBaseResource>> getCourseChapterGoal(@NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                                                           @Valid @RequestParam(value = "validCode", required = true)
                                                                                   String validCode,
                                                                           @ApiParam(value = "章节id") @Valid
                                                                           @RequestParam(value = "structureId", required = false)
                                                                                   String structureId,
                                                                           @ApiParam(value = "课程id") @Valid
                                                                           @RequestParam(value = "courseId", required = false)
                                                                                   String courseId,
                                                                           @ApiParam(value = "版本id") @Valid
                                                                           @RequestParam(value = "versionId", required = false)
                                                                                   String versionId);


    @ApiOperation(value = "新增课程章节目标", nickname = "addCourseChapterGoal",
            notes = "1.云课堂教师端-课程建设使用", tags = {"CourseChapterGoal",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursechaptergoal",
            method = RequestMethod.POST)
    ResponseEntity<Void> addCourseChapterGoal(@NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                              @Valid @RequestParam(value = "validCode", required = true)
                                                      String validCode,
                                              @ApiParam(value = "课程章节目标信息", required = true)
                                              @Valid @RequestBody CourseChapterGoalVo courseChapterGoalVo);


}
