/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseconstruction;

import com.lztech.site.viewmodel.courseconstruction.CourseVersionResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-02-18T07:05:46.115Z")

@Validated
@Api(value = "course", description = "the course API")
@RequestMapping(value = "/v1")
public interface CourseVersionApi {

    @ApiOperation(value = "获取课程版本信息,如没有版本信息，则生成版本信息", nickname = "getCourseVersion",
            notes = "1.云课堂老师端-课程建设详情使用", response = CourseVersionResource.class,
            responseContainer = "List", tags = {"CourseVersion",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseVersionResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/course/{id}/courseversion",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseVersionResource>> getCourseVersion(@NotNull @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
                                                                 @Valid @RequestParam(value = "validCode", required = true)
                                                                         String validCode,
                                                                 @ApiParam(value = "课程id", required = true)
                                                                 @PathVariable("id")
                                                                         String id,
                                                                 @ApiParam(value = "版本状态 0：已归档；1：使用中")
                                                                 @Valid @RequestParam(value = "versionStatus", required = false)
                                                                         Integer versionStatus);


    @ApiOperation(value = "课程建设归档，生成版本号", nickname = "saveCourseVersion", notes = "1.云课堂老师端-课程建设归档使用", tags={ "CourseVersion", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/course/{id}/version",
            method = RequestMethod.POST)
    ResponseEntity<Void> saveCourseVersion(
            @NotNull @ApiParam(value = "验证码（id={}&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程id",required=true) @PathVariable("id") String id,
            @ApiParam(value = "课程建设归档信息" ,required=true )
            @Valid @RequestBody CourseVersionResource courseVersionResource);


}
