/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseleader;

import com.lztech.site.resource.course.CourseInfoResource;
import com.lztech.site.viewmodel.courseleader.CourseLeaderVo;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-02T06:08:10.691Z")

@Api(value = "courseleader", description = "the courseleader API")
@RequestMapping(value = "/v1")
public interface CourseleaderApi {

    @ApiOperation(value = "课程负责人转让", nickname = "courseleaderPost", notes = "1、云课堂老师端课程管理调用", tags = {"CourseLeader",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密验证失败", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到老师相关信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "该老师不是课程负责人", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/courseleader",
            method = RequestMethod.POST)
    ResponseEntity<Void> courseleaderPost(
            @ApiParam(value = "", required = true)
            @Valid @RequestBody CourseLeaderVo courseLeaderVo,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取用户作为课程负责人所管理的课程", nickname = "getUserLeaderCourse",
            notes = "1.云课堂教师端-项目配置管理使用", response = CourseInfoResource.class,
            responseContainer = "List", tags = {"Course",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfoResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/user/{id}/courseleader/course",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfoResource>> getUserLeaderCourse(@NotNull @ApiParam(value = "验证码：id={}&signKey=123123(md5加密)", required = true)
                                                                 @Valid @RequestParam(value = "validCode", required = true)
                                                                         String validCode,
                                                                 @ApiParam(value = "直播讲座id", required = true)
                                                                 @PathVariable("id")
                                                                         String id);

}
