/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teachers;

import com.lztech.site.viewmodel.CourseTableSimpleVo;
import com.lztech.site.viewmodel.TeacherCourseTableSimpleResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.peerreview.TeacherPeerReviewCourseResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-12T05:40:01.236Z")

@Api(value = "teachers", description = "the teachers API")
@RequestMapping(value = "")
public interface TeachersApi {

    @ApiOperation(value = "接口-获取老师当前时间的课表简项信息", nickname = "teachersCurrentcoursetablesGet",
            notes = "互动课堂使用", response = CourseTableSimpleVo.class, tags = {"teachers",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableSimpleVo.class),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "当前时间不存在课表"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/teachers/currentcoursetables",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CourseTableSimpleVo> teachersCurrentcoursetablesGet(
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码：teacherId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取教师下课程以及开课班级以及课程项目", nickname =
            "getTeacherCourseTableGroupAndProject", notes = "1.云课堂教师端-同伴互评使用",
            response = TeacherPeerReviewCourseResource.class, responseContainer = "List", tags = {"TeacherCourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = TeacherPeerReviewCourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/teacher/coursetable/groupandproject",
            method = RequestMethod.GET)
    ResponseEntity<List<TeacherPeerReviewCourseResource>> getTeacherCourseTableGroupAndProject(
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "老师Id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "加密验证码userId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "接口-获取老师当前时间的课表简项信息",
            nickname = "teachersCurrentcoursetablesGet",
            notes = "互动课堂使用", response = CourseTableSimpleVo.class, tags = {"teachers",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeacherCourseTableSimpleResource.class),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "当前时间不存在课表"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v2/teachers/currentcoursetables",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TeacherCourseTableSimpleResource>> getTeachersCurrentCourseTableList(
            @NotNull @ApiParam(value = "老师id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码：teacherId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
