/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.administratorclass;

import com.lztech.site.resource.administratorclass.AdministrativeClassGroupInfo;
import com.lztech.site.resource.administratorclass.AdministrativeClassInfo;
import com.lztech.site.resource.administratorclass.AdministrativeClassInfoVo;
import com.lztech.site.resource.administratorclass.AdministrativeClassVo;
import com.lztech.site.viewmodel.administratorclass.AdministrativeClassResourceVo;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-20T08:30:00.298Z")

@Api(value = "administrativeclass", description = "the administrativeclass API")
@RequestMapping(value = "/v1")
public interface AdministrativeclassApi {

    @ApiOperation(value = "保存行政班教学班关系", nickname = "administrativeclassGroupsPost", notes = "数据对接使用", tags={ "AdministrativeClassResource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功"),
        @ApiResponse(code = 400, message = "参数不正确"),
        @ApiResponse(code = 401, message = "解密验证失败"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/administrativeclass/groups",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> administrativeclassGroupsPost(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                                       @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                       @ApiParam(value = "行政班教学班关系列表" ,required=true )
                                                       @Valid @RequestBody List<AdministrativeClassGroupInfo> administrativeClassGroups);


    @ApiOperation(value = "保存行政班", nickname = "administrativeclassPost", notes = "数据对接使用", tags={ "AdministrativeClassResource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功"),
        @ApiResponse(code = 400, message = "参数不正确"),
        @ApiResponse(code = 401, message = "解密验证失败"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/administrativeclass",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> administrativeclassPost(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                                 @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                 @ApiParam(value = "行政班列表" ,required=true )
                                                 @Valid @RequestBody List<AdministrativeClassInfo> administrativeClasses);


    @ApiOperation(value = "获取行政班列表信息", nickname = "administrativeclassGet", notes = "1、学业支持",
            response = AdministrativeClassVo.class, tags={ "AdministrativeClassResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = List.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "资源不存在"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/administrativeclass",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<AdministrativeClassVo>> administrativeClassGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "老师Id") @Valid @RequestParam(value = "teacherId", required = false) String teacherId);

    @ApiOperation(value = "根据老师id获取行政班列表信息", nickname = "getAdministrativeClassVoListByTeacherId",
            notes = "1、听查课端", response = AdministrativeClassInfoVo.class, responseContainer = "List",
            tags={ "AdministrativeClassResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = AdministrativeClassInfoVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "资源不存在"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/administrativeclass/{teacherId}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<AdministrativeClassInfoVo>> getAdministrativeClassVoListByTeacherId(
            @ApiParam(value = "老师id",required=true) @PathVariable("teacherId") String teacherId,
            @NotNull @ApiParam(value = "MD5加密验证字符串 teacherId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据学院id和班级名称模糊查询获取行政班列表信息", nickname = "administrativeclasslistGet",
            notes = "期末评教查看学生完成统计调用", response = AdministrativeClassResourceVo.class, responseContainer = "List",
            tags={ "AdministrativeClassResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = AdministrativeClassResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/administrativeclasslist",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<AdministrativeClassResourceVo>> getAdministrativeClassList(
            @NotNull @ApiParam(value = "MD5加密验证字符串 collegeId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "学院id", required = true)
            @Valid @RequestParam(value = "collegeId", required = true) String collegeId,
            @NotNull @ApiParam(value = "行政班名称", required = true)
            @Valid @RequestParam(value = "className", required = true) String className);


}
