/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.college;


import com.lztech.site.resource.college.CollegeCourseResource;
import com.lztech.site.resource.college.CollegeResource;
import com.lztech.site.viewmodel.college.CollegeIdsParam;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-07T02:41:59.747Z")

@Api(value = "colleges", description = "the colleges API")
public interface CollegesApi {

    @ApiOperation(value = "保存学院", nickname = "collegesPost", notes = "数据对接使用", tags={ "CollegeResource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功"),
        @ApiResponse(code = 400, message = "参数不正确"),
        @ApiResponse(code = 401, message = "解密验证失败"),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/colleges",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> collegesPost(@NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
                                      @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                      @ApiParam(value = "学院列表" ,required=true )  @Valid @RequestBody List<CollegeResource> colleges);

    @ApiOperation(value = "获取所有学院", nickname = "allcollegesGet", notes = "数据对接使用", response = CollegeResource.class,
            responseContainer = "List", tags={ "CollegeResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/colleges/all",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<CollegeResource>> allcollegesGet(@NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
                                                         @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "保存单个学院", nickname = "datadockCollegePost", notes = "数据对接使用",
            response = CollegeResource.class, tags={ "CollegeResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeResource.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/datadock/college",
            produces = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<CollegeResource> datadockCollegePost(@NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
                                                        @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                        @ApiParam(value = "学院信息" ,required=true )
                                                        @Valid @RequestBody CollegeResource college);

    @ApiOperation(value = "根据学院ids获取学院信息列表", nickname = "collegesGet",
            notes = "1、云课堂管理端督导听课使用", response = CollegeResource.class, responseContainer = "List", tags={ "CollegeResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/colleges",
            method = RequestMethod.GET)
    ResponseEntity<List<CollegeResource>> collegesGet(
            @NotNull @ApiParam(value = "学院ids（学院id逗号分割）", required = true)
            @Valid @RequestParam(value = "collegeIds", required = true) String collegeIds,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);



    @ApiOperation(value = "根据课程ID获取学院信息", nickname = "findCollegeInfoByCourseIds",
            notes = "1.teachingApi题库统计接口使用", response = CollegeCourseResource.class, responseContainer = "List",
            tags={ "CollegeResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeCourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/college/courseid",
            method = RequestMethod.POST)
    ResponseEntity<List<CollegeCourseResource>> findCollegeInfoByCourseIds(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程Id列表", required = true)
            @Valid @RequestBody List<String> courseIds);

    @ApiOperation(value = "根据学院id修改学院是否是开课学院接口", nickname = "updateCollegeCourseInfoCollege",
            notes = "1.云课堂管理端-基础数据-基础数据-学院信息", tags={ "CollegeResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "数据不存在", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误（1、已经是开课学院更新为开课学院，1、不是开课学院更新为不是开课学院）", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/v1/colleges/{id}/courseinfocollegestatus",
            method = RequestMethod.POST)
    ResponseEntity<Void> updateCollegeCourseInfoCollege(
            @ApiParam(value = "学院id",required=true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "MD5加密验证字符串(id={id}&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "是否开课学院", required = true)
            @Valid @RequestParam(value = "courseInfoCollegeStatus", required = true) Boolean courseInfoCollegeStatus);

    @ApiOperation(value = "根据学院ids和是否开课学院获取学院信息列表", nickname = "getCourseInfoOrAllCollegeByIds",
            notes = "1、云课堂听查课端 课表巡课和课程视频", response = CollegeResource.class, responseContainer = "List", tags={ "CollegeResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/colleges/courseinfoorallcolleges",
            method = RequestMethod.POST)
    ResponseEntity<List<CollegeResource>> getCourseInfoOrAllCollegeByIds(
            @ApiParam(value = "查询参数" ,required=true )  @Valid @RequestBody CollegeIdsParam queryParam,
            @ApiParam(value = "验证码：&signKey=123123(md5加密)")
            @Valid @RequestParam(value = "validCode", required = false) String validCode);

    @ApiOperation(
            value = "根据课程CODE获取学院信息", nickname = "findAllByCourseCode",
            notes = "1.学业支持统计不及格数据接口使用", response = CollegeCourseResource.class,
            responseContainer = "List", tags = {"CollegeResource",}
    )
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeCourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/college/findAllByCourseCode",
            method = RequestMethod.POST)
    ResponseEntity<List<CollegeCourseResource>> findAllByCourseCode(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程Id列表", required = true) @Valid @RequestBody List<String> courseCodes
    );
}
