/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.college;

import com.lztech.site.resource.college.CollegeVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-16T02:32:51.667Z")

@Api(value = "college", description = "the college API")
public interface CollegeApi {

    @ApiOperation(value = "获取开课学院信息", nickname = "collegeGet", notes = "小程序获取开课学院信息", response = CollegeVo.class,
            responseContainer = "List", tags = {"CollegeResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 404, message = "未找到开课学院信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/college",
            method = RequestMethod.GET)
    ResponseEntity<List<CollegeVo>> collegeGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
