/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.coursetables;

import com.lztech.domain.model.coursetabledetail.CourseParms;
import com.lztech.domain.model.coursetabledetailteacher.CourseAndMembers;
import com.lztech.site.resource.course.StudentHomepageCourse;
import com.lztech.site.resource.coursetable.CourseTableResource;
import com.lztech.site.resource.coursetable.CourseTableRunningTerm;
import com.lztech.site.resource.term.TermResource;
import com.lztech.site.viewmodel.CourseResource;
import com.lztech.site.viewmodel.assistantcourse.AssistantCourseParam;
import com.lztech.site.viewmodel.assistantcourse.AssistantCourseVo;
import com.lztech.site.viewmodel.coursetable.*;
import com.lztech.site.viewmodel.coursetabledetail.RealTimeSchedule;
import com.lztech.site.viewmodel.coursetableinfo.CourseTableInfoByRoomIdAndNowResource;
import com.lztech.site.viewmodel.coursetableinfo.CourseTableInfoResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.group.TeachingClassVo;
import com.lztech.site.viewmodel.preparelessonplugin.TeachingCourseInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-11T05:53:37.381Z")

@Api(value = "coursetables", description = "the coursetables API")
@RequestMapping(value = "/v1")
public interface CoursetablesApi {

    @ApiOperation(value = "根据课程id，老师Id和学期查询课表信息",
            nickname = "coursetablesGet", notes = "云课堂前端使用",
            response = CourseResource.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseResource>> coursetablesGet(
            @NotNull @ApiParam(value = "课程ID,多个用“,”隔开", required = true) @Valid @RequestParam(value = "courseIds", required = true) String courseIds,
            @NotNull @ApiParam(value = "老师Id", required = true) @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "学年", required = true) @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true) @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "加密验证码courseIds=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "根据老师Id和学期查询课表信息",
            nickname = "courseTablesTeacherCourseListGet",
            notes = "云课堂前端使用", response = CourseResource.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseTables/teacherCourseList",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseResource>> courseTablesTeacherCourseListGet(
            @NotNull @ApiParam(value = "老师Id", required = true) @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "学年", required = true) @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true) @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "加密验证码userId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "允许的授课学生类型的开课")
            @Valid @RequestParam(value = "courseStudentTypes", required = false) String courseStudentTypes,
            @ApiParam(value = "是否需要区分授课学生类型") @Valid @RequestParam(value = "isNeedDistinguish", required = false)
                    Boolean isNeedDistinguish,
            @ApiParam(value = "关联的授课类型") @Valid
            @RequestParam(value = "relatedScheduleTypes", required = false) String relatedScheduleTypes);

    @ApiOperation(value = "根据学生Id,课程id和学期查询课表信息", nickname = "coursetablesUserIdGet", notes = "云课堂前端使用",
            response = CourseResource.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/{userId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<StudentHomepageCourse>> coursetablesUserIdGet(
            @ApiParam(value = "学生Id", required = true)
            @PathVariable("userId") String userId,
            @NotNull @ApiParam(value = "课程ID,多个用“,”隔开", required = true)
            @Valid @RequestParam(value = "courseIds", required = true) String courseIds,
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "加密验证码userId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "保存课表信息", nickname = "coursetablesPost", notes = "数据对接使用", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> coursetablesPost(@NotNull @ApiParam(value = "&signKey=123123", required = true)
                                          @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                          @ApiParam(value = "课表列表", required = true) @Valid @RequestBody List<CourseTableResource> courseTables);


    @ApiOperation(value = "获取课表信息（日课表，周课表公用）", nickname = "coursetablesdayorweekPost",
            notes = "小程序调用", response = CourseTableResource.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDate.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到日期信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetablesdayorweek",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDate>> getCourseTablesDayOrWeek(
            @NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询课表条件集合", required = true)
            @Valid @RequestBody CourseParms courseparms);


    @ApiOperation(value = "根据课表id获取课表基本信息", nickname = "coursetablesIdBaseinfoGet",
            notes = "1、云课堂管理端根据课表获取教学计划使用", response = CourseTableBaseInfo.class, tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableBaseInfo.class),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课表"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/{id}/baseinfo",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CourseTableBaseInfo> coursetablesIdBaseinfoGet(
            @ApiParam(value = "课表id", required = true) @PathVariable("id") String id,
            @NotNull @ApiParam(value = "验证码：id={id}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "请求的开课类型(0:本科，1：研究生)", required = false)
            @Valid @RequestParam(value = "type", required = false) Integer type);

    @ApiOperation(value = "获取课表信息", nickname = "getCourseTableInfoListResource",
            notes = "信息发布服务项目调用", response = CourseTableInfoResource.class,
            responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableInfoResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密验证失败", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课程信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/coursetableinfolist",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableInfoResource>> getCourseTableInfoListResource(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "0:数据对接；1:系统录入；2:外部导入；3:自主开班；4:备课夹新建课程；5:二次排课（注：参数为空则查询全部）")
            @Valid @RequestParam(value = "courseInfoSource", required = false) Integer courseInfoSource);


    @ApiOperation(value = "获取教室当前时间课表信息",
            nickname = "getCourseTableByRoomIdAndNowTime", notes = "小程调用",
            response = CourseTableInfoByRoomIdAndNowResource.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableInfoByRoomIdAndNowResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密验证失败", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到课程信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/coursetablebyroomidandnowtime",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableInfoByRoomIdAndNowResource>> getCourseTableByRoomIdAndNowTime(
            @NotNull @ApiParam(value = "教室Id", required = true)
            @Valid @RequestParam(value = "roomId", required = true) String roomId,
            @NotNull @ApiParam(value = "验证码（roomId-?&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "0:数据对接；1:系统录入；2:外部导入；3:自主开班；4:备课夹新建课程；5:二次排课（注：参数为空则查询全部）")
            @Valid @RequestParam(value = "courseInfoSource", required = false) Integer courseInfoSource);

    @ApiOperation(value = "接口-获取开课课程信息", nickname = "coursetablesBasicinfosGet", notes = "1、云课堂管理端项目管理使用",
            response = CourseTableBasicInfo.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableBasicInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/basicinfos",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableBasicInfo>> coursetablesBasicinfosGet(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取此开课下所有老师", nickname = "coursetableTeachersGet", notes = "1.云课堂管理端视频点播获取开课老师",
            response = CourseTableTeacherResource.class,
            responseContainer = "List", tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableTeacherResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未查询到考勤信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/teachers",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableTeacherResource>> coursetableTeachersGet(@NotNull @ApiParam(value = "课表id集合，多个使用逗号分割", required = true)
                                                                            @Valid @RequestParam(value = "courseTableIds", required = true)
                                                                                    String courseTableIds,
                                                                            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)",
                                                                                    required = true)
                                                                            @Valid @RequestParam(value = "validCode", required = true)
                                                                                    String validCode);

    @ApiOperation(value = "统计当前学期相关课程类型开课数量", nickname = "coursetableStatisticsGet", notes = "1.云课堂服务使用",
            response = StatisticsResource.class, responseContainer = "List", tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = StatisticsResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未查询到考勤信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/statistics",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<StatisticsResource>> coursetableStatisticsGet(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据学年学期统计开课课程类型的总数", nickname = "coursetableTypeStatisticsGet", notes = "1.大数据平台",
            response = StatisticsResource.class, responseContainer = "List", tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = StatisticsResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/typestatistics",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<StatisticsResource>> coursetableTypeStatisticsGet(
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-获取开课课程类型列表",
            nickname = "coursetablesCoursecategoryGet",
            notes = "1、云课堂老师端我的课程使用", response = CourseCategoryResource.class, responseContainer = "List", tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseCategoryResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/coursecategorys",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseCategoryResource>> coursetablesCoursecategorysGet(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取课表信息（实时课表）", nickname = "realtimescheduleGet",
            notes = "电子班牌调用（1：实时课表；2：巡课）", response = RealTimeSchedule.class, tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = RealTimeSchedule.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到日期信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/realtimeschedule",
            method = RequestMethod.GET)
    ResponseEntity<RealTimeSchedule> realtimescheduleGet(
            @NotNull @ApiParam(value = "教室id", required = true)
            @Valid @RequestParam(value = "roomId", required = true) String roomId,
            @NotNull @ApiParam(value = "加密验证码roomId={xxx}&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "接口-获取所有开课教学日历相关信息",
            nickname = "courseTablesTeachingschedulesPost",
            notes = "1、云课堂管理端教学任务使用",
            response = CourseTableVo.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "错误的请求", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证信息错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetables/teachingschedules",
            method = RequestMethod.POST)
    ResponseEntity<List<TeachingDetail>> courseTablesTeachingschedulesPost(
            @ApiParam(value = "教学日历查询条件", required = true)
            @Valid @RequestBody CourseTableSearch courseTableSearch,

            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "根据老师Id和学期查询班级信息", nickname = "teacherClassListGet", notes = "云课堂小程序端使用",
            response = TeachingClassVo.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingClassVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseTables/teacherclasses",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingClassVo>> teacherClassListGet(
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "老师Id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "班级名称")
            @Valid @RequestParam(value = "groupName", required = false) String groupName,
            @ApiParam(value = "允许的授课学生类型的开课")
            @Valid @RequestParam(value = "courseStudentTypes", required = false) String courseStudentTypes,
            @ApiParam(value = "是否需要区分授课学生类型") @Valid @RequestParam(value = "isNeedDistinguish", required = false)
            Boolean isNeedDistinguish);

    @ApiOperation(value = "获取实验课表统计信息", nickname = "getExperimentalCourseList"
            , notes = "调用方：1、云课堂管理端", response = ExperimentalCoursePage.class, tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentalCoursePage.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/experimentalcourse",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<ExperimentalCoursePage> getExperimentalCourseList(
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "当前页数", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页条数", required = true)
            @Valid @RequestParam(value = "row", required = true) Integer row,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程名称")
            @Valid @RequestParam(value = "courseName", required = false) String courseName);

    @ApiOperation(value = "获取实验课表统计项目信息", nickname = "getExperimentalCourseProjectList"
            , notes = "调用方：1、云课堂管理端", response = ExperimentalCourseProject.class, responseContainer = "List", tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = ExperimentalCourseProject.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/experimentalcourseproject",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<ExperimentalCourseProject>> getExperimentalCourseProjectList(
            @NotNull @ApiParam(value = "开课课表id", required = true)
            @Valid @RequestParam(value = "courseTableId", required = true) String courseTableId,
            @NotNull @ApiParam(value = "验证码：courseTableId=xxx&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "获取开课课程学期信息", nickname = "getCourseTableTermInfo"
            , notes = "调用方：1、老师web端-课程公告新增"
            , response = CourseTableTermResource.class
            , tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableTermResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "开课信息或学期信息不存在", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/term",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CourseTableTermResource> getCourseTableTermInfo(
            @NotNull @ApiParam(value = "courseTableId={xxx}&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "开课信息Id", required = true)
            @Valid @RequestParam(value = "courseTableId", required = true) String courseTableId);


    @ApiOperation(
            value = "根据老师Id和学期查询课程和上课人数",
            nickname = "getTeacherCourseAndMembers",
            notes = "小程序端使用",
            response = CourseAndMembers.class,
            responseContainer = "List",
            tags = {"CourseResources",}
    )
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseAndMembers.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseTables/teacherCourseMembers",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseAndMembers>> getTeacherCourseAndMembers(
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "老师Id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "加密验证码userId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(value = "根据学年学期获取开课信息", nickname = "getCourseInfosBySchoolYearAndTerm", notes = "期末评教对接使用",
            response = CourseInfoModel.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseInfoModel.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/terminalevaluation/courseinfos",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfoModel>> getCourseInfosBySchoolYearAndTerm(
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "学年") @Valid @RequestParam(value = "schoolYear", required = false) String schoolYear,
            @ApiParam(value = "学期") @Valid @RequestParam(value = "term", required = false) String term);

    @ApiOperation(value = "根据学年学期统计课程的总数",
            nickname = "coursetableTermscoursestatisticsGet",
            notes = "1.大数据平台",
            response = TermCourseStatisticsResource.class,
            responseContainer = "List",
            tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = TermCourseStatisticsResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/termscoursestatistics",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TermCourseStatisticsResource>> coursetableTermscoursestatisticsGet(
            @NotNull @ApiParam(value = "取前多少条", required = true)
            @Valid @RequestParam(value = "topNum", required = true) Integer topNum,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取运行学期信息",
            nickname = "coursetableTermscoursGet", notes = "1.云课堂-课程画像：课程整体数据使用",
            response = CourseTableRunningTerm.class, tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableRunningTerm.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/termscours",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CourseTableRunningTerm> getCourseTableStatisticsByStartClass(
            @NotNull @ApiParam(value = "课程ID", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取课程开课所属学院列表", nickname = "coursetableCollegesGet",
            notes = "1.听查课端", response = CourseTableCollegeResource.class, responseContainer = "List", tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableCollegeResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未查询到学院信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/colleges",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableCollegeResource>> coursetableCollegesGet(
            @NotNull @ApiParam(value = "课程id集合，多个使用逗号分割", required = true)
            @Valid @RequestParam(value = "courseIds", required = true) String courseIds,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "获取运行学期信息（新）",
            nickname = "coursetableTermscoursGet", notes = "1.云课堂-课程画像：课程整体数据使用",
            response = CourseTableRunningTerm.class, tags = {"CourseTable",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableRunningTerm.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetable/operationterms",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TermResource>> getCourseTableOperationTerms(
            @NotNull @ApiParam(value = "课程ID", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据老师Ids和课程ids和学期查询课表信息", nickname = "getAssistantTeacherCourseTableList",
            notes = "云课堂学生端助教课程使用", response = AssistantCourseVo.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = AssistantCourseVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/assistantcourse/teachercourselist",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<List<AssistantCourseVo>> getAssistantTeacherCourseTableList(
            @NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "助教课程入参", required = true)
            @Valid @RequestBody AssistantCourseParam assistantCourseParam);


    @ApiOperation(value = "根据学年学期获取老师课表课程及结构", nickname = "getTeacherCourseTableCourseStructures",
            notes = "1、互动课堂", response = TeachingCourseInfo.class, responseContainer = "List", tags={ "CourseTableResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = TeachingCourseInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常，接受传入的参数类型不正确、必填参数未填写", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "传入的加密参数未通过验证", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "资源路径参数对应的资源未找到", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/coursetables/coursestructures",
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingCourseInfo>> getTeacherCourseTableCourseStructures(
            @NotNull @ApiParam(value = "学年", required = true)
            @Valid @RequestParam(value = "schoolYear", required = true) String schoolYear,
            @NotNull @ApiParam(value = "学期", required = true)
            @Valid @RequestParam(value = "term", required = true) Integer term,
            @NotNull @ApiParam(value = "老师Id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @NotNull @ApiParam(value = "验证码teacherId=?&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据老师Id查询当前学期查询开课详细信息", nickname = "getTeacherCourseInfos", notes = "云课堂前端使用",
            response = TeacherCourseResource.class, responseContainer = "List", tags={ "CourseTableResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeacherCourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/coursetables/teachercourseinfos",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<TeacherCourseResource>> getTeacherCourseInfos(
            @NotNull @ApiParam(value = "老师Id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @NotNull @ApiParam(value = "加密验证码userId=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "允许的授课学生类型的开课")
            @Valid @RequestParam(value = "courseStudentTypes", required = false) String courseStudentTypes,
            @ApiParam(value = "是否需要区分授课学生类型")
            @Valid @RequestParam(value = "isNeedDistinguish", required = false) Boolean isNeedDistinguish);


    @ApiOperation(value = "获取教师课表信息（日课表，周课表公用）", nickname = "getTeacherCourseTablesDayOrWeek", notes = "小程序调用",
            response = CourseTableDate.class, responseContainer = "List", tags={ "CourseTableResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDate.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到日期信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teacher/coursetablesdayorweek",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDate>> getTeacherCourseTablesDayOrWeek(@NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
                                                                          @Valid @RequestParam(value = "validCode", required = true)
                                                                          String validCode,
                                                                          @ApiParam(value = "查询课表条件集合" ,required=true )
                                                                          @Valid @RequestBody CourseParms courseparms);



    @ApiOperation(value = "获取学生课表信息（日课表，周课表公用）", nickname = "getStudentCourseTablesDayOrWeek", notes = "小程序调用",
            response = CourseTableDate.class, responseContainer = "List", tags={ "CourseTableResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDate.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到日期信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/student/coursetablesdayorweek",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDate>> getStudentCourseTablesDayOrWeek(@NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
                                                                          @Valid @RequestParam(value = "validCode", required = true)
                                                                          String validCode,
                                                                          @ApiParam(value = "查询课表条件集合" ,required=true )
                                                                          @Valid @RequestBody CourseParms courseparms);

    @ApiOperation(
            value = "根据学院id查询所有的开课ID", nickname = "getCourseTableIdsByCollegeIds",
            notes = "学业支持：挂科总览按开课学院汇总使用", response = String.class,
            responseContainer = "List", tags={ "CourseTableResource", }
    )
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = String.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/getcoursetableidsbycollegeids",
            method = RequestMethod.POST)
    ResponseEntity<List<String>> getCourseTableIdsByCollegeIds(
            @ApiParam(value = "学院ID列表" ,required=true )  @Valid @RequestBody List<String> collegeIds,
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );

    @ApiOperation(
            value = "根据学院id查询所有的开课信息", nickname = "getCourseTableInfoByCollegeIds",
            notes = "学业支持：挂科总览按开课学院汇总使用", response = CourseTableIdAndNameInfo.class,
            responseContainer = "List", tags={ "CourseTableResource", }
    )
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableIdAndNameInfo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/getcoursetableinfobycollegeids",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableIdAndNameInfo>> getCourseTableInfoByCollegeIds(
            @ApiParam(value = "学院ID列表" ,required=true )  @Valid @RequestBody List<String> collegeIds,
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );
    @ApiOperation(value = "根据学年学期获取满足评教的开课信息", nickname = "getCourseInfoCodes",
            notes = "期末评教对接使用", response = CourseInfoCode.class, responseContainer = "List", tags={ "CourseTableResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseInfoCode.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/terminalevaluation/courseinfocodes",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfoCode>> getCourseInfoCodes(
            @NotNull @ApiParam(value = "课次数", required = true)
            @Valid @RequestParam(value = "classTime", required = true) Integer classTime,
            @NotNull @ApiParam(value = "课次结课状态", required = true)
            @Valid @RequestParam(value = "courseCompletionStatus", required = true) Boolean courseCompletionStatus,
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "学年") @Valid @RequestParam(value = "schoolYear", required = false) String schoolYear,
            @ApiParam(value = "学期") @Valid @RequestParam(value = "term", required = false) String term);

}



