/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.coursetables;

import com.lztech.site.resource.coursetable.CourseSegmentResource;
import com.lztech.site.resource.coursetable.CourseTableDetailParam;
import com.lztech.site.resource.coursetable.CourseTypeCountResource;
import com.lztech.site.resource.coursetabledetail.CourseTableDetailResource;
import com.lztech.site.viewmodel.coursetable.OccupancyLabResource;
import com.lztech.site.viewmodel.coursetable.RoomResource;
import com.lztech.site.viewmodel.coursetabledetail.*;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-17T08:59:38.735Z")

@Api(value = "coursetabledetail", description = "the coursetabledetail API")

public interface CoursetabledetailApi {

    @ApiOperation(value = "获取课表信息", nickname = "coursetabledetailPost", notes = "查询课表信息（综合查询）",
            response = CourseSegmentResource.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseSegmentResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "解密验证失败", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/coursetabledetail",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<CourseSegmentResource> getCourseTableDetail(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课表综合查询信息", required = true)
            @Valid @RequestBody CourseTableDetailParam courseTableDetailParam);

    @ApiOperation(value = "获取课表总数", nickname = "coursetableCoursetypecountPost", notes = "获取课表总数（综合查询）",
            response = CourseTypeCountResource.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTypeCountResource.class),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密验证失败"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/coursetable/coursetypecount",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<CourseTypeCountResource> coursetableCoursetypecountPost(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "获取课表总数综合查询", required = true)
            @Valid @RequestBody CourseTableDetailParam courseTableDetailParam);


    @ApiOperation(value = "根据课程统计正在上课的课表", nickname = "coursetabledetailCourseInclassGet",
            notes = "1.云课堂在线巡课根据课程统计正在上课的课表", response = CourseCourseTableDetailResource.class,
            responseContainer = "List", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseCourseTableDetailResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/coursetabledetail/course/inclass",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseCourseTableDetailResource>> coursetabledetailCourseInclassGet(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "开课类型")
            @Valid @RequestParam(value = "courseStudentTypeIds", required = false) String courseStudentTypeIds,
            @ApiParam(value = "查询条件 教室/课程/教师 多个使用空格隔开")
            @Valid @RequestParam(value = "searchParams", required = false) String searchParams,
            @ApiParam(value = "课程Id,多个以‘，’分割")
            @Valid @RequestParam(value = "courseIds", required = false) String courseIds,
            @ApiParam(value = "学院id,多个以‘，’分割")
            @Valid @RequestParam(value = "collegeIds", required = false) String collegeIds,
            @ApiParam(value = "是否区分本硕信息")
            @Valid @RequestParam(value = "isDistinguishCourseStudentType", required = false) String isDistinguishCourseStudentType);


    @ApiOperation(value = "根据课程统计正在上课的课表", nickname = "coursetabledetailCourseInclassPost",
            notes = "1.云课堂在线巡课根据课程统计正在上课的课表", response = CourseCourseTableDetailResource.class,
            responseContainer = "List", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseCourseTableDetailResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/coursetabledetail/course/inclassPost",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseCourseTableDetailResource>> coursetabledetailCourseInclassPost(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询条件 教室/课程/教师 多个使用空格隔开")
            @Valid @RequestParam(value = "searchParams", required = false) String searchParams,
            @ApiParam(value = "课程Id,多个以‘，’分割")
            @Valid String courseIds,
            @ApiParam(value = "学院id,多个以‘，’分割")
            @Valid String collegeIds);


    @ApiOperation(value = "分页获取正在上课的课表", nickname = "coursetabledetailInclassPagePost",
            notes = "1.云课堂在线巡课分页获取正在上课的课表", response = CourseTableDetailPageResource.class,
            tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailPageResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/coursetabledetail/inclass/page",
            method = RequestMethod.POST)
    ResponseEntity<CourseTableDetailPageResource> coursetabledetailInclassPagePost(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课表巡课搜索信息", required = true)
            @Valid @RequestBody InclassPageVo inclassPageVo);

    @ApiOperation(value = "获取教室下正在上课的课表信息", nickname = "roomIdCoursetabledetailGet",
            notes = "1.云课堂在线巡课获取教室下正在上课的课表信息", response =
            CourseTableDetailResource.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/room/{id}/coursetabledetail",
            method = RequestMethod.GET)
    ResponseEntity<CourseTableDetailResource> roomIdCoursetabledetailGet(@NotNull
                                                                         @ApiParam(value = "id={}加密验证码（&signKey=123123）", required = true)
                                                                         @Valid @RequestParam(value = "validCode", required = true)
                                                                                 String validCode,
                                                                         @ApiParam(value = "教室id", required = true) @PathVariable("id")
                                                                                 String id,
                                                                         @ApiParam(value = "是否区分本硕信息") @Valid
                                                                         @RequestParam(value = "isDistinguishCourseStudentType", required = false)
                                                                                 String isDistinguishCourseStudentType,
                                                                         @ApiParam(value = "授课学生类型") @Valid
                                                                         @RequestParam(value = "courseStudentTypeIds", required = false)
                                                                                 String courseStudentTypeIds);

    @ApiOperation(value = "获取课程占用实验室信息", nickname = "coursetablesCourseoccupancylabGet",
            notes = "teaching项目使用", response = RoomResource.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功，返回实验室信息列表", response = RoomResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "传入的加密参数未通过验证", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "资源路径参数对应的资源未找到", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "文件操作IO异常等")})
    @RequestMapping(value = "/v1/coursetables/courseoccupancylablist",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<RoomResource>> getCourseOccupancyLabList(
            @NotNull @ApiParam(value = "课程日期（格式：yyyy-MM-dd；多个用“,”隔开，如：2020-08-09,2020-08-10）", required = true)
            @Valid @RequestParam(value = "courseDates", required = true) String courseDates,
            @NotNull @ApiParam(value = "课程节次（多个用“,”隔开，如：1,2,3）", required = true)
            @Valid @RequestParam(value = "courseSegments", required = true) String courseSegments,
            @NotNull @ApiParam(value = "courseSegments=XXX&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    //region 获取当天课表明细信息
    @ApiOperation(value = "获取当天课表明细信息", nickname = "coursetabledetailNowdaycoursetabledetailsGet",
            notes = "上墙软件查询教室设备使用（有课教室与无课教室）", response = NowDayCourseTableDetail.class,
            responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = NowDayCourseTableDetail.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "v1/coursetabledetail/nowdaycoursetabledetails",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<NowDayCourseTableDetail>> coursetabledetailNowdaycoursetabledetailsGet(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true) @Valid
            @RequestParam(value = "validCode", required = true)
                    String validCode);
    //endregion

    @ApiOperation(value = "获取教室占用课表信息", nickname = "coursetabledetailOccupancycoursetabledetailGet", notes = "1.自助终端小程序教室查询内部使用",
            response = OccupancyResource.class, tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = OccupancyResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到教室占用课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/occupancycoursetabledetail",
            method = RequestMethod.GET)
    ResponseEntity<OccupancyResource> coursetabledetailOccupancycoursetabledetailGet(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "节次", required = true)
            @Valid @RequestParam(value = "segment", required = true) Integer segment,
            @NotNull @ApiParam(value = "上课日期", required = true)
            @Valid @RequestParam(value = "courseDate", required = true) String courseDate,
            @NotNull @ApiParam(value = "教室id", required = true) @Valid @RequestParam(value = "roomId", required = true) String roomId);

    @ApiOperation(value = "接口-根据上课时间获取课表信息", nickname = "coursetabledetailSegmentcoursetableresourceGet",
            notes = "1.信息发布服务更新教室占用内部使用", response = SegmentCourseTableResource.class, responseContainer = "List", tags = {"CourseTableDetails",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = SegmentCourseTableResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/segmentcoursetableresource",
            method = RequestMethod.GET)
    ResponseEntity<List<SegmentCourseTableResource>> coursetabledetailSegmentcoursetableresourceGet(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "上课日期", required = true)
            @Valid @RequestParam(value = "courseDate", required = true) String courseDate);

    @ApiOperation(value = "查询正在上课的课表信息", nickname = "getCourseTableDetailInClassList",
            notes = "调用方： 1.小程序——云课堂在线巡课", response = CourseTableDetailInClassResource.class,
            responseContainer = "List", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailInClassResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/course/inclass",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDetailInClassResource>> getCourseTableDetailInClassList(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询字段——课程名称或老师名称 模糊查询")
            @Valid @RequestParam(value = "courseNameOrTeacherName", required = false) String courseNameOrTeacherName,
            @ApiParam(value = "课程Id和学院Id集合")
            @Valid @RequestBody CourseIdAndCollegeIdQuery courseIdAndCollegeIdQuery);

    @ApiOperation(value = "根据老师姓名精确查询本学期正在上课和已经上过的课程信息",
            nickname = "getCourseandgroupByTeacherId", notes = "1.云课堂管理端-督导听课使用",
            response = CourseTableSuperviseVo.class, responseContainer = "List", tags = {"CourseTableDetail",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableSuperviseVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/courseandgroup",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseTableSuperviseVo>> getCourseandgroupByTeacherId(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "老师Id", required = true)
            @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
            @ApiParam(value = "开课类型")
            @Valid @RequestParam(value = "courseStudentTypeIds", required = false) String courseStudentTypeIds,
            @ApiParam(value = "是否区分本硕信息")
            @Valid @RequestParam(value = "isDistinguishCourseStudentType", required = false) String isDistinguishCourseStudentType,
            @ApiParam(value = "是否需要过滤思政课")
            @Valid @RequestParam(value = "isNeedFilterPoliticalCourse", required = false) Boolean isNeedFilterPoliticalCourse);


    @ApiOperation(value = "查询能够直播的课表信息", nickname = "coursetabledetailLivePost",
            notes = "1.云课堂听查课端-在线巡课使用", response = CourseTableDetailPageResource.class, tags = {"CourseTableDetail",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDetailPageResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/live",
            method = RequestMethod.POST)
    ResponseEntity<CourseTableDetailPageResource> coursetabledetailLivePost(
            @ApiParam(value = "在线巡课查询条件", required = true)
            @Valid @RequestBody CourseTableDetailPageRequest courseTableDetailPageRequest,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "学院Id", required = false)
            @Valid @RequestParam(value = "collegeId", required = false) String collegeId,
            @ApiParam(value = "学院名称", required = false)
            @Valid @RequestParam(value = "collegeName", required = false) String collegeName);


    @ApiOperation(value = "根据行政班查询能够直播的课表信息", nickname = "getLiveCourseTableDetailListByAdministrativeClassIdList",
            notes = "1.云课堂听查课端-辅导员巡课", response = CourseTableDetailPageResource.class, tags = {"CourseTableDetail",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTableDetailPageResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/administrativeclass/live",
            method = RequestMethod.POST)
    ResponseEntity<CourseTableDetailPageResource> getLiveCourseTableDetailListByAdministrativeClassIdList(
            @ApiParam(value = "辅导员巡课查询条件", required = true)
            @Valid @RequestBody CourseTableDetailAdministrativeClassPageRequest pageRequest,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode
    );


    @ApiOperation(value = "根据课表详情ID查询课程信息的接口", nickname = "getCourseByCourseTableDetailId", notes = "调用方： 1.轻课堂 2.AI课堂预警",
            response = CoursetableResourceVo.class, tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CoursetableResourceVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class)})
    @RequestMapping(value = "/coursetable/{courseTableDetailId}/coursetabledetail",
            method = RequestMethod.GET)
    ResponseEntity<CoursetableResourceVo> getCourseByCourseTableDetailId(
            @NotNull @ApiParam(value = "验证码：courseTableDetailId={}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课表详情ID", required = true)
            @PathVariable("courseTableDetailId") String courseTableDetailId);


    @ApiOperation(value = "分页获取各个来源正在上课的课表(新接口)",
            nickname = "coursetabledetailInclassDetailsGet",
            notes = "1.江中医大屏使用", response = CourseTableDetailPageModel.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailPageModel.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "v1/coursetabledetail/inclass/details",
            method = RequestMethod.POST)
    ResponseEntity<CourseTableDetailPageModel> coursetabledetailInclassDetailsGet(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课表巡课搜索信息", required = true)
            @Valid @RequestBody InclassModelRequest inclassModelRequest
    );


    @ApiOperation(value = "获取教室下正在上课的课表信息", nickname = "roomIdCoursetabledetailinfoGet",
            notes = "1.江中医大屏使用", response =
            CourseTableDetailResource.class, tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/room/{id}/coursetabledetailinfo",
            method = RequestMethod.GET)
    ResponseEntity<CourseTableDetailResource> roomIdCoursetabledetailinfoGet(@NotNull
                                                                             @ApiParam(value = "id={}加密验证码（&signKey=123123）", required = true)
                                                                             @Valid @RequestParam(value = "validCode", required = true)
                                                                                     String validCode,
                                                                             @NotNull
                                                                             @ApiParam(value = "数据来源，多个使用逗号隔开", required = true)
                                                                             @Valid @RequestParam(value = "sources", required = true)
                                                                                     String sources,
                                                                             @ApiParam(value = "教室id", required = true) @PathVariable("id")
                                                                                     String id);


    @ApiOperation(value = "获取指定日期的课表", nickname = "getExpertAuthorizationScheduleResource", notes = "1.云课堂管理端-专家听课人员维护调用",
            response = ExpertAuthorizationChildListOne.class, responseContainer = "List", tags={ "CourseTableDetailResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = ExpertAuthorizationChildListOne.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到正在上课的课表信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/coursetabledetail/date",
            method = RequestMethod.POST)
    ResponseEntity<List<ExpertAuthorizationChildListOne>> getExpertAuthorizationScheduleResource(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课表巡课搜索信息" ,required=true )
            @Valid @RequestBody ExpertAuthorizationScheduleParam expertAuthorizationScheduleParam);


    @ApiOperation(value = "根据条件获取正在直播或点播的课表信息",
            nickname = "getLiveCourseTableDetailList",
            notes = "1.云课堂听查课专家听课使用", response = LiveScheduleResource.class,
            responseContainer = "List", tags={ "CourseTableDetail", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = LiveScheduleResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/livecoursetabledetail",
            method = RequestMethod.POST)
    ResponseEntity<List<LiveScheduleResource>> getLiveCourseTableDetailList(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "获取正在直播或点播课表信息入参" ,required=true )
            @Valid @RequestBody LiveCourseTableDetailParam liveCourseTableDetailParam);

    @ApiOperation(value = "根据条件获取正在直播的课程信息",
            nickname = "getLiveCourseList",
            notes = "1.云课堂听查课专家听课使用", response = LiveScheduleResourcePageVo.class,
            tags = {"CourseTableDetail",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = LiveScheduleResourcePageVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/liveCourses",
            method = RequestMethod.POST)
    ResponseEntity<LiveScheduleResourcePageVo> getLiveCourseList(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "获取正在直播课程信息入参", required = true)
            @Valid @RequestBody LiveCourseParam liveCourseParam);

    @ApiOperation(value = "根据条件获取今日正在上课和还未上课的课表信息", nickname = "getLiveCourseTablePage", notes = "1.云课堂听查课专家听课听课预告使用",
            response = LessonPreviewPage.class, tags={ "CourseTableDetail", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = LessonPreviewPage.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/livecoursetables",
            method = RequestMethod.POST)
    ResponseEntity<LessonPreviewPage> getLiveCourseTablePage(
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "获取信息入参" ,required=true )
            @Valid @RequestBody LessonPreviewParam lessonPreviewParam);

    @ApiOperation(value = "根据上课日期、节次获取课表占用实验室", nickname = "getCourseTableDetailOccupancyLabList",
            notes = "使用方：teachinglaboratoryapi项目使用", response = OccupancyLabResource.class, responseContainer = "List",
            tags={ "CourseTableResource", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功，返回占用实验室id列表", response = OccupancyLabResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码不正确", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/v1/coursetables/coursetabledetailoccupancylablist",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<OccupancyLabResource>> getCourseTableDetailOccupancyLabList(
            @NotNull @ApiParam(value = "上课日期（格式：yyyy-MM-dd）", required = true)
            @Valid @RequestParam(value = "courseDate", required = true) String courseDate,
            @NotNull @ApiParam(value = "课程节次（多个用“,”隔开，如：1,2,3）", required = true)
            @Valid @RequestParam(value = "courseSegments", required = true) String courseSegments,
            @NotNull @ApiParam(value = "courseDate={}&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "查询正在上课的课表明细信息", nickname = "getCourseTableDetailInClassDetailList",
            notes = "调用方： 1.小程序——云课堂在线巡课", response = CourseTableDetailInClassResource.class,
            responseContainer = "List", tags = {"CourseTableDetailResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = CourseTableDetailInClassResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursetabledetail/course/inclassdetails",
            method = RequestMethod.POST)
    ResponseEntity<List<CourseTableDetailInClassResource>> getCourseTableDetailInClassDetailList(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "查询字段——课程名称或老师名称 模糊查询")
            @Valid @RequestParam(value = "courseNameOrTeacherName", required = false) String courseNameOrTeacherName,
            @ApiParam(value = "课程Id和学院Id集合")
            @Valid @RequestBody CourseIdAndCollegeIdQuery courseIdAndCollegeIdQuery);

}
