/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.coursetables;

import com.lztech.site.viewmodel.coursetable.RealtimeSegment;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2025-10-10T14:19:44.442+08:00")

@Api(value = "roomrealtimesegment", description = "the roomrealtimesegment API")
public interface RoomrealtimesegmentApi {

    @ApiOperation(value = "根据教室id获取实时节次列表", nickname = "getRealtimeSegmentsByRoomId", notes = "使用方：1、AI课堂助教",
            response = RealtimeSegment.class, responseContainer = "List", tags = {"CourseTableResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = RealtimeSegment.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/roomrealtimesegment",
            method = RequestMethod.GET)
    ResponseEntity<List<RealtimeSegment>> getRealtimeSegmentsByRoomId(
            @NotNull @ApiParam(value = "教室id", required = true)
            @Valid @RequestParam(value = "roomId", required = true) String roomId,
            @NotNull @ApiParam(value = "加密验证码roomId={xxx}&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
