/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.aiknowledgebase;

import com.lztech.site.viewmodel.aiknowledgebase.AIKnowledgeBaseParam;
import com.lztech.site.viewmodel.aiknowledgebase.AIKnowledgeBaseVo;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-20T08:30:00.298Z")

@Api(value = "aiknowledgebase", description = "the aiknowledgebase API")
@RequestMapping(value = "/v1")
public interface AIKnowledgeBaseApi {

    @ApiOperation(value = "接口-根据条件获取AI知识库数据(课程教材、课件资源)",
            nickname = "getAIKnowledgeBaseList", notes = "1、内部调用", response = AIKnowledgeBaseVo.class,
            responseContainer = "List", tags = {"AIKnowledgeBase",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = AIKnowledgeBaseVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/aiknowledgebase/list",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<List<AIKnowledgeBaseVo>> getAIKnowledgeBaseList(
            @NotNull @ApiParam(value = "&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "知识库查询条件", required = true)
            @Valid @RequestBody AIKnowledgeBaseParam aiKnowledgeBaseParam
    );


}
