/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseteachingpackage;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.teachingpackage.CourseTeachingPackagePageResource;
import com.lztech.site.viewmodel.teachingpackage.CourseTeachingPackageVo;
import com.lztech.site.viewmodel.teachingpackage.QuoteTeachingPackageVo;
import com.lztech.site.viewmodel.teachingpackage.TeachingPackageCourseVersionResource;
import com.lztech.site.viewmodel.teachingpackage.TeachingPackageVo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-03-24T05:48:54.282Z")

@Validated
@Api(value = "teachingpackage", description = "the teachingpackage API")
@RequestMapping(value = "/v1")
public interface TeachingpackageApi {

    @ApiOperation(value = "发布课程包", nickname = "addTeachingPackage", notes = "1.云课堂老师端-课程建设-教学内容-发布课程包使用", tags={ "CourseTeachingPackage", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功"),
        @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
        @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
        @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
        @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
        @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage",
        method = RequestMethod.POST)
    ResponseEntity<Void> addTeachingPackage(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "" ,required=true )  @Valid @RequestBody CourseTeachingPackageVo teachingPackageVo);


    @ApiOperation(value = "根据名称查找课程包", nickname = "getTeachingPackageByName", notes = "1.云课堂老师端-课程建设-教学内容-引用课程包使用",
            response = TeachingPackageVo.class, responseContainer = "List", tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingPackageVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/packages",
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingPackageVo>> getTeachingPackageByName(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程名称", required = true)
            @Valid @RequestParam(value = "courseName", required = true) String courseName,
            @NotNull @ApiParam(value = "课程Id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "用户Id", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId);

    @ApiOperation(value = "查找教学包版本", nickname = "getTeachingPackageVersion", notes = "1.云课堂老师端-课程建设-教学内容-发布课程包使用",
            response = TeachingPackageCourseVersionResource.class, responseContainer = "List", tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingPackageCourseVersionResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/version",
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingPackageCourseVersionResource>> getTeachingPackageVersion(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程ID", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "用户ID", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId);

    @ApiOperation(value = "教学包列表", nickname = "getTeachingPackageList",
            notes = "1.云课堂老师端-课程建设-教学内容-教学包列表",
            response = CourseTeachingPackagePageResource.class, tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTeachingPackagePageResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/list",
            method = RequestMethod.POST)
    ResponseEntity<CourseTeachingPackagePageResource> getTeachingPackageList(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程Ids" ,required=true )
            @Valid @RequestBody List<String> courseIds,
            @NotNull @ApiParam(value = "当前页", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true)
            @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize);



    @ApiOperation(value = "教学包详情", nickname = "getTeachingPackageDetail",
            notes = "1.云课堂老师端-课程建设-教学内容-教学包列表", response = TeachingPackageVo.class, tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingPackageVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/{courseId}/detail",
            method = RequestMethod.GET)
    ResponseEntity<TeachingPackageVo> getTeachingPackageDetail(
            @NotNull @ApiParam(value = "验证码（courseId=?&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "用户ID", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @ApiParam(value = "课程Id",required=true) @PathVariable("courseId") String courseId);




    @ApiOperation(value = "引用课程包", nickname = "quoteTeachingPackage", notes = "1.云课堂老师端-课程建设-教学内容-引用课程包使用",
            tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/packages/quote",
            method = RequestMethod.POST)
    ResponseEntity<Void> quoteTeachingPackage(
            @NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "" ,required=true )  @Valid @RequestBody QuoteTeachingPackageVo quoteTeachingPackage);

    @ApiOperation(value = "个人空间教学包列表", nickname = "getTeachingPackageMyList", notes = "1.云课堂老师端-个人空间-",
            response = CourseTeachingPackagePageResource.class, tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseTeachingPackagePageResource.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/{userId}/mylist",
            method = RequestMethod.GET)
    ResponseEntity<CourseTeachingPackagePageResource> getTeachingPackageMyList(
            @NotNull @ApiParam(value = "验证码（userId=?&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "用户Id",required=true)
            @PathVariable("userId") String userId,
            @NotNull @ApiParam(value = "当前页", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true)
            @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize);



    @ApiOperation(value = "个人空间教学包详情", nickname = "getTeachingPackageMyDetail", notes = "1.云课堂老师端-个人空间-教学包详情",
            response = TeachingPackageVo.class, tags={ "CourseTeachingPackage", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingPackageVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/teachingpackage/{courseId}/mydetail",
            method = RequestMethod.GET)
    ResponseEntity<TeachingPackageVo> getTeachingPackageMyDetail(
            @NotNull @ApiParam(value = "验证码（courseId=?&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "用户ID", required = true)
            @Valid @RequestParam(value = "userId", required = true) String userId,
            @ApiParam(value = "课程Id",required=true)
            @PathVariable("courseId") String courseId);



}
