-- 创建课程知识图谱功能日志
CREATE TABLE `tb_course_knowledge_graph_action_log`  (
                                                         `id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                                                         `course_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '课程id',
                                                         `course_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '课程名称',
                                                         `course_knowledge_graph_domain_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '课程知识图谱id',
                                                         `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '模块标题',
                                                         `business_type`  int(11) NULL DEFAULT NULL COMMENT '业务类型',
                                                         `old_knowledge_node_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧知识点id',
                                                         `old_knowledge_node_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧知识点名称',
                                                         `old_knowledge_node_level_index` int(11) NULL DEFAULT NULL COMMENT '旧知识点层级编号',
                                                         `old_knowledge_node_level_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧知识点层级名称',
                                                         `old_knowledge_node_data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧知识点数据id',
                                                         `old_knowledge_node_data_content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '旧知识点数据内容',
                                                         `old_relationship_knowledge_node_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧关联知识点id(删除关系使用)',
                                                         `old_relationship_knowledge_node_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧关联知识点名称(删除关系使用)',
                                                         `old_relationship_knowledge_node_level_index` int(11) NULL DEFAULT NULL COMMENT '旧关联知识点层级编号(删除关系使用)',
                                                         `old_relationship_knowledge_node_level_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧关联知识点层级名称(删除关系使用)',
                                                         `now_knowledge_node_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧知识点id',
                                                         `now_knowledge_node_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '旧知识点名称',
                                                         `now_knowledge_node_level_index` int(11) NULL DEFAULT NULL COMMENT '新知识点层级编号',
                                                         `now_knowledge_node_level_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '新知识点层级名称',
                                                         `now_relationship_knowledge_node_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '新关联知识点id(新增关系使用)',
                                                         `now_relationship_knowledge_node_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '新关联知识点名称(新增关系使用)',
                                                         `now_relationship_knowledge_node_level_index` int(11) NULL DEFAULT NULL COMMENT '新关联知识点层级编号(新增关系使用)',
                                                         `now_relationship_knowledge_node_level_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '新关联知识点层级名称(新增关系使用)',
                                                         `now_knowledge_node_data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '新知识点数据id',
                                                         `now_knowledge_node_data_content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '新知识点数据内容',
                                                         `operator_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作人id',
                                                         `operator_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作人工号',
                                                         `operator_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作人名称',
                                                         `operator_ip` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作人所在ip',
                                                         `detail_content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '详细内容',
                                                         `operator_time` datetime(0) NULL DEFAULT NULL COMMENT '操作时间',
                                                         PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;