-- 新增 课程成绩表
CREATE TABLE `tb_student_score`
(
    `id`                      varchar(255) NOT NULL,
    `record_id`               varchar(255)  DEFAULT NULL,
    `student_no`              varchar(255)  DEFAULT NULL,
    `term_id`                 varchar(255)  DEFAULT NULL,
    `teaching_class_id`       varchar(255)  DEFAULT NULL,
    `course_code`             varchar(255)  DEFAULT NULL,
    `exam_date`               date          DEFAULT NULL,
    `exam_type`               varchar(255)  DEFAULT NULL,
    `study_mode`              varchar(255)  DEFAULT NULL,
    `usual_score`             decimal(5, 2) DEFAULT NULL,
    `midterm_score`           decimal(5, 2) DEFAULT NULL,
    `final_exam_score`        decimal(5, 2) DEFAULT NULL,
    `experiment_score`        decimal(5, 2) DEFAULT NULL,
    `practical_score`         decimal(5, 2) DEFAULT NULL,
    `total_score`             decimal(5, 2) DEFAULT NULL,
    `course_grade`            varchar(255)  DEFAULT NULL,
    `credit`                  decimal(5, 2) DEFAULT NULL,
    `grade_point`             decimal(5, 2) DEFAULT NULL,
    `is_pass`                 tinyint(1)    DEFAULT NULL,
    `is_included_in_gpa`      tinyint(1)    DEFAULT NULL,
    `is_merit_point`          tinyint(1)    DEFAULT NULL,
    `score_type`              varchar(255)  DEFAULT NULL,
    `study_type`              varchar(255)  DEFAULT NULL,
    `course_sequence_no`      varchar(255)  DEFAULT NULL,
    `gpa`                     decimal(5, 2) DEFAULT NULL,
    `remark`                  text,
    `course_nature`           varchar(255)  DEFAULT NULL,
    `exam_type_name`          varchar(255)  DEFAULT NULL,
    `study_mode_name`         varchar(255)  DEFAULT NULL,
    `is_pass_name`            varchar(255)  DEFAULT NULL,
    `is_included_in_gpa_name` varchar(255)  DEFAULT NULL,
    `is_merit_point_name`     varchar(255)  DEFAULT NULL,
    `score_type_name`         varchar(255)  DEFAULT NULL,
    `study_type_name`         varchar(255)  DEFAULT NULL,
    `course_nature_name`      varchar(255)  DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_score_course_code` (`course_code`),
    KEY `idx_score_student_no` (`student_no`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  ROW_FORMAT = DYNAMIC;
