CREATE TABLE `tb_knowledge` (
                                `id` varchar(255) NOT NULL,
                                `create_time` datetime DEFAULT NULL,
                                `creator_id` varchar(255)  DEFAULT NULL,
                                `creator_name` varchar(255)  DEFAULT NULL,
                                `modifier_id` varchar(255)  DEFAULT NULL,
                                `modifier_name` varchar(255)  DEFAULT NULL,
                                `modify_time` datetime DEFAULT NULL,
                                `course_id` varchar(255) DEFAULT NULL,
                                `course_code` varchar(255) DEFAULT NULL,
                                `course_name` varchar(255) DEFAULT NULL,
                                `teacher_id` varchar(255) DEFAULT NULL, 
                                `teacher_name` varchar(255) DEFAULT NULL,
                                `data_source` int DEFAULT NULL,
                                `data_id` varchar(255) DEFAULT NULL,
                                `data_inner_url` varchar(255) DEFAULT NULL,
                                `data_outer_url` varchar(255) DEFAULT NULL,
                                `data_path` varchar(2048) DEFAULT NULL,
                                `data_type` varchar(64) DEFAULT NULL,
                                `is_delete` bit(1) DEFAULT b'1',
                                PRIMARY KEY (`id`),
                                KEY `data_id_index` (`data_id`) USING BTREE,
                                KEY `course_index` (`course_id`) USING BTREE,
                                KEY `teacher_index` (`teacher_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;