/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.courseresources;

import com.lztech.site.resource.college.CollegeCourseResource;
import com.lztech.site.resource.course.*;
import com.lztech.site.viewmodel.courseconstruction.CourseResourceKnowledgePointVo;
import com.lztech.site.viewmodel.courseresource.CourseInfoResourceVo;
import com.lztech.site.viewmodel.courseresource.FoundationCoursePageVo;
import com.lztech.site.viewmodel.courseresource.TestPaperResource;
import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-10T10:07:17.884Z")

@Api(value = "courseResources", description = "the courseResources API")
@RequestMapping(value = "/v1")
public interface CourseResourcesApi {

    @ApiOperation(value = "", nickname = "getCourseResourcePage", notes = "查询课程信息", response = CourseResourcesPageVo.class,
            tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = CourseResourcesPageVo.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseResources",
            method = RequestMethod.GET)
    ResponseEntity<CourseResourcesPageVo> getCourseResourcePage(@NotNull @ApiParam(value = "MD5加密验证字符串", required = true)
                                                                @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                                @NotNull @ApiParam(value = "当前页", required = true)
                                                                @Valid @RequestParam(value = "page", required = true) Integer page,
                                                                @NotNull @ApiParam(value = "每页个数", required = true)
                                                                @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize,
                                                                @ApiParam(value = "学院Id")
                                                                @Valid @RequestParam(value = "collegeId", required = false) String collegeId,
                                                                @ApiParam(value = "课程名称")
                                                                @Valid @RequestParam(value = "courseName", required = false) String courseName,
                                                                @ApiParam(value = "课程来源 0：数据对接；1：课程管理老师新建")
                                                                @Valid @RequestParam(value = "courseSource", required = false) Integer courseSource);

    //region 根据课程名称查询课程信息
    @ApiOperation(value = "根据课程名称查询课程信息", nickname = "courseresourcesCourseinforesourcesGet",
            notes = "云课堂管理端使用", response = CourseInfoResource.class, responseContainer = "List", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfoResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常，接受传入的参数类型不正确、必填参数未填写"),
            @ApiResponse(code = 403, message = "传入的加密参数未通过验证"),
            @ApiResponse(code = 404, message = "资源路径参数对应的资源未找到"),
            @ApiResponse(code = 500, message = "文件操作IO异常等")})
    @RequestMapping(value = "/courseresources/courseinforesources",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfoResource>> courseresourcesCourseinforesourcesGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串（&signKey=123123）", required = true) @Valid
            @RequestParam(value = "validCode", required = true)
            String validCode,
            @NotNull @ApiParam(value = "课程名称", required = true) @Valid
            @RequestParam(value = "courseName", required = true)
            String courseName);

    //endregion
    @ApiOperation(value = "获取所有课程信息，教研室管理、权限课程数据对接调用", nickname = "allcourseresourceGet", notes = "",
            response = CourseResourceVo.class, responseContainer = "List", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = CourseResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误")})
    @RequestMapping(value = "/allcourseresource",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseResourceVo>> allcourseresourceGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

    @ApiOperation(value = "根据courseId及teacherId获取备课包下测验资源", nickname = "getTestPapers",
            notes = "互动课堂备课包获取该老师该课程下的测验资源,接口做排序", response = TestPaperResource.class,
            responseContainer = "List", tags = {"TestPaper",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = TestPaperResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常，接受传入的参数类型不正确、必填参数未填写"),
            @ApiResponse(code = 403, message = "传入的加密参数未通过验证"),
            @ApiResponse(code = 404, message = "资源路径参数对应的资源未找到"),
            @ApiResponse(code = 409, message = "自定义错误")})
    @RequestMapping(value = "/resource/testpapers",
            method = RequestMethod.GET)
    ResponseEntity<List<TestPaperResource>> getTestPapers(@NotNull @ApiParam(value = "课程Id", required = true)
                                                          @Valid @RequestParam(value = "courseId", required = true) String courseId,
                                                          @NotNull @ApiParam(value = "教师Id", required = true)
                                                          @Valid @RequestParam(value = "teacherId", required = true) String teacherId,
                                                          @NotNull @ApiParam(value = "验证码（courseId={}&signKey=123123）", required = true)
                                                          @Valid @RequestParam(value = "validCode", required = true) String validCode,
                                                          @ApiParam(value = "测验名称")
                                                          @Valid @RequestParam(value = "testName", required = false) String testName);


    @ApiOperation(value = "根据课程名称/课程编号查询课程信息", nickname = "getCourseInfo", notes = "云课堂小程序端使用",
            response = CourseInfoPageVo.class, responseContainer = "List", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfoPageVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseresources/courseinfo",
            method = RequestMethod.GET)
    ResponseEntity<CourseInfoPageVo> getCourseInfo(
            @NotNull @ApiParam(value = "MD5加密验证字符串（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程名称/课程编号", required = true)
            @Valid @RequestParam(value = "courseNameOrNo", required = true) String courseNameOrNo,
            @NotNull @ApiParam(value = "当前页", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true)
            @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize);


    @ApiOperation(value = "查询基础课程信息；相同课程名称去重", nickname = "getFoundationCourseList"
            , notes = "使用方：1.赏课", response = FoundationCoursePageVo.class, tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = FoundationCoursePageVo.class),
            @ApiResponse(code = 400, message = "参数异常"),
            @ApiResponse(code = 403, message = "验证码错误"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/foundationcourse",
            method = RequestMethod.GET)
    ResponseEntity<FoundationCoursePageVo> getFoundationCourseList(
            @NotNull @ApiParam(value = "MD5加密验证字符串", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "当前页", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true)
            @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize,
            @ApiParam(value = "课程名称")
            @Valid @RequestParam(value = "courseName", required = false) String courseName,
            @ApiParam(value = "教师工号")
            @Valid @RequestParam(value = "teacherNo", required = false) String teacherNo,
            @ApiParam(value = "时间范围-开始时间")
            @Valid @RequestParam(value = "startTime", required = false) String startTime,
            @ApiParam(value = "时间范围-结束时间")
            @Valid @RequestParam(value = "endTime", required = false) String endTime);

    @ApiOperation(value = "查询基础课程删除状态", nickname = "getCourseDeleteState"
            , notes = "使用方：1.云课堂老师端——课程首页", response = Boolean.class, tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = Boolean.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/coursedeletestate",
            method = RequestMethod.GET)
    ResponseEntity<Boolean> getCourseDeleteState(
            @NotNull @ApiParam(value = "课程id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "验证码：courseId={xxx}&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(
            value = "根据查询在用的课程信息",
            nickname = "getAvailableCourseInfo",
            notes = "云课堂RPC使用",
            response = CourseInfosTO.class,
            responseContainer = "List",
            tags = {"CourseResource",}
    )
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfosTO.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/availablecourse",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfosTO>> getAvailableCourseInfo(
            @NotNull @ApiParam(value = "MD5加密验证字符串(&signKey=123123)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程名称或编号") @Valid @RequestParam(value = "courseNameOrNo", required = false) String courseNameOrNo,
            @ApiParam(value = "学院id") @Valid @RequestParam(value = "collegeId", required = false) String collegeId
    );

    @ApiOperation(value = "资源关联知识点", nickname = "addCourseResourceKnowledgePoint",
            notes = "1.云课堂老师端-课程建设使用", tags = {"CourseKnowledgeStructure",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务校验数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseresource/knowledgepoint",
            method = RequestMethod.POST)
    ResponseEntity<Void> addCourseResourceKnowledgePoint(@NotNull @ApiParam(value = "验证码（&signKey=123123）", required = true)
                                                         @Valid @RequestParam(value = "validCode", required = true)
                                                         String validCode,
                                                         @ApiParam(value = "", required = true) @Valid @RequestBody
                                                         CourseResourceKnowledgePointVo resourcePointVo);


    @ApiOperation(value = "根据课程编号精确查询课程信息", nickname = "getCourseInfoByCourseNo", notes = "调用方:teachingApi-题库导入接口",
            response = CourseInfoVo.class, tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfoVo.class),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "查询课程为空", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseresources/courseno",
            method = RequestMethod.GET)
    ResponseEntity<CourseInfoVo> getCourseInfoByCourseNo(
            @NotNull @ApiParam(value = "MD5加密验证字符串（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程编号", required = true)
            @Valid @RequestParam(value = "courseNo", required = true) String courseNo);

    @ApiOperation(value = "根据课程名称/课程编号模糊查询课程信息", nickname = "getCourseInfos", notes = "教研室平台 添加已有课程使用 ",
            response = CourseInfoResourceVo.class, responseContainer = "List", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfoResourceVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseresources/courseinfos",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfoResourceVo>> getCourseInfos(
            @NotNull @ApiParam(value = "MD5加密验证字符串（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "课程名称/课程编号", required = true)
            @Valid @RequestParam(value = "courseNameOrNo", required = true) String courseNameOrNo);


    @ApiOperation(value = "新增课程", nickname = "addCourse", notes = "使用方：1、云课堂管理端-课程信息数据-课程信息", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseresources",
            method = RequestMethod.POST)
    ResponseEntity<Void> addCourse(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程列表", required = true)
            @Valid @RequestBody CourseResourceInfoVo courseResourceInfoVo);


    @ApiOperation(value = "根据学院id获取学院下得所有课程", nickname = "getcourseinfosbycolegeids", notes = "使用方：1、学业支持-内部调用",
            response = CollegeCourseResource.class, responseContainer = "List", tags = {"CourseResources",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CollegeCourseResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/courseinfosbycollegeid",
            method = RequestMethod.POST)
    ResponseEntity<List<CollegeCourseResource>> getCourseInfosByColegeIds(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "学院Id列表", required = true) @Valid @RequestBody List<String> collegeIds);

    @ApiOperation(value = "查询课程信息", nickname = "queryCourseList", notes = "1、云课堂管理端使用",
            response = CourseInfoVo.class, responseContainer = "List", tags={ "CourseResources", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = CourseInfoVo.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常") })
    @RequestMapping(value = "/course/query",
            method = RequestMethod.GET)
    ResponseEntity<List<CourseInfoVo>> queryCourseList(
            @NotNull @ApiParam(value = "加密验证码（&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "课程名称或课程编号") @Valid @RequestParam(value = "courseNameOrNo", required = false)
            String courseNameOrNo);

}
