/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.projectcard;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import com.lztech.site.viewmodel.projectcard.ProjectCardPageVo;
import com.lztech.site.viewmodel.projectcard.ProjectCardVo;
import com.lztech.site.viewmodel.projectsuite.ProjectSuiteResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-19T10:55:50.034Z")

@Api(value = "projectcard", description = "the projectcard API")
@RequestMapping(value = "/v1")
public interface ProjectcardApi {

    @ApiOperation(value = "根据项目id获取项目套件", nickname = "getProjectSuiteByProjectIds",
            notes = "teaching项目保存二次排课记录调用", response = ProjectSuiteResource.class,
            responseContainer = "List", tags = {"teachingcalendar",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "获取成功", response = ProjectSuiteResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数异常，接受传入的参数类型不正确、必填参数未填写", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "传入的加密参数未通过验证", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "资源路径参数对应的资源未找到", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "文件操作IO异常等")})
    @RequestMapping(value = "/projectcard/projectsuitebyprojectids",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<ProjectSuiteResource>> getProjectSuiteByProjectIds(
            @NotNull @ApiParam(value = "课程Id", required = true)
            @Valid @RequestParam(value = "courseId", required = true) String courseId,
            @NotNull @ApiParam(value = "项目id（多个用逗号“,”隔开）", required = true)
            @Valid @RequestParam(value = "projectIds", required = true) String projectIds,
            @NotNull @ApiParam(value = "验证码（courseId=XXX&signKey=123123）", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "根据课程id、项目名称获取项目卡列表", nickname = "projectCardGet", notes = "云课堂管理端项目卡管理使用",
            response = ProjectCardPageVo.class, tags={ "projectCard", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功", response = ProjectCardPageVo.class),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/projectCard",
            method = RequestMethod.GET)
    ResponseEntity<ProjectCardPageVo> projectCardGet(
            @NotNull @ApiParam(value = "MD5加密验证字符串&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "当前页", required = true)
            @Valid @RequestParam(value = "page", required = true) Integer page,
            @NotNull @ApiParam(value = "每页个数", required = true)
            @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize,
            @ApiParam(value = "项目名称") @Valid @RequestParam(value = "projectName", required = false) String projectName,
            @ApiParam(value = "所属课程id") @Valid @RequestParam(value = "courseId", required = false) String courseId);
    @ApiOperation(value = "添加项目卡信息", nickname = "projectCardPost", notes = "云课堂管理端项目卡管理使用", tags={ "projectCard", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/projectCard",
            method = RequestMethod.POST)
    ResponseEntity<Void> projectCardPost(
            @NotNull @ApiParam(value = "MD5加密验证字符串&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @ApiParam(value = "" ,required=true )  @Valid @RequestBody ProjectCardVo projectCardVo);

    @ApiOperation(value = "根据项目卡id，删除项目卡及其相关内容", nickname = "projectCardDelete",
            notes = "云课堂管理端项目卡管理使用", tags={ "projectCard", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "操作成功"),
            @ApiResponse(code = 400, message = "参数异常", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到套件信息", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常", response = ErrorResult.class) })
    @RequestMapping(value = "/projectCard/delete",
            method = RequestMethod.POST)
    ResponseEntity<Void> projectCardDelete(
            @NotNull @ApiParam(value = "projectCardIds=?&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode,
            @NotNull @ApiParam(value = "项目卡id(逗号分割)", required = true)
            @Valid @RequestParam(value = "projectCardIds", required = true) String projectCardIds);





}
