/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.lowvaluearticles;

import com.lztech.site.viewmodel.lowvaluearticles.LowValueArticlesResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-26T12:20:14.639Z")

@Api(value = "lowvaluearticles", description = "the lowvaluearticles API")
@RequestMapping(value = "/v1")
public interface LowvaluearticlesApi {

    @ApiOperation(value = "根据预约项目Id获取低值易耗物品信息", nickname = "lowvaluearticlesGet", notes = "云课堂服务接口调用",
            response = LowValueArticlesResource.class, responseContainer = "List", tags = {"LowValueArticles",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = LowValueArticlesResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 403, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到视频资源文件信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/lowvaluearticles",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<LowValueArticlesResource>> lowvaluearticlesGet(
            @NotNull @ApiParam(value = "项目Id,多个使用‘,’分割", required = true)
            @Valid @RequestParam(value = "appointmentProjectIds", required = true) String appointmentProjectIds,
            @NotNull @ApiParam(value = "预约人员数据", required = true)
            @Valid @RequestParam(value = "appointmentPeopleNumber", required = true) Integer appointmentPeopleNumber,
            @NotNull @ApiParam(value = "MD5加密验证字符串 &signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
