/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.teachingclass;

import com.lztech.site.resource.teachingclass.TeachingClassResource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-17T03:10:25.361Z")

@Api(value = "teachingclasses", description = "the teachingclasses API")
public interface TeachingclassesApi {

    @ApiOperation(value = "根据班级id查询班级信息", nickname = "teachingclassesGet", notes = "云课堂前端使用",
            response = TeachingClassResource.class, responseContainer = "List", tags = {"TeachingClassResource",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功", response = TeachingClassResource.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "参数不正确"),
            @ApiResponse(code = 401, message = "解密验证失败"),
            @ApiResponse(code = 404, message = "未找到课表信息"),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/v1/teachingclasses",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<TeachingClassResource>> teachingclassesGet(
            @NotNull @ApiParam(value = "班级ID,多个用“,”隔开", required = true)
            @Valid @RequestParam(value = "teachingClassIds", required = true) String teachingClassIds,
            @NotNull @ApiParam(value = "加密验证码&signKey=123123", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);

}
