/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lztech.site.controllers.api.resourcereferences;

import com.lztech.site.viewmodel.errorresult.ErrorResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-05T08:18:49.495Z")

@Validated
@Api(value = "resourcereferences", description = "the resourcereferences API")
@RequestMapping(value = "/v1")
public interface ResourcereferencesApi {

    @ApiOperation(value = "接口-更新下载资源引用次数", nickname = "resourcereferencesPost", notes = "1.云课堂老师端课程管理,备课包使用", tags = {"ResourceReferences",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/resourcereferences",
            produces = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> resourcereferencesPost(
            @NotNull @ApiParam(value = "资源Id,多个以‘,’分割", required = true)
            @Valid @RequestParam(value = "resourceIds", required = true) String resourceIds,
            @ApiParam(value = "引用人id")
            @Valid @RequestParam(value = "quotePeopleId", required = false) String quotePeopleId,
            @NotNull @ApiParam(value = "验证码：&signKey=123123(md5加密)", required = true)
            @Valid @RequestParam(value = "validCode", required = true) String validCode);


    @ApiOperation(value = "根据资源详情id更新资源引用数量",
            nickname = "updateReferenceNumByResourceDetailId",
            notes = "1.互动课堂-发起分组讨论使用", tags = {"ResourceReferences",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功"),
            @ApiResponse(code = 400, message = "参数不正确", response = ErrorResult.class),
            @ApiResponse(code = 403, message = "验证码错误", response = ErrorResult.class),
            @ApiResponse(code = 404, message = "未找到资源信息", response = ErrorResult.class),
            @ApiResponse(code = 409, message = "业务数据错误", response = ErrorResult.class),
            @ApiResponse(code = 500, message = "服务器异常")})
    @RequestMapping(value = "/resource/references/updatebyresourcedetail",
            method = RequestMethod.POST)
    ResponseEntity<Void> updateReferenceNumByResourceDetailId(@NotNull @ApiParam(value = "资源详情Id", required = true)
                                                              @Valid @RequestParam(value = "resourceDetailId", required = true)
                                                                      String resourceDetailId,
                                                              @NotNull @ApiParam(value = "验证码：resourceDetailId={}&signKey=123123(md5加密)",
                                                                      required = true)
                                                              @Valid @RequestParam(value = "validCode", required = true)
                                                                      String validCode);

}
